// ==========================================================
// GOSPEL TRACTS i18n — STRUGGLE category, Part 2 of 3 (tracts 116-120)
// Translated into all 8 languages. Merge with base GOSPEL_TRACTS data
// (id, category, color, title, verses stay the same across languages —
// only hook/body/repentance/prayer prose changes per language).
// ==========================================================
const TRACTS_I18N_STRUGGLE_P2 = {
  "en": {
    "116": {
      "hook": "Jesus wept. God is not asking you to pretend.",
      "body": "John 11:35 is the shortest verse in the Bible: \"Jesus wept.\" He was standing outside the tomb of Lazarus — a man He was about to raise from the dead. He knew the end of the story. And He still wept. Not as performance. As genuine grief over genuine loss — and genuine empathy with the grief of those around Him.\n\nThe Psalms are the Bible's model for honest grief. Psalm 88 ends without resolution, without a turn toward praise, without a happy ending — just \"darkness is my closest friend\" (Psalm 88:18). And that psalm is in the Bible. God included the unresolved grief alongside the triumphant worship. Because He is not afraid of the grief, and He does not demand resolution before He will hear you.\n\n\"He heals the brokenhearted and binds up their wounds\" (Psalm 147:3). The healing is real. The binding is real. But it begins with the acknowledgment of the wound. God does not heal what is not brought to Him. Bring the grief — all of it, in whatever form it takes.",
      "repentance": "Bring your grief to God. Not the managed version — the real one. He is not asking you to perform peace you do not feel. He is asking you to come with what you actually have.",
      "prayer": "Lord, I bring You my grief today — the full weight of it, without minimizing. You wept at Lazarus's tomb even knowing the resurrection was coming. Weep with me in this. Bind my wound. Heal what is broken. I trust that You know the way through this darkness. Amen."
    },
    "117": {
      "hook": "You feel alone. You are not.",
      "body": "\"Never will I leave you; never will I forsake you\" (Hebrews 13:5). The Greek construction uses five negatives for emphasis: I will never, not ever, under no circumstances, under no condition, leave you. This promise was spoken into the fear of facing the unknown without support — and it has not expired.\n\nJesus told His disciples: \"And surely I am with you always, to the very end of the age\" (Matthew 28:20). Always. Not in retrospect, not in principle, not when you feel it. Always. The presence of Jesus is not contingent on your perception of it. It is not a feeling. It is a fact.\n\nPsalm 23 was written by David — a man who had been genuinely alone: in the wilderness, in caves, fleeing from a son who was trying to kill him. And he wrote: \"Even though I walk through the darkest valley, I will fear no evil, for you are with me.\" Not \"I feel Your presence\" — You are with me. The companionship of God does not require your feelings to authenticate it.",
      "repentance": "God's presence is not contingent on your feelings. Declare it today as a fact, even if you cannot feel it: You are with me. And let that fact begin to push through the feeling.",
      "prayer": "Lord, I feel alone. But I choose to believe what You said rather than what I feel. You said: Never will I leave you. I take that promise into the loneliness today. You are with me — even here, even now, even in the silence. I am not alone. Amen."
    },
    "118": {
      "hook": "Delay is not denial. God's calendar is different from yours.",
      "body": "Hannah prayed for a son year after year (1 Samuel 1). She went to the temple and prayed so fervently that Eli the priest thought she was drunk. She wept. She kept praying. And \"the LORD remembered her\" (1 Samuel 1:19) — not because she finally prayed the right prayer, but because the time had come. The wait was not delay. It was preparation — for a child who would become one of the greatest prophets in Israel's history.\n\nThe parable of the persistent widow (Luke 18:1-8) was told specifically \"to show them that they should always pray and not give up.\" The widow was not told to stop asking. She was told the asking itself was the right response to the delay. Not passive resignation. Active, persistent, even stubborn faith.\n\nHabakkuk 2:3: \"For the revelation awaits an appointed time; it speaks of the end and will not prove false. Though it linger, wait for it; it will certainly come and will not delay.\" The appointed time is real. The \"lingering\" is not evidence of indifference. It is the space between the promise and the fulfilment — and that space is meant to be filled with faith.",
      "repentance": "Do not interpret unanswered prayer as unheard prayer. Keep asking. Keep knocking. The appointed time is real.",
      "prayer": "Lord, I have been praying and I have not seen the answer yet. I choose today not to give up. I bring my request again — persistently, faithfully. I trust that the delay is not denial. I trust that the appointed time is real. I keep asking. Amen."
    },
    "119": {
      "hook": "The race you are in is yours. Stop watching someone else's lane.",
      "body": "Peter, newly commissioned by Jesus, looked at another disciple and asked: \"Lord, what about him?\" (John 21:21). He had just received his specific call — \"Feed my sheep\" — and immediately looked sideways at someone else's calling. Jesus' response was direct: \"What is that to you? You must follow me\" (John 21:22). What is that to you. Your lane. Follow me.\n\nComparison is a thief. It steals joy from what God is doing in your life by making you measure it against what He is doing in someone else's. It is also a category error — comparing your chapter 1 to someone else's chapter 40, your private struggles to someone else's public achievements. Paul warned: \"When they measure themselves by themselves and compare themselves with themselves, they are not wise\" (2 Corinthians 10:12).\n\nYou were not given someone else's race. You were given yours — with your specific gifts, your specific assignment, your specific timing. \"Each one should test their own actions. Then they can take pride in themselves alone, without comparing themselves to someone else\" (Galatians 6:4). Your faithfulness in your lane is the only faithfulness that counts.",
      "repentance": "Stop looking sideways. Jesus said: what is that to you? You must follow me. Return your attention to your lane, your calling, your faithfulness.",
      "prayer": "Lord, I confess that I have been watching other people's lanes and losing sight of mine. I hear Your word: what is that to you? You must follow me. I return my eyes to You today. I run my race. I fulfil my calling. I stop comparing and start following. Amen."
    },
    "120": {
      "hook": "Testing was not designed to destroy your faith. It was designed to prove it.",
      "body": "James 1:2-4: \"Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance. Let perseverance finish its work so that you may be mature and complete, not lacking anything.\" Pure joy — a genuine orientation that comes from knowing what the testing is producing.\n\nThe testing of your faith is not evidence that God has abandoned you. It is evidence that you are in the refinery. Job's declaration from the ash heap: \"When he has tested me, I will come forth as gold\" (Job 23:10). The Refiner does not heat the metal to destroy it. He heats it to purify it. The process is painful. The product is precious.\n\n1 Peter 1:6-7: \"In all this you greatly rejoice, though now for a little while you may have had to suffer grief in all kinds of trials. These have come so that the proven genuineness of your faith — of greater worth than gold, which perishes even though refined by fire — may result in praise, glory and honour when Jesus Christ is revealed.\" The proven genuineness — faith that has been tested and held — is of greater worth than gold.",
      "repentance": "Look at the trial you are in. Ask what God is producing in it. Let perseverance finish its work. The fire is not meant to destroy you. It is meant to prove what is real.",
      "prayer": "Lord, I choose to see this trial through Your lens. I know that the testing of my faith produces perseverance. Let perseverance finish its work. Let me come forth as gold — proven, purified, and of greater worth than when I entered the fire. Amen."
    }
  },
  "fr": {
    "116": {
      "hook": "Jésus pleura. Dieu ne te demande pas de faire semblant.",
      "body": "Jean 11.35 est le verset le plus court de la Bible : « Jésus pleura. » Il se tenait devant le tombeau de Lazare — un homme qu'Il était sur le point de ressusciter. Il connaissait la fin de l'histoire. Et Il pleura quand même. Pas comme une mise en scène. Comme un chagrin authentique face à une perte authentique — et une empathie authentique envers le deuil de ceux qui L'entouraient.\n\nLes Psaumes sont le modèle biblique du deuil honnête. Le Psaume 88 se termine sans résolution, sans un élan vers la louange, sans une fin heureuse — juste « les ténèbres sont mon seul compagnon » (Psaume 88.18). Et ce psaume est dans la Bible. Dieu a inclus le deuil non résolu à côté de l'adoration triomphante. Parce qu'Il n'a pas peur du deuil, et Il n'exige pas de résolution avant de t'écouter.\n\n« Il guérit ceux qui ont le cœur brisé, et il panse leurs blessures » (Psaume 147.3). La guérison est réelle. Le pansement est réel. Mais cela commence par la reconnaissance de la blessure. Dieu ne guérit pas ce qui ne Lui est pas apporté. Apporte ton deuil — tout entier, sous quelque forme qu'il prenne.",
      "repentance": "Apporte ton deuil à Dieu. Pas la version gérée — la vraie. Il ne te demande pas de jouer une paix que tu ne ressens pas. Il te demande de venir avec ce que tu as réellement.",
      "prayer": "Seigneur, je T'apporte mon deuil aujourd'hui — tout son poids, sans le minimiser. Tu as pleuré au tombeau de Lazare tout en sachant que la résurrection arrivait. Pleure avec moi dans cela. Panse ma blessure. Guéris ce qui est brisé. Je fais confiance que Tu connais le chemin à travers ces ténèbres. Amen."
    },
    "117": {
      "hook": "Tu te sens seul. Tu ne l'es pas.",
      "body": "« Je ne te délaisserai point, et je ne t'abandonnerai point » (Hébreux 13.5). La construction grecque utilise cinq négations pour l'emphase : je ne te laisserai jamais, en aucun cas, sous aucune condition, ne t'abandonnerai. Cette promesse a été prononcée dans la peur de faire face à l'inconnu sans soutien — et elle n'a pas expiré.\n\nJésus a dit à Ses disciples : « Et voici, je suis avec vous tous les jours, jusqu'à la fin du monde » (Matthieu 28.20). Toujours. Pas rétrospectivement, pas en principe, pas quand tu le ressens. Toujours. La présence de Jésus ne dépend pas de ta perception de celle-ci. Ce n'est pas un sentiment. C'est un fait.\n\nLe Psaume 23 a été écrit par David — un homme qui avait été véritablement seul : dans le désert, dans des grottes, fuyant un fils qui essayait de le tuer. Et il a écrit : « Quand je marche dans la vallée de l'ombre de la mort, je ne crains aucun mal, car tu es avec moi. » Pas « je sens Ta présence » — Tu es avec moi. La compagnie de Dieu n'a pas besoin de tes sentiments pour l'authentifier.",
      "repentance": "La présence de Dieu ne dépend pas de tes sentiments. Déclare-le aujourd'hui comme un fait, même si tu ne peux pas le sentir : Tu es avec moi. Et laisse ce fait commencer à percer le sentiment.",
      "prayer": "Seigneur, je me sens seul. Mais je choisis de croire ce que Tu as dit plutôt que ce que je ressens. Tu as dit : Je ne te délaisserai point. Je prends cette promesse dans la solitude aujourd'hui. Tu es avec moi — même ici, même maintenant, même dans le silence. Je ne suis pas seul. Amen."
    },
    "118": {
      "hook": "Le délai n'est pas un refus. Le calendrier de Dieu est différent du tien.",
      "body": "Anne a prié pour un fils année après année (1 Samuel 1). Elle est allée au temple et a prié si ardemment que le prêtre Éli pensait qu'elle était ivre. Elle a pleuré. Elle a continué à prier. Et « l'Éternel se souvint d'elle » (1 Samuel 1.19) — non pas parce qu'elle avait enfin prié la bonne prière, mais parce que le temps était venu. L'attente n'était pas un délai. C'était une préparation — pour un enfant qui deviendrait l'un des plus grands prophètes de l'histoire d'Israël.\n\nLa parabole de la veuve persévérante (Luc 18.1-8) a été racontée spécifiquement « pour montrer qu'il faut toujours prier, et ne pas se relâcher. » La veuve n'a pas été invitée à arrêter de demander. On lui a montré que le fait même de demander était la bonne réponse au délai. Pas une résignation passive. Une foi active, persévérante, même tenace.\n\nHabacuc 2.3 : « Car c'est une révélation pour un temps fixé ; elle marche vers son terme, et elle ne mentira pas ; si elle tarde, attends-la, car elle s'accomplira, elle s'accomplira certainement. » Le temps fixé est réel. Le « retard » n'est pas une preuve d'indifférence. C'est l'espace entre la promesse et l'accomplissement — et cet espace est destiné à être rempli de foi.",
      "repentance": "N'interprète pas la prière sans réponse comme une prière non entendue. Continue à demander. Continue à frapper. Le temps fixé est réel.",
      "prayer": "Seigneur, je prie et je n'ai pas encore vu la réponse. Je choisis aujourd'hui de ne pas abandonner. J'apporte ma demande à nouveau — avec persévérance, avec fidélité. Je fais confiance que le délai n'est pas un refus. Je fais confiance que le temps fixé est réel. Je continue à demander. Amen."
    },
    "119": {
      "hook": "La course dans laquelle tu es est la tienne. Arrête de regarder la voie de quelqu'un d'autre.",
      "body": "Pierre, tout juste mandaté par Jésus, a regardé un autre disciple et a demandé : « Seigneur, et celui-ci, que lui arrivera-t-il ? » (Jean 21.21). Il venait de recevoir son appel spécifique — « Pais mes brebis » — et a immédiatement regardé de côté vers l'appel de quelqu'un d'autre. La réponse de Jésus fut directe : « Que t'importe ? Toi, suis-moi » (Jean 21.22). Que t'importe. Ta voie. Suis-moi.\n\nLa comparaison est une voleuse. Elle vole la joie de ce que Dieu fait dans ta vie en te faisant la mesurer par rapport à ce qu'Il fait dans celle de quelqu'un d'autre. C'est aussi une erreur de catégorie — comparer ton chapitre 1 au chapitre 40 de quelqu'un d'autre, tes luttes privées aux réussites publiques de quelqu'un d'autre. Paul a averti : « Ils ne sont pas sages, ceux qui se mesurent à leur propre mesure, et qui se comparent à eux-mêmes » (2 Corinthiens 10.12).\n\nTu n'as pas reçu la course de quelqu'un d'autre. Tu as reçu la tienne — avec tes dons spécifiques, ta mission spécifique, ton timing spécifique. « Que chacun examine ses propres œuvres, et alors il aura sujet de se glorifier pour lui seul, et non par rapport à autrui » (Galates 6.4). Ta fidélité dans ta voie est la seule fidélité qui compte.",
      "repentance": "Arrête de regarder de côté. Jésus a dit : que t'importe ? Toi, suis-moi. Reviens à ta voie, ton appel, ta fidélité.",
      "prayer": "Seigneur, je confesse que j'ai regardé les voies des autres et perdu de vue la mienne. J'entends Ta parole : que t'importe ? Toi, suis-moi. Je reviens mes yeux vers Toi aujourd'hui. Je cours ma course. J'accomplis mon appel. J'arrête de comparer et je commence à suivre. Amen."
    },
    "120": {
      "hook": "L'épreuve n'a pas été conçue pour détruire ta foi. Elle a été conçue pour la prouver.",
      "body": "Jacques 1.2-4 : « Mes frères, regardez comme un sujet de joie complète les diverses épreuves auxquelles vous pouvez être exposés, sachant que l'épreuve de votre foi produit la patience. Mais que la patience accomplisse parfaitement son œuvre, afin que vous soyez parfaits et accomplis, sans faillir en rien. » Une joie complète — une orientation authentique qui vient du fait de savoir ce que l'épreuve produit.\n\nL'épreuve de ta foi n'est pas la preuve que Dieu t'a abandonné. C'est la preuve que tu es dans la raffinerie. La déclaration de Job depuis le tas de cendres : « Quand il m'aura éprouvé, je sortirai comme l'or » (Job 23.10). Le Raffineur ne chauffe pas le métal pour le détruire. Il le chauffe pour le purifier. Le processus est douloureux. Le produit est précieux.\n\n1 Pierre 1.6-7 : « C'est là ce qui fait votre joie, quoique maintenant, puisqu'il le faut, vous soyez attristés pour un peu de temps par diverses épreuves, afin que l'épreuve de votre foi, plus précieuse que l'or périssable (qui cependant est éprouvé par le feu), ait pour résultat la louange, la gloire et l'honneur, lorsque Jésus-Christ apparaîtra. » L'authenticité prouvée — une foi qui a été éprouvée et qui a tenu — a plus de valeur que l'or.",
      "repentance": "Regarde l'épreuve dans laquelle tu es. Demande ce que Dieu produit à travers elle. Laisse la patience accomplir son œuvre. Le feu n'est pas destiné à te détruire. Il est destiné à prouver ce qui est réel.",
      "prayer": "Seigneur, je choisis de voir cette épreuve à travers Ton regard. Je sais que l'épreuve de ma foi produit la patience. Laisse la patience accomplir son œuvre. Que je sorte comme l'or — éprouvé, purifié, et de plus grande valeur qu'avant d'entrer dans le feu. Amen."
    }
  },
  "sw": {
    "116": {
      "hook": "Yesu alilia. Mungu hakuombi ujifanye.",
      "body": "Yohana 11:35 ni mstari mfupi zaidi katika Biblia: \"Yesu akalia machozi.\" Alikuwa amesimama nje ya kaburi la Lazaro — mtu ambaye alikuwa karibu kumfufua. Alijua mwisho wa hadithi. Na bado alilia. Si kama maonyesho. Kama huzuni halisi kwa hasara halisi — na huruma halisi kwa huzuni ya wale waliomzunguka.\n\nZaburi ni kielelezo cha Biblia cha huzuni ya uaminifu. Zaburi 88 inaisha bila azimio, bila kugeukia sifa, bila mwisho wa furaha — ni \"giza ndilo rafiki yangu wa karibu\" tu (Zaburi 88:18 - tafsiri ya mfano). Na zaburi hiyo ipo katika Biblia. Mungu aliweka huzuni isiyotatuliwa pamoja na ibada ya ushindi. Kwa sababu Yeye haogopi huzuni, wala hadai azimio kabla ya kukusikiliza.\n\n\"Awaponya wenye moyo uliovunjika, na kuziganga jeraha zao\" (Zaburi 147:3). Uponyaji ni halisi. Kufungwa kwa jeraha ni halisi. Lakini huanza na kutambua jeraha. Mungu hapaponyi kile ambacho hakijaletwa Kwake. Leta huzuni yako — yote, kwa umbo lolote inalochukua.",
      "repentance": "Leta huzuni yako kwa Mungu. Si toleo lililodhibitiwa — la kweli. Hakuombi uonyeshe amani usiyohisi. Anakuomba uje na kile ulicho nacho hasa.",
      "prayer": "Bwana, ninakuletea huzuni yangu leo — uzito wake wote, bila kupunguza. Ulilia kaburini kwa Lazaro hata ukijua ufufuo unakuja. Lia nami katika hili. Funga jeraha langu. Ponya kilichovunjika. Ninaamini unajua njia ya kupitia giza hili. Amina."
    },
    "117": {
      "hook": "Unahisi upweke. Hauko peke yako.",
      "body": "\"Sitakupungukia kamwe wala sitakuacha kamwe\" (Waebrania 13:5). Muundo wa Kigiriki hutumia vikanushi vitano kwa msisitizo: sitawahi, kamwe, chini ya hali yoyote, chini ya sharti lolote, kukuacha. Ahadi hii ilisemwa katika hofu ya kukabili yasiyojulikana bila msaada — na haijaisha muda wake.\n\nYesu aliwaambia wanafunzi Wake: \"Na tazama, mimi nipo pamoja nanyi siku zote, hata ukamilifu wa dahari\" (Mathayo 28:20). Daima. Si kwa kurudi nyuma, si kwa kanuni, si unapohisi. Daima. Uwepo wa Yesu hautegemei mtazamo wako juu yake. Si hisia. Ni ukweli.\n\nZaburi 23 iliandikwa na Daudi — mtu aliyekuwa peke yake kihalisi: nyikani, mapangoni, akikimbia mwanawe aliyekuwa akijaribu kumuua. Na aliandika: \"Ijapokuwa napita kati ya bonde la uvuli wa mauti, sitaogopa mabaya, kwa maana Wewe upo pamoja nami.\" Si \"nahisi uwepo Wako\" — Wewe upo pamoja nami. Ushirika wa Mungu hauitaji hisia zako kuuthibitisha.",
      "repentance": "Uwepo wa Mungu hautegemei hisia zako. Tangaza hilo leo kama ukweli, hata usipoweza kuuhisi: Wewe upo pamoja nami. Na wacha ukweli huo uanze kupenya hisia.",
      "prayer": "Bwana, nahisi upweke. Lakini ninachagua kuamini uliyosema kuliko ninavyohisi. Ulisema: Sitakupungukia kamwe. Ninachukua ahadi hiyo katika upweke leo. Wewe upo pamoja nami — hata hapa, hata sasa, hata katika ukimya. Sipo peke yangu. Amina."
    },
    "118": {
      "hook": "Kuchelewa si kukataa. Kalenda ya Mungu ni tofauti na yako.",
      "body": "Hana aliomba mtoto wa kiume mwaka baada ya mwaka (1 Samweli 1). Alikwenda hekaluni na kuomba kwa bidii sana hata kuhani Eli alidhani amelewa. Alilia. Aliendelea kuomba. Na \"Bwana akamkumbuka\" (1 Samweli 1:19) — si kwa sababu hatimaye aliomba sala sahihi, bali kwa sababu wakati ulikuwa umefika. Kusubiri hakukuwa kuchelewa. Ilikuwa maandalizi — kwa mtoto ambaye angekuwa mmoja wa manabii wakuu zaidi katika historia ya Israeli.\n\nMfano wa mjane mwenye kuendelea (Luka 18:1-8) ulisimuliwa mahususi \"kwamba imewapasa kuomba sikuzote, wasikate tamaa.\" Mjane hakuambiwa aache kuomba. Aliambiwa kuomba kwenyewe ndiyo jibu sahihi kwa kuchelewa. Si kujiuzulu kwa upole. Imani ya vitendo, ya kuendelea, hata ya ukaidi.\n\nHabakuki 2:3: \"Kwa maana maono hayo yangalikuwa yangali ya wakati ulioamriwa, yanahaha kuuelekea mwisho wake, wala hayatasema uongo; ijapokuwa yakikawia, yangoje; kwa kuwa hakika yatakuja, wala hayatakawia.\" Wakati ulioamriwa ni halisi. \"Kukawia\" si ushahidi wa kutojali. Ni nafasi kati ya ahadi na utimilifu wake — na nafasi hiyo imekusudiwa kujazwa na imani.",
      "repentance": "Usitafsiri sala isiyojibiwa kama sala isiyosikika. Endelea kuomba. Endelea kugonga. Wakati ulioamriwa ni halisi.",
      "prayer": "Bwana, nimekuwa nikiomba na sijaona jibu bado. Ninachagua leo kutokata tamaa. Ninaleta ombi langu tena — kwa uvumilivu, kwa uaminifu. Ninaamini kuchelewa si kukataa. Ninaamini wakati ulioamriwa ni halisi. Ninaendelea kuomba. Amina."
    },
    "119": {
      "hook": "Mbio unazokimbia ni zako. Acha kuangalia njia ya mtu mwingine.",
      "body": "Petro, aliyekuwa ametumwa hivi karibuni na Yesu, alimtazama mwanafunzi mwingine na kuuliza: \"Bwana, na huyu je?\" (Yohana 21:21). Alikuwa amepokea wito wake mahususi — \"Lisha kondoo zangu\" — na mara moja akaangalia kando kwenye wito wa mtu mwingine. Jibu la Yesu lilikuwa la moja kwa moja: \"Yakupasa nini wewe? Nifuate mimi\" (Yohana 21:22). Yakupasa nini. Njia yako. Nifuate.\n\nKulinganisha ni mwizi. Huiba furaha ya kile Mungu anachofanya katika maisha yako kwa kukufanya uipime dhidi ya kile anachofanya katika maisha ya mtu mwingine. Pia ni kosa la aina — kulinganisha sura yako ya kwanza na sura ya arobaini ya mtu mwingine, mapambano yako binafsi na mafanikio ya umma ya mtu mwingine. Paulo alionya: \"Wanapojipima nafsi zao na kujilinganisha wenyewe kwa wenyewe hawana akili\" (2 Wakorintho 10:12).\n\nHukupewa mbio za mtu mwingine. Ulipewa zako mwenyewe — pamoja na vipawa vyako mahususi, jukumu lako mahususi, wakati wako mahususi. \"Kila mtu na ajipime mwenyewe matendo yake, ndipo atakuwa na sababu ya kujisifu katika nafsi yake mwenyewe, wala si kwa kumhusu mwingine\" (Wagalatia 6:4). Uaminifu wako katika njia yako ndio uaminifu pekee unaohesabiwa.",
      "repentance": "Acha kuangalia kando. Yesu alisema: yakupasa nini? Nifuate. Rudisha fikira zako kwenye njia yako, wito wako, uaminifu wako.",
      "prayer": "Bwana, ninakiri kwamba nimekuwa nikiangalia njia za watu wengine na kupoteza mtazamo wa yangu. Nasikia neno Lako: yakupasa nini? Nifuate. Ninarudisha macho yangu Kwako leo. Ninakimbia mbio zangu. Ninatimiza wito wangu. Ninaacha kulinganisha na kuanza kufuata. Amina."
    },
    "120": {
      "hook": "Kujaribiwa hakukubuniwa kuharibu imani yako. Kulibuniwa kuithibitisha.",
      "body": "Yakobo 1:2-4: \"Ndugu zangu, hesabuni ya kuwa ni furaha tupu, mkiangukia katika majaribu mbalimbali, mkifahamu ya kuwa kujaribiwa kwa imani yenu huleta saburi. Saburi na iwe na kazi kamilifu, mpate kuwa wakamilifu na watimilifu, bila kupungukiwa na neno lolote.\" Furaha tupu — mwelekeo halisi unaotokana na kujua kile ambacho kujaribiwa kunazalisha.\n\nKujaribiwa kwa imani yako si ushahidi kwamba Mungu amekuacha. Ni ushahidi kwamba upo katika kinu cha kusafisha. Tamko la Ayubu kutoka lundo la majivu: \"Atakapokuwa amenijaribu, nitatoka kama dhahabu\" (Ayubu 23:10). Msafishaji hachomi chuma ili kukiharibu. Anakichoma ili kukisafisha. Mchakato una uchungu. Bidhaa ni ya thamani.\n\n1 Petro 1:6-7: \"Ndani yake mnashangilia sana; ijapokuwa sasa kwa kitambo kidogo, ikiwa ni lazima, mmehuzunishwa kwa majaribu mbalimbali; ili kwamba kujaribiwa kwa imani yenu, ambako ni kwa thamani kuu kuliko dhahabu ipoteayo, ijapokuwa hiyo dhahabu hujaribiwa kwa moto, kuonekane kuwa kwenye sifa na utukufu na heshima, katika kufunuliwa kwake Yesu Kristo.\" Uthibitisho wa uhalisi — imani iliyojaribiwa na kudumu — ina thamani kuu kuliko dhahabu.",
      "repentance": "Angalia jaribu ulilo ndani yake. Uliza Mungu anazalisha nini kupitia hilo. Wacha saburi ikamilishe kazi yake. Moto haukusudiwi kukuharibu. Umekusudiwa kuthibitisha kilicho halisi.",
      "prayer": "Bwana, ninachagua kuona jaribu hili kupitia mtazamo Wako. Najua kujaribiwa kwa imani yangu kunazalisha saburi. Wacha saburi ikamilishe kazi yake. Nitoke kama dhahabu — nikiwa nimethibitishwa, nikiwa safi, na wa thamani kuu kuliko nilipoingia motoni. Amina."
    }
  },
  "ar": {
    "116": {
      "hook": "بكى يسوع. الله لا يطلب منك أن تتظاهر.",
      "body": "يوحنا ١١: ٣٥ هو أقصر آية في الكتاب المقدس: «بكى يسوع.» كان واقفًا خارج قبر لعازر — رجل كان على وشك أن يقيمه من الأموات. كان يعرف نهاية القصة. ومع ذلك بكى. ليس كأداء تمثيلي. بل كحزن حقيقي على خسارة حقيقية — وتعاطف حقيقي مع حزن من حوله.\n\nالمزامير هي نموذج الكتاب المقدس للحزن الصادق. ينتهي المزمور ٨٨ دون حل، دون توجه نحو التسبيح، دون نهاية سعيدة — فقط «الظلمة صاحبي» (مزمور ٨٨: ١٨). وهذا المزمور موجود في الكتاب المقدس. أدرج الله الحزن غير المحلول جنبًا إلى جنب مع العبادة المنتصرة. لأنه لا يخاف من الحزن، ولا يطالب بحل قبل أن يستمع إليك.\n\n«يشفي منكسري القلب ويجبر كسرهم» (مزمور ١٤٧: ٣). الشفاء حقيقي. الجبر حقيقي. لكنه يبدأ بالاعتراف بالجرح. الله لا يشفي ما لا يُحضَر إليه. أحضر حزنك — كله، بأي شكل يتخذه.",
      "repentance": "أحضر حزنك إلى الله. ليس النسخة المُدارة — بل الحقيقية. هو لا يطلب منك أن تتظاهر بسلام لا تشعر به. يطلب منك أن تأتي بما لديك فعلاً.",
      "prayer": "يا رب، أحضر إليك حزني اليوم — بكل ثقله، دون تقليل. بكيت عند قبر لعازر مع علمك أن القيامة قادمة. ابكِ معي في هذا. اجبر جرحي. اشفِ ما هو مكسور. أثق أنك تعرف الطريق عبر هذا الظلام. آمين."
    },
    "117": {
      "hook": "تشعر بالوحدة. أنت لست وحيدًا.",
      "body": "«لن أهملك ولن أتركك» (عبرانيين ١٣: ٥). التركيب اليوناني يستخدم خمس نفيات للتأكيد: لن، أبدًا، تحت أي ظرف، تحت أي شرط، أتركك. قيل هذا الوعد في خوف مواجهة المجهول بلا سند — ولم تنته صلاحيته.\n\nقال يسوع لتلاميذه: «وها أنا معكم كل الأيام إلى انقضاء الدهر» (متى ٢٨: ٢٠). دائمًا. ليس بأثر رجعي، ليس من حيث المبدأ، ليس فقط عندما تشعر به. دائمًا. حضور يسوع لا يعتمد على إدراكك له. إنه ليس شعورًا. إنه حقيقة.\n\nكتب داود المزمور ٢٣ — رجل كان وحيدًا حقًا: في البرية، في الكهوف، هاربًا من ابن كان يحاول قتله. وكتب: «حتى لو سرت في وادي ظل الموت، لا أخاف شرًا لأنك أنت معي.» ليس «أشعر بحضورك» — بل أنت معي. رفقة الله لا تحتاج مشاعرك لتثبتها.",
      "repentance": "حضور الله لا يعتمد على مشاعرك. أعلنه اليوم كحقيقة، حتى لو لم تستطع الشعور به: أنت معي. ودع هذه الحقيقة تبدأ في اختراق الشعور.",
      "prayer": "يا رب، أشعر بالوحدة. لكنني أختار أن أؤمن بما قلته بدلاً مما أشعر به. قلت: لن أهملك. آخذ هذا الوعد إلى الوحدة اليوم. أنت معي — حتى هنا، حتى الآن، حتى في الصمت. أنا لست وحيدًا. آمين."
    },
    "118": {
      "hook": "التأخير ليس رفضًا. تقويم الله يختلف عن تقويمك.",
      "body": "صلت حنة من أجل ابن سنة بعد سنة (١ صموئيل ١). ذهبت إلى الهيكل وصلت بحرارة شديدة حتى ظن الكاهن عالي أنها سكرى. بكت. استمرت في الصلاة. و«ذكرها الرب» (١ صموئيل ١: ١٩) — ليس لأنها صلت أخيرًا الصلاة الصحيحة، بل لأن الوقت قد حان. الانتظار لم يكن تأخيرًا. كان استعدادًا — لطفل سيصبح أحد أعظم الأنبياء في تاريخ إسرائيل.\n\nمثل الأرملة الملحّة (لوقا ١٨: ١-٨) قيل تحديدًا «ليبين لهم أنه ينبغي أن يصلوا كل حين ولا يملّوا.» لم يُقل للأرملة أن تتوقف عن الطلب. قيل لها إن الطلب نفسه كان الاستجابة الصحيحة للتأخير. ليس استسلامًا سلبيًا. إيمان نشط، مثابر، بل عنيد.\n\nحبقوق ٢: ٣: «لأن الرؤيا بعد إلى الميعاد، وفي النهاية تتكلم ولا تكذب. إن أبطأت فانتظرها لأنها ستأتي، لا تتأخر.» الوقت المحدد حقيقي. «الإبطاء» ليس دليلاً على اللامبالاة. إنه المسافة بين الوعد وإتمامه — وهذه المسافة مُصممة لتُملأ بالإيمان.",
      "repentance": "لا تفسر الصلاة التي لم تُستجب بعد على أنها صلاة لم تُسمع. استمر في الطلب. استمر في القرع. الوقت المحدد حقيقي.",
      "prayer": "يا رب، لقد كنت أصلي ولم أرَ الإجابة بعد. أختار اليوم ألا أستسلم. أحضر طلبي مرة أخرى — بمثابرة، بأمانة. أثق أن التأخير ليس رفضًا. أثق أن الوقت المحدد حقيقي. أستمر في الطلب. آمين."
    },
    "119": {
      "hook": "السباق الذي أنت فيه هو سباقك. توقف عن مراقبة مسار شخص آخر.",
      "body": "بطرس، المُكلَّف حديثًا من يسوع، نظر إلى تلميذ آخر وسأل: «يا رب وهذا ما له؟» (يوحنا ٢١: ٢١). كان قد تلقى للتو دعوته المحددة — «ارعَ خرافي» — ونظر فورًا جانبًا إلى دعوة شخص آخر. كانت إجابة يسوع مباشرة: «ماذا لك؟ اتبعني أنت» (يوحنا ٢١: ٢٢). ماذا لك. مسارك. اتبعني.\n\nالمقارنة لص. تسرق الفرح مما يفعله الله في حياتك بجعلك تقيسه مقابل ما يفعله في حياة شخص آخر. إنها أيضًا خطأ في التصنيف — مقارنة فصلك الأول بفصل شخص آخر الأربعين، صراعاتك الخاصة بإنجازات شخص آخر العلنية. حذّر بولس: «لأنهم إذ يقيسون أنفسهم بأنفسهم ويقارنون أنفسهم بأنفسهم لا يفهمون» (٢ كورنثوس ١٠: ١٢).\n\nلم تُعطَ سباق شخص آخر. أُعطيت سباقك أنت — بمواهبك المحددة، ومهمتك المحددة، وتوقيتك المحدد. «ولكن ليمتحن كل واحد عمل نفسه، وحينئذ يكون له الفخر من جهة نفسه فقط لا من جهة غيره» (غلاطية ٦: ٤). أمانتك في مسارك هي الأمانة الوحيدة التي تُحسب.",
      "repentance": "توقف عن النظر جانبًا. قال يسوع: ماذا لك؟ اتبعني أنت. أعد انتباهك إلى مسارك، دعوتك، أمانتك.",
      "prayer": "يا رب، أعترف أنني كنت أراقب مسارات الآخرين وأفقد رؤية مساري. أسمع كلمتك: ماذا لك؟ اتبعني أنت. أعيد عيني إليك اليوم. أجري سباقي. أُتمم دعوتي. أتوقف عن المقارنة وأبدأ في الاتباع. آمين."
    },
    "120": {
      "hook": "لم يُصمَّم الاختبار لتدمير إيمانك. صُمم لإثباته.",
      "body": "يعقوب ١: ٢-٤: «احسبوه كل فرح يا إخوتي حينما تقعون في تجارب متنوعة، عالمين أن امتحان إيمانكم ينشئ صبرًا. فليكن للصبر عمل تام، لكي تكونوا كاملين وتامين غير ناقصين في شيء.» فرح تام — توجه حقيقي ينبع من معرفة ما ينتجه الاختبار.\n\nاختبار إيمانك ليس دليلاً على أن الله تخلى عنك. إنه دليل على أنك في المصفاة. إعلان أيوب من كومة الرماد: «إذا جربني خرجت كالذهب» (أيوب ٢٣: ١٠). المُنقّي لا يُسخّن المعدن ليدمره. يُسخّنه لينقّيه. العملية مؤلمة. المنتج ثمين.\n\n١ بطرس ١: ٦-٧: «الذي فيه تبتهجون، مع أنكم الآن إن كان يجب قليلاً تحزنون في تجارب متنوعة، لكي تكون تزكية إيمانكم أثمن من الذهب الفاني، مع أنه يُختبر بالنار، فتوجد للمدح والكرامة والمجد عند استعلان يسوع المسيح.» التزكية المُثبتة — إيمان اختُبر وثبت — أثمن من الذهب.",
      "repentance": "انظر إلى التجربة التي أنت فيها. اسأل ماذا ينتج الله من خلالها. دع الصبر يُتمم عمله. النار ليست مُخصصة لتدميرك. إنها مُخصصة لإثبات ما هو حقيقي.",
      "prayer": "يا رب، أختار أن أرى هذه التجربة من خلال منظورك. أعلم أن اختبار إيماني ينتج صبرًا. دع الصبر يُتمم عمله. دعني أخرج كالذهب — مُثبتًا، منقّى، وأثمن مما كنت عليه قبل دخول النار. آمين."
    }
  },
  "yo": {
    "116": {
      "hook": "Jésù sunkún. Ọlọ́run kò ní ọ láti díbọ́n.",
      "body": "Jòhánù 11:35 ni ẹsẹ tí ó kúrú jùlọ nínú Bíbélì: \"Jésù sunkún.\" Ó dúró ní ìta ibojì Lásárù — ọkùnrin kan tí ó fẹ́rẹ̀ jí dìde kúrò nínú òkú. Ó mọ òpin ìtàn náà. Síbẹ̀ ó sunkún. Kì í ṣe fún ìṣe. Ṣùgbọ́n bí ìbànújẹ́ tòótọ́ lórí ìpàdánù tòótọ́ — àti ìyọ́nú tòótọ́ fún ìbànújẹ́ àwọn tí ó yí i ká.\n\nÀwọn Sáàmù ni àwòrán Bíbélì fún ìbànújẹ́ olóòótọ́. Sáàmù 88 parí láìsí ìpinnu, láìsí yíyí sí ìyìn, láìsí òpin aládùn — kìkì \"òkùnkùn ni ọ̀rẹ́ mi tímọ́tímọ́\" (Sáàmù 88:18). Àti pé sáàmù náà wà nínú Bíbélì. Ọlọ́run fi ìbànújẹ́ tí kò yanjú sí ẹ̀gbẹ́ ìjọsìn ìṣẹ́gun. Nítorí Òun kò bẹ̀rù ìbànújẹ́, Òun kò sì béèrè ìpinnu kó tó gbọ́ ohùn rẹ.\n\n\"Ó ń wo àwọn oníròbìnújẹ́ ọkàn sàn, ó sì ń dì egbò wọn\" (Sáàmù 147:3). Ìwòsàn náà jẹ́ òtítọ́. Dídìí náà jẹ́ òtítọ́. Ṣùgbọ́n ó bẹ̀rẹ̀ pẹ̀lú jíjẹ́wọ́ egbò náà. Ọlọ́run kì í wo ohun tí a kò mú wá sọ́dọ̀ Rẹ̀ sàn. Mú ìbànújẹ́ rẹ wá — gbogbo rẹ̀, ní èyíkéyìí ìrísí tí ó fi hàn.",
      "repentance": "Mú ìbànújẹ́ rẹ wá sọ́dọ̀ Ọlọ́run. Kì í ṣe ẹ̀dà tí a ti darí — ti òtítọ́ ni. Kò béèrè kí o ṣe àṣehàn àlàáfíà tí o kò nímọ̀lára. Ó ń béèrè kí o wá pẹ̀lú ohun tí o ní gan-an.",
      "prayer": "Olúwa, mo mú ìbànújẹ́ mi wá sọ́dọ̀ Rẹ lónìí — gbogbo ìwúwo rẹ̀, láìdín kù. O sunkún ní ibojì Lásárù pàápàá bí O ṣe mọ̀ pé àjíǹde ń bọ̀. Sunkún pẹ̀lú mi nínú èyí. Dì egbò mi. Wo ohun tí ó ṣẹ́ sàn. Mo gbẹ́kẹ̀lé pé O mọ ọ̀nà la òkùnkùn yìí kọjá. Àmín."
    },
    "117": {
      "hook": "O rí i bí ẹni pé o dá wà. O kò dá wà.",
      "body": "\"Èmi kì yóò fi ọ sílẹ̀ láéláé, bẹ́ẹ̀ ni èmi kì yóò kọ̀ ọ́ sílẹ̀ láéláé\" (Hébérù 13:5). Ìṣètò Gíríìkì náà lo ìkọ̀sílẹ̀ márùn-ún fún ìtẹnumọ́: Èmi kì yóò, kì í ṣe rárá, kò sí ipò kankan, kò sí ipò kankan, fi ọ sílẹ̀. A sọ ìlérí yìí sínú ìbẹ̀rù dídojú kọ àìmọ̀ láìsí àtìlẹ́yìn — kò sì ti parí.\n\nJésù sọ fún àwọn ọmọ ẹ̀yìn Rẹ̀: \"Sì kíyèsíi, èmi wà pẹ̀lú yín nígbà gbogbo, títí dé òpin ayé\" (Mátíù 28:20). Nígbà gbogbo. Kì í ṣe ní ìrántí padà, kì í ṣe ní ìlànà, kì í ṣe nígbà tí o bá nímọ̀lára rẹ̀. Nígbà gbogbo. Wíwàníbẹ̀ Jésù kò gbẹ́kẹ̀lé bí o ṣe rí i. Kì í ṣe ìmọ̀lára. Òtítọ́ ni.\n\nDáfídì ni ó kọ Sáàmù 23 — ọkùnrin kan tí ó ti dá wà ní òtítọ́: nínú aginjù, nínú àpáta, ó ń sá fún ọmọkùnrin tí ó ń gbìyànjú láti pa á. Ó sì kọ: \"Bí mo tilẹ̀ ń rìn gba àfonífojì òjìji ikú já, èmi kì yóò bẹ̀rù ibi kan, nítorí Ìwọ wà pẹ̀lú mi.\" Kì í ṣe \"Mo nímọ̀lára wíwàníbẹ̀ Rẹ\" — Ìwọ wà pẹ̀lú mi. Ìbágbépọ̀ Ọlọ́run kò nílò ìmọ̀lára rẹ láti fi ẹ̀rí rẹ̀ hàn.",
      "repentance": "Wíwàníbẹ̀ Ọlọ́run kò gbẹ́kẹ̀lé ìmọ̀lára rẹ. Kéde rẹ̀ lónìí gẹ́gẹ́ bí òtítọ́, kódà bí o kò bá lè nímọ̀lára rẹ̀: Ìwọ wà pẹ̀lú mi. Kí òtítọ́ náà sì bẹ̀rẹ̀ láti gún ìmọ̀lára náà já.",
      "prayer": "Olúwa, mo rí i bí ẹni pé mo dá wà. Ṣùgbọ́n mo yàn láti gbàgbọ́ ohun tí O sọ ju bí mo ṣe nímọ̀lára rẹ̀ lọ. O sọ pé: Èmi kì yóò fi ọ sílẹ̀ láéláé. Mo mú ìlérí yẹn wá sínú ìdáwà lónìí. Ìwọ wà pẹ̀lú mi — kódà níbí, kódà báyìí, kódà nínú ìdákẹ́jẹ́ẹ́. Èmi kò dá wà. Àmín."
    },
    "118": {
      "hook": "Ìdádúró kì í ṣe ìkọ̀sílẹ̀. Kàlẹ́ńdà Ọlọ́run yàtọ̀ sí tìrẹ.",
      "body": "Hánà gbàdúrà fún ọmọkùnrin ní ọdún kọ̀ọ̀kan (1 Sámúẹ́lì 1). Ó lọ sí tẹ́mpìlì ó sì gbàdúrà pẹ̀lú ìtara tó bẹ́ẹ̀ tí Éli àlùfáà rò pé ó mutí yó. Ó sunkún. Ó ń bá a nìṣó ní gbígbàdúrà. Àti pé \"OLÚWA rántí i\" (1 Sámúẹ́lì 1:19) — kì í ṣe nítorí pé nígbẹ̀yìngbẹ́yín ó gbàdúrà àdúrà tí ó tọ́, ṣùgbọ́n nítorí pé àkókò náà ti dé. Ìdúró dè náà kì í ṣe ìdádúró. Ìmúrasílẹ̀ ni — fún ọmọ tí yóò di ọ̀kan lára àwọn wòlíì tí ó tóbi jùlọ nínú ìtàn Ísírẹ́lì.\n\nÀkàwé opó tí kì í fojú sọ́nà (Lúùkù 18:1-8) ni a sọ ní pàtàkì \"láti fi hàn wọ́n pé ó yẹ kí a máa gbàdúrà nígbà gbogbo, kí a má sì rẹ̀wẹ̀sì.\" A kò sọ fún opó náà láti dáwọ́ béèrè dúró. A sọ fún un pé bíbéèrè fúnra rẹ̀ ni ìdáhùn tí ó tọ́ sí ìdádúró náà. Kì í ṣe ìfarasin palolo. Ìgbàgbọ́ tí ó ṣiṣẹ́, tí ó dúró ṣinṣin, kódà tí ó le koko.\n\nHábákúkù 2:3: \"Nítorí ìran náà ṣì ń dúró de àkókò tí a yàn, ó sì ń yára lọ sí òpin, kì yóò sì purọ́: bí ó tilẹ̀ pẹ́, dúró de e; nítorí ó dájú pé yóò dé, kì yóò sì fà sẹ́yìn.\" Àkókò tí a yàn jẹ́ òtítọ́. \"Ìpẹ́\" náà kì í ṣe ẹ̀rí àìṣàníyàn. Ó jẹ́ àyè láàrin ìlérí àti ìmúṣẹ — àyè náà sì ní láti kún fún ìgbàgbọ́.",
      "repentance": "Má ṣe túmọ̀ àdúrà tí a kò dá lóhùn gẹ́gẹ́ bí àdúrà tí a kò gbọ́. Máa bá a nìṣó ní bíbéèrè. Máa bá a nìṣó ní kíkànkùn. Àkókò tí a yàn jẹ́ òtítọ́.",
      "prayer": "Olúwa, mo ti ń gbàdúrà, èmi kò sì tíì rí ìdáhùn náà. Mo yàn lónìí láti má fi sílẹ̀. Mo mú ìbéèrè mi wá padà — pẹ̀lú ìdúró ṣinṣin, pẹ̀lú òtítọ́ inú. Mo gbẹ́kẹ̀lé pé ìdádúró náà kì í ṣe ìkọ̀sílẹ̀. Mo gbẹ́kẹ̀lé pé àkókò tí a yàn jẹ́ òtítọ́. Mo ń bá a nìṣó ní bíbéèrè. Àmín."
    },
    "119": {
      "hook": "Eré-ìje tí o wà nínú rẹ̀ jẹ́ tìrẹ. Dáwọ́ wíwo ipa ọ̀nà ẹlòmíràn dúró.",
      "body": "Pétérù, tí Jésù ṣẹ̀ṣẹ̀ fi àṣẹ fún, wo ọmọ ẹ̀yìn mìíràn ó sì béèrè pé: \"Olúwa, ǹjẹ́ kí ni ti ẹni yìí?\" (Jòhánù 21:21). Ó ṣẹ̀ṣẹ̀ gba ìpè rẹ̀ pàtàkì — \"Bọ́ àwọn àgùntàn mi\" — ó sì lẹ́sẹ̀kẹsẹ̀ wo ìhà ìpè ẹlòmíràn. Ìdáhùn Jésù jẹ́ tààrà: \"Kín ni ti ìwọ nínú rẹ̀? Máa tọ̀ mí lẹ́yìn ìwọ\" (Jòhánù 21:22). Kín ni ti ìwọ nínú rẹ̀. Ipa ọ̀nà rẹ. Tọ̀ mí lẹ́yìn.\n\nỌ̀wọ́ ọ̀tọ̀ jẹ́ olè. Ó ń jí ayọ̀ ohun tí Ọlọ́run ń ṣe nínú ìgbésí ayé rẹ nípa mímú kí o díwọ̀n rẹ̀ lòdì sí ohun tí Ó ń ṣe nínú ti ẹlòmíràn. Ó tún jẹ́ àṣìṣe ìsọ̀rí — fífi orí kìíní rẹ wéra pẹ̀lú orí ogójì ẹlòmíràn, ìjàkadì àdáni rẹ pẹ̀lú àṣeyọrí gbangba ẹlòmíràn. Pọ́ọ̀lù kìlọ̀ pé: \"Nígbà tí wọ́n bá fi ara wọn wéra pẹ̀lú ara wọn, tí wọ́n sì ń fi ara wọn wéra, wọn kò gbọ́n\" (2 Kọ́ríntì 10:12).\n\nA kò fún ọ ní eré-ìje ẹlòmíràn. A fún ọ ní tìrẹ — pẹ̀lú ẹ̀bùn rẹ pàtàkì, iṣẹ́ rẹ pàtàkì, àkókò rẹ pàtàkì. \"Ṣùgbọ́n kí olúkúlùkù ẹ̀dá dán iṣẹ́ ara rẹ̀ wò, nígbà náà ni yóò ní ìṣògo nínú ara rẹ̀ nìkan, kì í ṣe nínú ẹlòmíràn\" (Gálátíà 6:4). Òtítọ́ ìnú rẹ nínú ipa ọ̀nà rẹ nìkan ni òtítọ́ ìnú tí ó ka.",
      "repentance": "Dáwọ́ wíwo ìhà dúró. Jésù sọ pé: kín ni ti ìwọ nínú rẹ̀? Máa tọ̀ mí lẹ́yìn ìwọ. Padà sí ipa ọ̀nà rẹ, ìpè rẹ, òtítọ́ ìnú rẹ.",
      "prayer": "Olúwa, mo jẹ́wọ́ pé mo ti ń wo ipa ọ̀nà àwọn ẹlòmíràn tí mo sì ń pàdánù ìríran tèmi. Mo gbọ́ ọ̀rọ̀ Rẹ: kín ni ti ìwọ nínú rẹ̀? Máa tọ̀ mí lẹ́yìn ìwọ. Mo dá ojú mi padà sí ọ̀dọ̀ Rẹ lónìí. Mo sáré eré-ìje mi. Mo mú ìpè mi ṣẹ. Mo dáwọ́ ọ̀wọ́-ọ̀tọ̀ dúró mo sì bẹ̀rẹ̀ títẹ̀lé. Àmín."
    },
    "120": {
      "hook": "A kò ṣe àdánwò láti pa ìgbàgbọ́ rẹ run. A ṣe é láti fi hàn.",
      "body": "Jákọ́bù 1:2-4: \"Ẹ ka gbogbo rẹ̀ sí ohun ìdùnnú, ará mi, nígbà tí ẹ bá bọ́ sínú onírúurú àdánwò; kí ẹ mọ̀ pé, ìdánwò ìgbàgbọ́ yín ń mú sùúrù jáde. Ṣùgbọ́n kí sùúrù ní iṣẹ́ pípé, kí ẹ̀yin lè jẹ́ pípé àti odidi, láìsí àìní ohunkóhun.\" Ìdùnnú tí ó pé — ẹ̀mí tòótọ́ tí ó ti mímọ̀ ohun tí àdánwò náà ń mú jáde.\n\nÀdánwò ìgbàgbọ́ rẹ kì í ṣe ẹ̀rí pé Ọlọ́run ti kọ̀ ọ́ sílẹ̀. Ẹ̀rí ni pé o wà nínú ilé-iṣẹ́ ìtúnṣe. Ìkéde Jóòbù láti orí òkìtì eérú: \"Nígbà tí ó bá ti dán mi wò, èmi yóò jáde bí wúrà\" (Jóòbù 23:10). Aṣàtúnṣe kì í mú irin gbóná láti pa á run. Ó ń mú un gbóná láti sọ di mímọ́. Ìlànà náà ń dùn. Ọjà náà níyelórí.\n\n1 Pétérù 1:6-7: \"Nínú èyí tí ẹ̀yin ń yọ̀ gidigidi, bí ó tilẹ̀ jẹ́ pé nísisìyí fún sáà kékeré, bí ó bá pọndandan, a ti mú ẹ̀yin banújẹ́ nínú onírúurú ìdánwò: kí ìdánwò ìgbàgbọ́ yín, tí ó níyelórí ju wúrà tí ń ṣègbé lọ, bí a tilẹ̀ dán an wò nínú iná, kí a lè rí i pé ó lẹ́sìn sí ìyìn àti ọlá àti ògo ní ìfarahàn Jésù Kristi.\" Ìjẹ́rìísí tí a fi hàn — ìgbàgbọ́ tí a ti dán wò tí ó sì dúró — níyelórí ju wúrà lọ.",
      "repentance": "Wo àdánwò tí o wà nínú rẹ̀. Béèrè ohun tí Ọlọ́run ń mú jáde nínú rẹ̀. Jẹ́ kí sùúrù parí iṣẹ́ rẹ̀. Iná náà kò ní ète láti pa ọ́ run. Ó ní ète láti fi ohun tí ó jẹ́ òtítọ́ hàn.",
      "prayer": "Olúwa, mo yàn láti wo àdánwò yìí nípasẹ̀ ojú Rẹ. Mo mọ̀ pé àdánwò ìgbàgbọ́ mi ń mú sùúrù jáde. Jẹ́ kí sùúrù parí iṣẹ́ rẹ̀. Jẹ́ kí n jáde bí wúrà — tí a ti fi hàn, tí a ti sọ di mímọ́, tí ó sì níyelórí ju ìgbà tí mo wọ inú iná lọ. Àmín."
    }
  },
  "ig": {
    "116": {
      "hook": "Jizọs bere ákwá. Chineke anaghị agwa gị ka ị mee ka a ga-eme.",
      "body": "Jọn 11:35 bụ amaokwu kacha dị mkpirikpi n'ime Baịbụl: \"Jizọs bere ákwá.\" Ọ na-eguzo n'èzí ili Lazarọs — nwoke ọ na-achọ ikpọlite n'ọnwụ. Ọ maara ngwụcha akụkọ ahụ. Ma o bere ákwá. Ọ bụghị dịka ihe ngosi. Kama dịka mwute n'ezie maka mfu n'ezie — na mmetụta ọmịiko n'ezie maka mwute nke ndị gbara ya gburugburu.\n\nAbụ Ọma bụ ihe atụ Baịbụl maka mwute n'ezi okwu. Abụ Ọma nke 88 na-akwụsị na-enweghị ngwụcha, na-enweghị ntụgharị gaa n'otuto, na-enweghị ngwụcha obi ụtọ — naanị \"ọchịchịrị bụ enyi m kachasị nso\" (Abụ Ọma 88:18). Abụ ọma ahụ dị n'ime Baịbụl. Chineke tinyere mwute na-edozibeghị n'akụkụ ofufe mmeri. N'ihi na ọ dịghị atụ egwu mwute, ọ dịghịkwa achọ ka a dozie ihe tupu ọ ga-ege gị ntị.\n\n\"Ọ na-agwọ ndị obi tiwara etiwa, ma na-ekechikwa ọnya ha\" (Abụ Ọma 147:3). Ọgwụgwọ ahụ bụ ezi ihe. Ikechi ahụ bụ ezi ihe. Ma ọ na-amalite site n'ikweta na ọnya ahụ dị. Chineke anaghị agwọ ihe a na-ewetaghị n'ihu ya. Wetara mwute gị — ya niile, n'ụdị ọ bụla o were.",
      "repentance": "Wetara Chineke mwute gị. Ọ bụghị ụdị a chịkọtara — nke ezi n'ezi. Ọ naghị agwa gị ka ị meere udo ị na-enweghị mmetụta ya. Ọ na-agwa gị bịa na ihe ị nwere n'ezie.",
      "prayer": "Onyenwe anyị, ana m eweta mwute m n'ihu Gị taa — ibu ya niile, na-enweghị ibelata ya. Ị berela ákwá n'ili Lazarọs ọbụlagodi mgbe ị maara na mbilite n'ọnwụ na-abịa. Kwaa ákwá m taa. Kechie ọnya m. Gwọọ ihe gbajiri agbaji. Ekwenyere m na ị maara ụzọ isi gafere ọchịchịrị a. Amen."
    },
    "117": {
      "hook": "Ị na-enwe mmetụta owu. Ị nọghị naanị gị.",
      "body": "\"Agaghị m ahapụ gị, agakwaghị m agbakụ gị azụ\" (Ndị Hibru 13:5). Ihe eji ewu okwu Grik ahụ jiri asatọ ise mee ka ọ dị ike: agaghị m, ọ dịghị mgbe, n'okpuru ọnọdụ ọ bụla, n'okpuru ihe ọ bụla, hapụ gị. Ekwuru nkwa a n'ime egwu nke iche ihe amaghị ama enweghị nkwado — ọ dịghịkwa emebi.\n\nJizọs gwara ndị na-eso ụzọ ya: \"Ma le, mụ onwe m na-anọnyere unu ụbọchị niile, ruo na ngwụcha ụwa\" (Matiu 28:20). Mgbe niile. Ọ bụghị site n'ilegharị anya n'azụ, ọ bụghị site n'ụkpụrụ, ọ bụghị naanị mgbe ị na-enwe mmetụta ya. Mgbe niile. Ọnụnọ Jizọs adabereghị n'echiche gị banyere ya. Ọ bụghị mmetụta uche. Ọ bụ eziokwu.\n\nDevid dere Abụ Ọma 23 — nwoke nọworo naanị ya n'ezie: n'ọzara, n'ime ọgba, na-agbapụ n'aka nwa ya nwoke nke na-achọ igbu ya. O dekwara: \"Ọbụlagodi mgbe m na-aga n'ime ndagwurugwu nke onyinyo nke ọnwụ, agaghị m atụ egwu ihe ọjọọ ọ bụla, n'ihi na Gị onwe gị nọnyeere m.\" Ọ bụghị \"Ana m enwe mmetụta ọnụnọ Gị\" — Ị nọnyeere m. Mmekọrịta Chineke anaghị achọ mmetụta uche gị iji gosipụta ya.",
      "repentance": "Ọnụnọ Chineke adabereghị n'echiche gị. Kwupụta ya taa dịka eziokwu, ọbụlagodi ma ọ bụrụ na ị enweghị ike inwe mmetụta ya: Ị nọnyeere m. Kwe ka eziokwu ahụ malite igafe mmetụta uche ahụ.",
      "prayer": "Onyenwe anyị, ana m enwe mmetụta owu. Ma ana m ahọrọ ikwere ihe I kwuru karịa ihe m na-enwe mmetụta ya. I kwuru: Agaghị m ahapụ gị. Ana m ewere nkwa ahụ baa n'ime owu taa. Ị nọnyeere m — ọbụlagodi ebe a, ọbụlagodi ugbu a, ọbụlagodi n'ime ịmị. Anọghị m naanị m. Amen."
    },
    "118": {
      "hook": "Igbu oge abụghị ajụ. Kalịnda Chineke dị iche na nke gị.",
      "body": "Hana kpere ekpere maka nwa nwoke afọ ka afọ (1 Samuel 1). O jere n'ụlọ nsọ kpee ekpere n'ike nke ukwuu ruo na Ịlaị bụ onye nchụàjà chere na ọ ṅụbigara mmanya oke ọnụ. Ọ bere ákwá. Ọ nọgidere na-ekpe ekpere. Ma \"Onyenwe anyị chetara ya\" (1 Samuel 1:19) — ọ bụghị n'ihi na o mesịrị kpee ekpere ziri ezi, kama n'ihi na oge eruola. Ichere abụghị igbu oge. Ọ bụ nkwadebe — maka nwa ga-aghọ otu n'ime ndị amụma kachasị ukwuu n'akụkọ ihe mere eme Izrel.\n\nA kọrọ ilu nke nwaanyị di ya nwụrụ nke na-anọgide (Luk 18:1-8) kpọmkwem \"igosi ha na ọ dị mkpa ka ha na-ekpe ekpere mgbe niile ghara ịda mba.\" A gwaghị nwaanyị ahụ ka ọ kwụsị ịrịọ. A gwara ya na ịrịọ n'onwe ya bụ ọsịsa ziri ezi nye igbu oge ahụ. Ọ bụghị nnabata dị nwayọọ. Okwukwe dị active, na-anọgide, ọbụlagodi isiike.\n\nHabakuk 2:3: \"N'ihi na ọhụụ ahụ ka na-eche oge a kara aka; ọ na-agba ọsọ gaa n'ọgwụgwụ, ọ gakwaghị agha ụgha: ọ bụrụ na ọ na-egbu oge, chere ya; n'ihi na ọ ga-abịa n'eziokwu, ọ gaghị egbu oge.\" Oge akara aka ahụ bụ eziokwu. \"Igbu oge\" ahụ abụghị ihe akaebe nke enweghị mmasị. Ọ bụ oghere dị n'etiti nkwa na mmezu ya — a chọrọ ka oghere ahụ jupụta n'okwukwe.",
      "repentance": "Atụgharịla ekpere a na-azaghị dịka ekpere a na-anụghị. Nọgide na-arịọ. Nọgide na-akụ aka n'ọnụ ụzọ. Oge akara aka ahụ bụ eziokwu.",
      "prayer": "Onyenwe anyị, anọwo m na-ekpe ekpere na-ahụtụbeghị m azịza ya. Ana m ahọrọ taa ka m ghara ịda mba. Ana m ewetaghachi arịrịọ m ọzọ — site n'ịnọgide na-eme ya, site n'ikwesị ntụkwasị obi. Ekwenyere m na igbu oge abụghị ajụ. Ekwenyere m na oge akara aka bụ eziokwu. Ana m anọgide na-arịọ. Amen."
    },
    "119": {
      "hook": "Ọsọ ị na-agba bụ nke gị. Kwụsị ile ihe eri onye ọzọ.",
      "body": "Pita, onye Jizọs nyefere ọrụ ọhụrụ, lere onye na-eso ụzọ ya ọzọ anya ma jụọ: \"Onyenwe m, gịnị ka a ga-eme onye a?\" (Jọn 21:21). Ọ ka natara oku ya kpọmkwem — \"Zụọ atụrụ m\" — o lekwasịrị anya ozugbo n'akụkụ na oku onye ọzọ. Azịza Jizọs pụtara ìhè: \"Gịnị ka ọ bụ nye gị? Soro m aga\" (Jọn 21:22). Gịnị ka ọ bụ nye gị. Ihe eri gị. Soro m aga.\n\nItụnyere onwe onye na onye ọzọ bụ onye ohi. Ọ na-ezuru ọṅụ nke ihe Chineke na-eme na ndụ gị site n'ime ka ị tụle ya megide ihe Ọ na-eme na ndụ onye ọzọ. Ọ bụkwa mmejọ n'ụdị ihe — ịtụnyere isi nke mbụ gị na isi nke iri anọ nke onye ọzọ, mgbagwoju anya nzuzo gị na mmezu ihu ọha nke onye ọzọ. Pọl dọrọ aka na ntị: \"Mgbe ha jiri onwe ha tụnyere onwe ha, ma jiri onwe ha tụnyere onwe ha, ha amaghị ihe\" (2 Ndị Kọrint 10:12).\n\nA nyeghị gị ọsọ nke onye ọzọ. A nyere gị nke gị — jiri onyinye gị kpọmkwem, ọrụ gị kpọmkwem, oge gị kpọmkwem. \"Ka onye ọ bụla nwaa ọrụ nke aka ya, mgbe ahụ ka ọ ga-enwe ihe ịnya isi maka onwe ya naanị, ọ bụghị maka onye ọzọ\" (Ndị Galeshia 6:4). Ikwesị ntụkwasị obi gị n'ime ihe eri gị bụ naanị ikwesị ntụkwasị obi na-agụ ọnụ.",
      "repentance": "Kwụsị ile anya n'akụkụ. Jizọs kwuru: gịnị ka ọ bụ nye gị? Soro m aga. Weghachi uche gị n'ihe eri gị, oku gị, ikwesị ntụkwasị obi gị.",
      "prayer": "Onyenwe anyị, ana m ekwupụta na anọwo m na-ele anya n'ihe eri ndị ọzọ ma na-efunahụ nke m. Ana m anụ okwu Gị: gịnị ka ọ bụ nye gị? Soro m aga. Ana m eweghachi anya m Gị taa. Ana m agba ọsọ m. Ana m emezu oku m. Ana m akwụsị ịtụnyere onwe m na ibido iso ụzọ. Amen."
    },
    "120": {
      "hook": "E chepụtaghị ule iji bibie okwukwe gị. E chepụtara ya iji gosipụta ya.",
      "body": "Jemis 1:2-4: \"Ụmụnna m, gụọ ya dịka ihe ọṅụ nke ukwuu mgbe ọ bụla unu dabara n'ọnwụnwa dị iche iche; ebe unu maara na ule nke okwukwe unu na-eweta ntachi obi. Ka ntachi obi rụzuo ọrụ ya kpamkpam, ka unu wee zuo oke, ghọọkwa ndị zuru ezu, na-adịghị achọ ihe ọ bụla.\" Ọṅụ dị ukwuu — ntụziaka n'ezie na-esi na ịmara ihe ule ahụ na-emepụta.\n\nUle nke okwukwe gị abụghị ihe akaebe na Chineke ahapụla gị. Ọ bụ ihe akaebe na ị nọ n'ụlọ nnụcha. Nkwupụta Job si n'ikpo ntụ: \"Mgbe ọ ṅwapụtachara m, aga m apụta dị ka ọlaedo\" (Job 23:10). Onye na-anụcha adịghị eme ka mkpọmkpọ ígwè kpoo ọkụ iji bibie ya. Ọ na-eme ka ọ kpoo ọkụ iji dee ya ọcha. Usoro ahụ na-egbu mgbu. Ngwaahịa ahụ dị oke ọnụ ahịa.\n\n1 Pita 1:6-7: \"Nke unu na-aṅụrị ọṅụ nke ukwuu na ya, ọ bụ ezie na ugbu a, ọ bụrụ na ọ dị mkpa, e mewo ka unu wute obi n'ọnwụnwa dị iche iche: ka nnwale nke okwukwe unu, nke dị oke ọnụ ahịa karịa ọlaedo na-ala n'iyi, ọ bụ ezie na a na-anwale ya n'ọkụ, wee dịrị na otuto na nsọpụrụ na ebube mgbe a ga-akpughe Jizọs Kraịst.\" Nkwupụta ezi ihe eji ele anya — okwukwe a nwaliri ma jide ike — dị oke ọnụ ahịa karịa ọlaedo.",
      "repentance": "Lere anya na ule ị nọ na ya. Jụọ ihe Chineke na-emepụta site na ya. Kwe ka ntachi obi rụzuo ọrụ ya. Ọkụ ahụ ebughị n'obi ibibi gị. Eburu ya n'obi igosipụta ihe bụ eziokwu.",
      "prayer": "Onyenwe anyị, ana m ahọrọ ile ule a anya site na anya Gị. Ama m na ule nke okwukwe m na-emepụta ntachi obi. Kwe ka ntachi obi rụzuo ọrụ ya. Kwe ka m pụta dị ka ọlaedo — ihe e nwaliri, dị ọcha, na dị oke ọnụ ahịa karịa mgbe m batara n'ọkụ. Amen."
    }
  },
  "ha": {
    "116": {
      "hook": "Yesu ya yi kuka. Allah ba ya neman ka yi kamar-kamar.",
      "body": "Yohanna 11:35 shi ne mafi guntun aya a cikin Littafi Mai Tsarki: \"Yesu ya yi kuka.\" Yana tsaye a bakin kabarin Li'azaru — mutumin da yake shirin tayar da shi daga matattu. Ya san ƙarshen labarin. Duk da haka ya yi kuka. Ba a matsayin wasan kwaikwayo ba. A matsayin baƙin ciki na gaskiya kan asara ta gaskiya — da tausayi na gaskiya ga baƙin cikin waɗanda ke kewaye da shi.\n\nZabura sune tsarin Littafi Mai Tsarki na baƙin ciki na gaskiya. Zabura ta 88 ta ƙare ba tare da warware matsala ba, ba tare da juyawa zuwa yabo ba, ba tare da ƙarshe mai daɗi ba — kawai \"duhu ne abokina na kusa\" (Zabura 88:18). Kuma wannan zabura tana cikin Littafi Mai Tsarki. Allah ya haɗa baƙin cikin da ba a warware ba tare da bautar nasara. Domin ba ya tsoron baƙin ciki, kuma ba ya buƙatar warwarewa kafin ya saurare ka.\n\n\"Yana warkar da masu karyayyun zuciya, yana kuma ɗaura raunukansu\" (Zabura 147:3). Warkarwa gaskiya ce. Ɗaurin gaskiya ne. Amma yana farawa da yarda da rauni. Allah ba ya warkar da abin da ba a kawo masa ba. Kawo baƙin cikinka — dukkansa, cikin kowace siffa da yake ɗauka.",
      "repentance": "Kawo baƙin cikinka ga Allah. Ba tsaftataccen sigar ba — na gaskiya. Ba ya neman ka yi kamar kana da salama wanda ba ka ji ba. Yana neman ka zo da abin da kake da shi hakika.",
      "prayer": "Ubangiji, na kawo maka baƙin cikina yau — nauyinsa gaba ɗaya, ba tare da rage shi ba. Ka yi kuka a kabarin Li'azaru koda kana sane cewa tashin matattu yana zuwa. Yi kuka tare da ni cikin wannan. Ɗaura raunina. Ka warkar da abin da ya karye. Na dogara ka san hanya ta cikin wannan duhu. Amin."
    },
    "117": {
      "hook": "Kana jin kaɗaici. Ba ka kaɗai ba.",
      "body": "\"Ba zan taɓa rabuwa da kai ba, ba kuwa zan taɓa yashe ka ba\" (Ibraniyawa 13:5). Tsarin Girkanci yana amfani da mummunan magana biyar don ƙarfafawa: ba zan taɓa, ba kwata-kwata, ba a ƙarƙashin kowane yanayi, ba a ƙarƙashin kowane sharadi, in bar ka. An faɗi wannan alkawari cikin tsoron fuskantar wanda ba a sani ba babu tallafi — kuma bai ƙare ba.\n\nYesu ya gaya wa almajiransa: \"Kuma lalle ina tare da ku kullum, har ƙarshen zamani\" (Matiyu 28:20). Kullum. Ba a baya ba, ba a ka'ida ba, ba lokacin da kake ji ba. Kullum. Kasancewar Yesu ba ya dogara akan yadda kake gani. Ba jin dadi ba ne. Gaskiya ne.\n\nDauda ne ya rubuta Zabura ta 23 — mutumin da ya kasance kaɗai hakika: cikin jeji, cikin kogo, yana gudu daga ɗa wanda yake ƙoƙarin kashe shi. Kuma ya rubuta: \"Ko da yake ina tafiya cikin kwarin inuwar mutuwa, ba zan ji tsoron wani mugun abu ba, gama kai kana tare da ni.\" Ba \"Ina jin kasancewarka ba\" — kana tare da ni. Zumuncin Allah ba ya buƙatar jin daɗinka don tabbatar da shi.",
      "repentance": "Kasancewar Allah ba ya dogara akan jin daɗinka. Ka bayyana shi yau a matsayin gaskiya, ko da ba ka iya jin shi ba: Kana tare da ni. Ka bar wannan gaskiya ta fara shiga jin dadi.",
      "prayer": "Ubangiji, ina jin kaɗaici. Amma na zaɓi in gaskata abin da ka faɗa maimakon abin da nake ji. Ka ce: Ba zan taɓa rabuwa da kai ba. Na ɗauki wannan alkawari zuwa cikin kaɗaici yau. Kana tare da ni — koda anan, koda yanzu, koda cikin shiru. Ba ni kaɗai ba. Amin."
    },
    "118": {
      "hook": "Jinkiri ba ƙi ba ne. Kalandar Allah ta bambanta da taka.",
      "body": "Hanna ta yi addu'a domin ɗa shekara bayan shekara (1 Sama'ila 1). Ta je haikali ta yi addu'a da himma sosai har Eli firist ya ɗauka ta bugu. Ta yi kuka. Ta ci gaba da yin addu'a. Kuma \"Ubangiji ya tuna da ita\" (1 Sama'ila 1:19) — ba don a ƙarshe ta yi addu'a daidai ba, sai don lokacin ya yi. Jira ba jinkiri ba ne. Shiri ne — domin ɗa wanda zai zama ɗaya daga cikin manyan annabawa a tarihin Isra'ila.\n\nAn faɗi misalin gwauruwa mai nacewa (Luka 18:1-8) musamman \"don nuna musu cewa ya kamata su yi addu'a kullum, kada su karaya.\" Ba a gaya wa gwauruwar ta daina rokawa ba. An gaya mata cewa rokawar da kanta ita ce amsa daidai ga jinkirin. Ba mika wuya na shiru ba. Bangaskiya mai aiki, mai nacewa, har ma taurin kai.\n\nHabakuk 2:3: \"Domin wahayin nan har yanzu domin ƙayyadadden lokaci ne; yana magana game da ƙarshe, ba zai yi ƙarya ba: ko da ya jinkirta, ka jira shi; domin lalle zai zo, ba zai jinkirta ba.\" Ƙayyadadden lokaci gaskiya ne. \"Jinkirin\" ba shaida na rashin kula ba ne. Shi ne sarari tsakanin alkawari da cikawa — kuma an nufi sararin nan ya cika da bangaskiya.",
      "repentance": "Kada ka fassara addu'ar da ba a amsa ba a matsayin addu'ar da ba a ji ba. Ka ci gaba da rokawa. Ka ci gaba da ƙwanƙwasawa. Ƙayyadadden lokaci gaskiya ne.",
      "prayer": "Ubangiji, na kasance ina addu'a kuma ban ga amsa ba tukuna. Na zaɓi yau kada in daina. Na kawo buƙatata sake — da nacewa, da aminci. Na dogara jinkirin ba ƙi ba ne. Na dogara ƙayyadadden lokaci gaskiya ne. Na ci gaba da rokawa. Amin."
    },
    "119": {
      "hook": "Tseren da kake ciki naka ne. Ka daina kallon hanyar wani.",
      "body": "Bitrus, wanda Yesu ya sabon ba da izini, ya kalli wani almajiri ya kuma tambaya: \"Ubangiji, me game da wannan?\" (Yohanna 21:21). Ya karɓi kiransa na musamman kawai — \"Ka ciyar da tumakina\" — sai nan take ya kalli gefe zuwa kiran wani. Amsar Yesu ta kasance kai tsaye: \"Me ya shafe ka? Ka bi ni\" (Yohanna 21:22). Me ya shafe ka. Hanyarka. Ka bi ni.\n\nKwatanci ɓarawo ne. Yana sata farin ciki daga abin da Allah yake yi a rayuwarka ta wurin sa ka aunata da abin da Yake yi a rayuwar wani. Har ila yau kuskuren rukuni ne — kwatanta babi na ɗaya naka da babi na arba'in na wani, gwagwarmayarka ta sirri da nasarorin jama'a na wani. Bulus ya yi gargaɗi: \"Domin sa'ad da suke aunan kansu da kansu, kuma suna kwatanta kansu da kansu, ba su da hikima\" (2 Korintiyawa 10:12).\n\nAn ba ka ba tseren wani ba. An ba ka naka — da baiwarka ta musamman, ayyukanka na musamman, lokacinka na musamman. \"Amma bari kowa ya gwada aikin kansa, sa'an nan zai sami dalilin taƙama a cikin kansa kaɗai, ba dangane da wani ba\" (Galatiyawa 6:4). Aminci naka a cikin hanyarka shi ne kaɗai amincin da yake ƙidaya.",
      "repentance": "Ka daina kallon gefe. Yesu ya ce: me ya shafe ka? Ka bi ni. Ka mayar da hankalinka zuwa hanyarka, kiranka, amincinka.",
      "prayer": "Ubangiji, na furta cewa na kasance ina kallon hanyoyin wasu ina kuma rasa ganin nawa. Na ji maganarka: me ya shafe ka? Ka bi ni. Na mayar da idanuna gareka yau. Ina gudun tseren nawa. Ina cika kiran nawa. Na daina kwatantawa na fara bi. Amin."
    },
    "120": {
      "hook": "Ba a tsara gwaji don halaka bangaskiyarka ba. An tsara shi don tabbatar da ita.",
      "body": "Yakubu 1:2-4: \"'Yan'uwana, ku ɗauke shi duk farin ciki, sa'ad da kuka fāɗa cikin jarrabobi dabam-dabam; da sanin cewa gwajin bangaskiyarku na haifar da haƙuri. Bari haƙuri ya kammala aikinsa, don ku zama cikakku da kamiltattu, ba ku rasa kome ba.\" Cikakken farin ciki — daidaitaccen fuskanta na gaskiya wanda ke fitowa daga sanin abin da gwajin yake haifarwa.\n\nGwajin bangaskiyarka ba shaida ba ne cewa Allah ya bar ka. Shaida ce cewa kana cikin masana'anta. Sanarwar Ayuba daga tudun toka: \"Bayan ya gwada ni, zan fito kamar zinariya\" (Ayuba 23:10). Mai tsarkakewa ba ya dumama ƙarfe don halaka shi. Yana dumama shi don tsarkake shi. Tsari yana da zafi. Amma sakamakon yana da daraja.\n\n1 Bitrus 1:6-7: \"Wanda a ciki kuke murna sosai, ko da yake yanzu na ɗan lokaci, in ya zama dole, an ɓata muku rai da jarrabobi dabam-dabam: don a tabbatar da bangaskiyarku, wadda ta fi zinariya mai lalacewa daraja, ko da yake ana gwada ta da wuta, a same ta domin yabo da girma da daraja a bayyanuwar Yesu Kristi.\" Tabbatacciyar gaskiya — bangaskiya wadda aka gwada aka kuma riƙe ta — ta fi zinariya daraja.",
      "repentance": "Ka duba gwajin da kake ciki. Ka tambaya abin da Allah yake haifarwa a cikinsa. Ka bari haƙuri ya kammala aikinsa. Wuta ba a nufe don ta halaka ka ba. An nufe don ta tabbatar da abin da yake gaskiya.",
      "prayer": "Ubangiji, na zaɓi in duba wannan gwaji ta wurin ganin ka. Na sani gwajin bangaskiyata yana haifar da haƙuri. Bari haƙuri ya kammala aikinsa. Ka bar ni in fito kamar zinariya — tabbatacce, tsarkakakke, kuma mai daraja fiye da lokacin da na shiga wuta. Amin."
    }
  },
  "pcm": {
    "116": {
      "hook": "Jesus cry. God no dey ask you make you form.",
      "body": "John 11:35 na di shortest verse for Bible: \"Jesus weep.\" E dey stand outside Lazarus tomb — man wey e dey about to raise from dead. E know how di story go end. But e still cry. E no be performance. Na real grief for real loss — and real compassion for di grief of those wey dey around Am.\n\nPsalms na di Bible pattern for honest grief. Psalm 88 end without resolution, without turn to praise, without happy ending — just \"darkness na my closest friend\" (Psalm 88:18). And dat psalm dey inside Bible. God include di grief wey never resolve join di victorious worship. Because E no dey fear grief, E no too dey demand resolution before E go hear you.\n\n\"E dey heal di brokenhearted and bind up their wounds\" (Psalm 147:3). Di healing na real. Di binding na real. But e dey start with acknowledging di wound. God no dey heal wetin nobody bring come to Am. Bring your grief — everything, for whatever form e take.",
      "repentance": "Bring your grief come to God. No bring di managed version — bring di real one. E no dey ask you to perform peace wey you no dey feel. E dey ask you make you come with wetin you actually get.",
      "prayer": "Lord, I dey bring my grief come to You today — di full weight of am, I no go minimize am. You weep for Lazarus tomb even as You know say resurrection dey come. Weep with me for dis one. Bind my wound. Heal wetin don break. I trust say You know di way through dis darkness. Amen."
    },
    "117": {
      "hook": "You dey feel alone. You no dey alone.",
      "body": "\"I no go ever leave you; I no go ever forsake you\" (Hebrews 13:5). Di Greek construction use five negatives for emphasis: I no go, never, under no circumstance, under no condition, leave you. Dem talk dis promise inside fear of facing unknown without support — and e no expire.\n\nJesus tell im disciples: \"And surely I dey with una always, to di very end of di age\" (Matthew 28:20). Always. E no be for looking back, e no be for principle, e no be only when you feel am. Always. Di presence of Jesus no depend on how you perceive am. E no be feeling. Na fact.\n\nDavid na im write Psalm 23 — man wey don dey alone for real: for wilderness, for caves, dey run from son wey dey try kill am. E write: \"Even as I dey waka through di darkest valley, I no go fear evil, because You dey with me.\" E no talk \"I feel Your presence\" — na You dey with me. Di companionship of God no need your feelings to authenticate am.",
      "repentance": "God presence no depend on your feelings. Declare am today as fact, even if you no fit feel am: You dey with me. Make dat fact begin push through di feeling.",
      "prayer": "Lord, I dey feel alone. But I choose to believe wetin You talk pass wetin I dey feel. You talk: I no go ever leave you. I dey carry dat promise enter di loneliness today. You dey with me — even here, even now, even for di silence. I no dey alone. Amen."
    },
    "118": {
      "hook": "Delay no be denial. God calendar different from yours.",
      "body": "Hannah pray for son year after year (1 Samuel 1). E go temple e pray with strong passion until Eli di priest think say she don drunk. E cry. E continue to pray. And \"di LORD remember her\" (1 Samuel 1:19) — no be because she finally pray di correct prayer, but because di time don reach. Di wait no be delay. Na preparation — for child wey go become one of di greatest prophets for Israel history.\n\nDi parable of di persistent widow (Luke 18:1-8) dem tell am specifically \"to show dem say dem suppose always pray, no give up.\" Dem no tell di widow make she stop to dey ask. Dem tell her say di asking itself na di correct response to di delay. E no be passive resignation. Active, persistent, even stubborn faith.\n\nHabakkuk 2:3: \"Because di revelation dey wait for appointed time; e dey talk about di end and e no go prove false. Even if e delay, wait for am; e go surely come, e no go delay.\" Di appointed time na real. Di \"delaying\" no be evidence of indifference. Na di space between di promise and di fulfillment — and dat space suppose dey filled with faith.",
      "repentance": "No interpret prayer wey never answer as prayer wey nobody hear. Continue to dey ask. Continue to dey knock. Di appointed time na real.",
      "prayer": "Lord, I don dey pray and I never see di answer yet. I choose today make I no give up. I dey bring my request again — persistently, faithfully. I trust say di delay no be denial. I trust say di appointed time na real. I dey continue to ask. Amen."
    },
    "119": {
      "hook": "Di race wey you dey inside na yours. Stop to dey watch person lane.",
      "body": "Peter, wey Jesus just commission, look another disciple ask: \"Lord, wetin about am?\" (John 21:21). E just receive im specific call — \"Feed my sheep\" — e come immediately look sideways to another person calling. Jesus response na direct: \"Wetin be dat to you? You must follow me\" (John 21:22). Wetin be dat to you. Your lane. Follow me.\n\nComparison na thief. E dey steal joy from wetin God dey do for your life by making you measure am against wetin E dey do for another person life. E also be category error — to compare your chapter 1 with another person chapter 40, your private struggles with another person public achievements. Paul warn say: \"When dem measure demself by demself, and dem compare demself with demself, dem no wise\" (2 Corinthians 10:12).\n\nDem no give you another person race. Dem give you yours — with your specific gifts, your specific assignment, your specific timing. \"Make every person test im own actions. Then dem fit take pride for demself alone, without comparing demself to another person\" (Galatians 6:4). Your faithfulness for your lane na di only faithfulness wey count.",
      "repentance": "Stop to dey look sideways. Jesus talk say: wetin be dat to you? You must follow me. Return your attention to your lane, your calling, your faithfulness.",
      "prayer": "Lord, I confess say I don dey watch other people lane and I dey lose sight of mine. I hear Your word: wetin be dat to you? You must follow me. I return my eyes come to You today. I dey run my race. I dey fulfil my calling. I stop to compare, I start to follow. Amen."
    },
    "120": {
      "hook": "Dem no design testing to destroy your faith. Dem design am to prove am.",
      "body": "James 1:2-4: \"Consider am pure joy, my brothers and sisters, anytime wey una face different kind trials, because una know say di testing of una faith dey produce perseverance. Make perseverance finish im work so that una fit mature and complete, no dey lack anything.\" Pure joy — real orientation wey dey come from knowing wetin di testing dey produce.\n\nDi testing of your faith no be evidence say God don abandon you. Na evidence say you dey inside di refinery. Job declaration from di ash heap: \"When E don test me, I go come out as gold\" (Job 23:10). Di Refiner no dey heat di metal to destroy am. E dey heat am to purify am. Di process dey pain. Di product get value.\n\n1 Peter 1:6-7: \"For dis one una dey rejoice well well, even though now for small time una fit don suffer grief for different kind trials. Dis ones don come so dat di proven genuineness of una faith — wey get more value pass gold, wey dey perish even though dem refine am with fire — fit result for praise, glory and honour when Jesus Christ go reveal Imself.\" Di proven genuineness — faith wey dem don test and wey hold — get more value pass gold.",
      "repentance": "Look di trial wey you dey inside. Ask wetin God dey produce for inside am. Make perseverance finish im work. Di fire no mean to destroy you. E mean to prove wetin real.",
      "prayer": "Lord, I choose to see dis trial through Your own lens. I know say di testing of my faith dey produce perseverance. Make perseverance finish im work. Make I come out as gold — proven, purified, and get more value pass how I be before I enter di fire. Amen."
    }
  }
};

if (typeof mergeTractsI18n === 'function') mergeTractsI18n(TRACTS_I18N_STRUGGLE_P2);