// ==========================================================
// GOSPEL TRACTS i18n — STRUGGLE category, Part 1 of 3 (tracts 111-115)
// Translated into all 8 languages. Merge with base GOSPEL_TRACTS data
// (id, category, color, title, verses stay the same across languages —
// only hook/body/repentance/prayer prose changes per language).
// ==========================================================
const TRACTS_I18N_STRUGGLE_P1 = {
  "en": {
    "111": {
      "hook": "The temptation feels unique to you. The way out is promised to everyone.",
      "body": "1 Corinthians 10:13: \"No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can endure it.\" Three guarantees: the temptation is not unique, it is not beyond bearing, and there is always a way out.\n\nThe first guarantee addresses the isolation that temptation produces. You feel as though no one else struggles with this. It is not true. \"No temptation has overtaken you except what is common to mankind.\" Your struggle is human, not monstrous. Others have faced it. Others have overcome it.\n\nThe third guarantee is perhaps the most practical: when you are tempted, God provides a way out. Always. Not sometimes — always. The way out may require movement — physical removal from the situation, a conversation you need to have. But it is always there. The question is not whether the exit exists. It is whether you will take it.",
      "repentance": "Look for the way out God has provided in your current temptation. It is there. It may require more courage to take it than to give in — but it is there.",
      "prayer": "Lord, I trust Your promise that there is always a way out. I stop looking at the temptation and I start looking for the exit You have provided. Give me the courage to take it. I choose the way out over the way down. Amen."
    },
    "112": {
      "hook": "You have tried to stop. He does not ask you to stop alone.",
      "body": "The person in Romans 7 — \"I do not do what I want to do, but the very thing I hate\" (Romans 7:15) — is the most honest description of addiction in the ancient world. Rational, aware, wanting change, unable to produce it. Not a person who does not care. A person for whom caring is not enough.\n\nPaul's answer is in Romans 8: \"Therefore, there is now no condemnation for those who are in Christ Jesus, because through Christ Jesus the law of the Spirit who gives life has set you free from the law of sin and death\" (Romans 8:1-2). Not a better version of your willpower. A different law entirely — the supernatural empowerment of the Holy Spirit — that is stronger than the law pulling you toward destruction.\n\nGalatians 5:1: \"It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.\" The freedom exists. It was purchased at the cross. The Spirit is available to produce it. The work of freedom is not done by holding tighter — it is done by surrendering more completely to the One who is already stronger than what holds you.",
      "repentance": "Bring the addiction honestly to God. Not the cleaned-up version — the real one. Receive the help He offers — not as a supplement to your effort, but as a power entirely beyond your effort.",
      "prayer": "Lord Jesus, I bring this addiction to You — all of it, without minimizing. I have tried to stop and I cannot do it alone. I receive what You offer — not better willpower, but the Spirit who gives life. Set me free. I surrender more completely to You than to what has been holding me. Amen."
    },
    "113": {
      "hook": "Honest doubt brought to Jesus will find an honest answer.",
      "body": "John the Baptist — the man Jesus called \"the greatest born of women\" (Matthew 11:11) — sent a message from prison: \"Are you the one who is to come, or should we expect someone else?\" (Luke 7:19). The prophet who had baptised Jesus, who had seen the Spirit descend like a dove — was asking whether Jesus was really the Messiah. In the dark of a prison cell, doubt came to the greatest prophet.\n\nJesus did not condemn John's doubt. He answered it. He sent back evidence — the blind see, the lame walk, the deaf hear, the dead are raised — and He did not require John to have certainty before asking the question. The question was met with evidence, not rejection.\n\nThomas doubted the resurrection until he touched the wounds (John 20:27-28). Jesus appeared to Thomas specifically and gave him exactly what he needed. He did not exclude Thomas from the disciples for the doubt. He appeared to the doubter. God is not frightened by honest doubt. He meets it.",
      "repentance": "Bring your doubt to Jesus, not away from Him. He can handle your questions. He answered John from prison. He appeared to Thomas. He will meet you in your uncertainty.",
      "prayer": "Lord, I have doubts. I am afraid to say that, but I believe You already know. I bring them to You — not away from You. Meet me in my uncertainty the way You met Thomas. I believe; help my unbelief. Amen."
    },
    "114": {
      "hook": "The war is not primarily external. It is fought between your ears.",
      "body": "2 Corinthians 10:4-5: \"The weapons we fight with are not the weapons of the world. On the contrary, they have divine power to demolish strongholds. We demolish arguments and every pretension that sets itself up against the knowledge of God, and we take captive every thought to make it obedient to Christ.\" Strongholds. Arguments. Pretensions. Every thought. The spiritual battle is a battle of ideas, narratives, and the stories you tell yourself.\n\nA stronghold in the mind is a pattern of thinking that has become so entrenched it feels like truth. \"God doesn't love me.\" \"I will never change.\" \"This is just how I am.\" \"Nothing ever works out for me.\" These are not observations — they are strongholds. And there is divine power available against them.\n\nRomans 12:2: \"Do not conform to the pattern of this world, but be transformed by the renewing of your mind.\" The transformation begins in the mind. The renewing is not a positive thinking exercise — it is the systematic replacement of false narratives with the truth of God's Word. Every thought that contradicts what God says about you — that thought is taken captive.",
      "repentance": "Identify the strongholds — the patterns of thinking that have been running your life. Take them captive. Put them against the truth of God's Word. Begin the renewing of your mind today.",
      "prayer": "Lord, I identify the strongholds in my mind today. I take them captive in the name of Jesus. I replace them with what You say. I begin the renewing of my mind — not with positive thinking, but with the truth of Your Word. Transform me. Amen."
    },
    "115": {
      "hook": "Elijah asked God to end his life. God sent an angel to feed him instead.",
      "body": "1 Kings 19 is the most honest account of spiritual depression in Scripture. Elijah had just called fire from heaven on Mount Carmel. He had stood against four hundred and fifty prophets. And then: \"He came to a broom bush, sat down under it and prayed that he might die. 'I have had enough, LORD,' he said. 'Take my life'\" (1 Kings 19:4). From the greatest spiritual high to the depths of suicidal despair in a matter of days.\n\nGod's response to Elijah's depression is extraordinary in its practicality: \"An angel touched him and said, 'Get up and eat.'\" Food and rest — before the theological conversation. Then food and rest again. Then \"the journey is too great for you.\" God met the physical reality before the spiritual. He did not rebuke Elijah for his despair. He fed it.\n\nThen the still small voice — the gentle, quiet word — in the cave at Horeb (1 Kings 19:12). Not the earthquake, not the fire, not the drama. The gentle voice of God speaking to an exhausted prophet. God met Elijah where he was — not where he should have been — and brought him back.",
      "repentance": "If you are in the place Elijah was, God is not far from you. He does not rebuke the exhausted. He feeds them. Come to Him in your weariness and receive His care.",
      "prayer": "Lord, I have had enough. I am like Elijah under the tree. I am not performing strength I do not have. I come to You in the exhaustion. Feed me. Let me rest. And when I am ready — speak in the still small voice. I will listen. Amen."
    }
  },
  "fr": {
    "111": {
      "hook": "La tentation te semble unique. L'issue est promise à tous.",
      "body": "1 Corinthiens 10.13 : « Aucune tentation ne vous est survenue qui n'ait été humaine, et Dieu, qui est fidèle, ne permettra pas que vous soyez tentés au-delà de vos forces ; mais avec la tentation il préparera aussi le moyen d'en sortir, afin que vous puissiez la supporter. » Trois garanties : la tentation n'est pas unique, elle n'est pas au-delà de tes forces, et il y a toujours une issue.\n\nLa première garantie répond à l'isolement que produit la tentation. Tu as l'impression que personne d'autre ne lutte contre cela. Ce n'est pas vrai. « Aucune tentation ne vous est survenue qui n'ait été humaine. » Ta lutte est humaine, pas monstrueuse. D'autres l'ont affrontée. D'autres l'ont surmontée.\n\nLa troisième garantie est peut-être la plus pratique : quand tu es tenté, Dieu prépare une issue. Toujours. Pas parfois — toujours. L'issue peut exiger un mouvement — un éloignement physique de la situation, une conversation que tu dois avoir. Mais elle est toujours là. La question n'est pas de savoir si la sortie existe. C'est de savoir si tu la prendras.",
      "repentance": "Cherche l'issue que Dieu a préparée dans ta tentation actuelle. Elle est là. Elle peut exiger plus de courage à prendre qu'à céder — mais elle est là.",
      "prayer": "Seigneur, je fais confiance à Ta promesse qu'il y a toujours une issue. J'arrête de regarder la tentation et je commence à chercher la sortie que Tu as préparée. Donne-moi le courage de la prendre. Je choisis l'issue plutôt que la chute. Amen."
    },
    "112": {
      "hook": "Tu as essayé d'arrêter. Il ne te demande pas d'arrêter seul.",
      "body": "La personne de Romains 7 — « Je ne fais pas ce que je veux, mais je fais ce que je hais » (Romains 7.15) — est la description la plus honnête de la dépendance dans le monde antique. Rationnelle, consciente, voulant changer, incapable d'y parvenir. Pas une personne qui s'en fiche. Une personne pour qui se soucier ne suffit pas.\n\nLa réponse de Paul se trouve en Romains 8 : « Il n'y a donc maintenant aucune condamnation pour ceux qui sont en Jésus-Christ... car la loi de l'Esprit de vie en Jésus-Christ m'a affranchi de la loi du péché et de la mort » (Romains 8.1-2). Pas une meilleure version de ta volonté. Une loi entièrement différente — la puissance surnaturelle du Saint-Esprit — plus forte que la loi qui t'entraîne vers la destruction.\n\nGalates 5.1 : « C'est pour la liberté que Christ nous a affranchis. Demeurez donc fermes, et ne vous laissez pas mettre de nouveau sous le joug de la servitude. » La liberté existe. Elle a été achetée à la croix. L'Esprit est disponible pour la produire. L'œuvre de la liberté ne se fait pas en serrant plus fort — elle se fait en se rendant plus complètement à Celui qui est déjà plus fort que ce qui te retient.",
      "repentance": "Apporte ta dépendance honnêtement à Dieu. Pas la version arrangée — la vraie. Reçois l'aide qu'Il offre — non pas comme un complément à ton effort, mais comme une puissance entièrement au-delà de ton effort.",
      "prayer": "Seigneur Jésus, je T'apporte cette dépendance — toute entière, sans la minimiser. J'ai essayé d'arrêter et je n'y arrive pas seul. Je reçois ce que Tu offres — non pas une meilleure volonté, mais l'Esprit qui donne la vie. Libère-moi. Je me rends plus complètement à Toi qu'à ce qui me retenait. Amen."
    },
    "113": {
      "hook": "Un doute honnête apporté à Jésus trouvera une réponse honnête.",
      "body": "Jean-Baptiste — l'homme que Jésus a appelé « le plus grand né de femme » (Matthieu 11.11) — envoya un message depuis la prison : « Es-tu celui qui doit venir, ou devons-nous en attendre un autre ? » (Luc 7.19). Le prophète qui avait baptisé Jésus, qui avait vu l'Esprit descendre comme une colombe — se demandait si Jésus était vraiment le Messie. Dans l'obscurité d'une cellule de prison, le doute est venu au plus grand des prophètes.\n\nJésus n'a pas condamné le doute de Jean. Il y a répondu. Il a renvoyé des preuves — les aveugles voient, les boiteux marchent, les sourds entendent, les morts ressuscitent — et Il n'a pas exigé que Jean ait la certitude avant de poser la question. La question a été accueillie par des preuves, pas par le rejet.\n\nThomas doutait de la résurrection jusqu'à ce qu'il touche les blessures (Jean 20.27-28). Jésus est apparu spécifiquement à Thomas et lui a donné exactement ce dont il avait besoin. Il n'a pas exclu Thomas des disciples à cause du doute. Il est apparu au douteur. Dieu n'a pas peur du doute honnête. Il vient à sa rencontre.",
      "repentance": "Apporte ton doute à Jésus, ne T'éloigne pas de Lui. Il peut gérer tes questions. Il a répondu à Jean depuis la prison. Il est apparu à Thomas. Il te rencontrera dans ton incertitude.",
      "prayer": "Seigneur, j'ai des doutes. J'ai peur de le dire, mais je crois que Tu le sais déjà. Je Te les apporte — je ne m'éloigne pas de Toi. Rencontre-moi dans mon incertitude comme Tu as rencontré Thomas. Je crois ; viens au secours de mon incrédulité. Amen."
    },
    "114": {
      "hook": "La guerre n'est pas d'abord extérieure. Elle se livre entre tes oreilles.",
      "body": "2 Corinthiens 10.4-5 : « Les armes avec lesquelles nous combattons ne sont pas charnelles ; elles sont, au contraire, puissantes, par la vertu de Dieu, pour renverser des forteresses. Nous renversons les raisonnements et toute hauteur qui s'élève contre la connaissance de Dieu, et nous amenons toute pensée captive à l'obéissance de Christ. » Forteresses. Raisonnements. Hauteurs. Toute pensée. La bataille spirituelle est une bataille d'idées, de récits, et des histoires que tu te racontes.\n\nUne forteresse dans l'esprit est un schéma de pensée devenu si ancré qu'il semble être la vérité. « Dieu ne m'aime pas. » « Je ne changerai jamais. » « C'est juste comme ça que je suis. » « Rien ne marche jamais pour moi. » Ce ne sont pas des observations — ce sont des forteresses. Et il y a une puissance divine disponible contre elles.\n\nRomains 12.2 : « Ne vous conformez pas au siècle présent, mais soyez transformés par le renouvellement de l'intelligence. » La transformation commence dans l'esprit. Le renouvellement n'est pas un exercice de pensée positive — c'est le remplacement systématique des faux récits par la vérité de la Parole de Dieu. Toute pensée qui contredit ce que Dieu dit de toi — cette pensée est faite captive.",
      "repentance": "Identifie les forteresses — les schémas de pensée qui dirigent ta vie. Fais-les captives. Confronte-les à la vérité de la Parole de Dieu. Commence le renouvellement de ton esprit aujourd'hui.",
      "prayer": "Seigneur, j'identifie les forteresses dans mon esprit aujourd'hui. Je les fais captives au nom de Jésus. Je les remplace par ce que Tu dis. Je commence le renouvellement de mon esprit — non par la pensée positive, mais par la vérité de Ta Parole. Transforme-moi. Amen."
    },
    "115": {
      "hook": "Élie a demandé à Dieu de mettre fin à sa vie. Dieu a envoyé un ange pour le nourrir à la place.",
      "body": "1 Rois 19 est le récit le plus honnête de la dépression spirituelle dans les Écritures. Élie venait d'appeler le feu du ciel sur le mont Carmel. Il s'était tenu debout contre quatre cent cinquante prophètes. Et ensuite : « Il alla s'asseoir sous un genêt, et il demanda la mort en disant : C'est assez ! Maintenant, Éternel, prends mon âme » (1 Rois 19.4). Du plus grand sommet spirituel aux profondeurs du désespoir suicidaire en l'espace de quelques jours.\n\nLa réponse de Dieu à la dépression d'Élie est extraordinaire par son côté pratique : « Un ange le toucha, et lui dit : Lève-toi, mange. » Nourriture et repos — avant la conversation théologique. Puis encore nourriture et repos. Puis « le chemin est trop long pour toi. » Dieu a répondu à la réalité physique avant la réalité spirituelle. Il n'a pas réprimandé Élie pour son désespoir. Il l'a nourri.\n\nPuis la voix douce et légère — dans la grotte à Horeb (1 Rois 19.12). Pas le tremblement de terre, pas le feu, pas le drame. La voix douce de Dieu parlant à un prophète épuisé. Dieu a rencontré Élie là où il était — pas là où il aurait dû être — et l'a ramené.",
      "repentance": "Si tu es à l'endroit où était Élie, Dieu n'est pas loin de toi. Il ne réprimande pas les épuisés. Il les nourrit. Viens à Lui dans ta lassitude et reçois Son soin.",
      "prayer": "Seigneur, c'est assez. Je suis comme Élie sous l'arbre. Je ne fais pas semblant d'avoir une force que je n'ai pas. Je viens à Toi dans l'épuisement. Nourris-moi. Laisse-moi me reposer. Et quand je serai prêt — parle-moi dans la voix douce et légère. J'écouterai. Amen."
    }
  },
  "sw": {
    "111": {
      "hook": "Jaribu linahisi la kipekee kwako. Njia ya kutoka imeahidiwa kwa kila mtu.",
      "body": "1 Wakorintho 10:13: \"Hakuna jaribu lililowapata isipokuwa lililo kawaida kwa wanadamu; ila Mungu ni mwaminifu, ambaye hatawaacha mjaribiwe kupita mnavyoweza, lakini pamoja na lile jaribu atafanya na mlango wa kutokea, mpate kustahimili.\" Ahadi tatu: jaribu si la kipekee, si zaidi ya uwezo wako, na kuna njia ya kutoka daima.\n\nAhadi ya kwanza inashughulikia utengano ambao jaribu huzalisha. Unahisi kana kwamba hakuna mtu mwingine anayepambana na hili. Si kweli. \"Hakuna jaribu lililowapata isipokuwa lililo kawaida kwa wanadamu.\" Mapambano yako ni ya kibinadamu, si ya kishetani. Wengine wamekabiliana nalo. Wengine wameshinda.\n\nAhadi ya tatu labda ndiyo ya vitendo zaidi: unapojaribiwa, Mungu hutoa njia ya kutoka. Daima. Si mara nyingine — daima. Njia ya kutoka inaweza kuhitaji hatua — kujiondoa kimwili kutoka hali hiyo, mazungumzo unayohitaji kufanya. Lakini ipo daima. Swali si kama njia hiyo ipo. Ni kama utaichukua.",
      "repentance": "Tafuta njia ya kutoka ambayo Mungu ameiweka katika jaribu lako la sasa. Ipo. Inaweza kuhitaji ujasiri zaidi kuichukua kuliko kukubali — lakini ipo.",
      "prayer": "Bwana, ninaamini ahadi Yako kwamba daima kuna njia ya kutoka. Ninaacha kuangalia jaribu na kuanza kutafuta njia ya kutoka uliyoiweka. Nipe ujasiri wa kuichukua. Ninachagua njia ya kutoka badala ya njia ya kuanguka. Amina."
    },
    "112": {
      "hook": "Umejaribu kuacha. Yeye hakuombi uache peke yako.",
      "body": "Mtu katika Warumi 7 — \"Sifanyi lile nilipendalo, bali nifanyalo ni lile nilichukialo\" (Warumi 7:15) — ni maelezo ya uaminifu zaidi ya uraibu katika ulimwengu wa kale. Mwenye akili, anayejua, anayetaka mabadiliko, asiyeweza kuyazalisha. Si mtu asiyejali. Mtu ambaye kujali hakutoshi.\n\nJibu la Paulo liko katika Warumi 8: \"Basi sasa hakuna hukumu ya adhabu juu yao walio katika Kristo Yesu... kwa sababu sheria ya Roho wa uzima ule ulio katika Kristo Yesu imeniacha huru na sheria ya dhambi na mauti\" (Warumi 8:1-2). Si toleo bora la nia yako. Sheria tofauti kabisa — nguvu ya kimiujiza ya Roho Mtakatifu — yenye nguvu zaidi kuliko sheria inayokuvuta kwenye uharibifu.\n\nWagalatia 5:1: \"Kristo alituweka huru ili tuwe huru; basi simameni imara, wala msinaswe tena chini ya kongwa la utumwa.\" Uhuru upo. Ulinunuliwa msalabani. Roho anapatikana kuuzalisha. Kazi ya uhuru haifanywi kwa kushikilia kwa nguvu zaidi — inafanywa kwa kujisalimisha zaidi kwa Yule ambaye tayari ni mwenye nguvu zaidi kuliko kile kinachokushikilia.",
      "repentance": "Leta uraibu wako kwa Mungu kwa uaminifu. Si toleo lililosafishwa — la kweli. Pokea msaada anaotoa — si kama nyongeza ya juhudi yako, bali kama nguvu iliyo kabisa zaidi ya juhudi yako.",
      "prayer": "Bwana Yesu, ninakuletea uraibu huu — wote, bila kupunguza. Nimejaribu kuacha na siwezi peke yangu. Ninapokea unachotoa — si nia bora, bali Roho anayetoa uzima. Niweke huru. Ninajisalimisha zaidi Kwako kuliko kile kilichokuwa kikinishikilia. Amina."
    },
    "113": {
      "hook": "Shaka la uaminifu lililoletwa kwa Yesu litapata jibu la uaminifu.",
      "body": "Yohana Mbatizaji — mtu ambaye Yesu alimwita \"aliye mkuu kuliko wote waliozaliwa na wanawake\" (Mathayo 11:11) — alituma ujumbe kutoka gerezani: \"Wewe ndiye yeye ajaye, au tumtazamie mwingine?\" (Luka 7:19). Nabii aliyembatiza Yesu, aliyeona Roho akishuka kama njiwa — alikuwa akiuliza kama Yesu alikuwa kweli Masihi. Katika giza la chumba cha gereza, shaka lilimjia nabii mkuu zaidi.\n\nYesu hakulaumu shaka la Yohana. Alilijibu. Alirudisha ushahidi — vipofu wanaona, viwete wanatembea, viziwi wanasikia, wafu wanafufuliwa — na hakumhitaji Yohana kuwa na uhakika kabla ya kuuliza swali. Swali lilikutana na ushahidi, si kukataliwa.\n\nThomaso alishuku ufufuo mpaka aliposhika majeraha (Yohana 20:27-28). Yesu alimtokea Thomaso mahususi na kumpa hasa alichohitaji. Hakumtenga Thomaso na wanafunzi kwa sababu ya shaka. Alimtokea mwenye shaka. Mungu haogopi shaka la uaminifu. Anakutana nalo.",
      "repentance": "Leta shaka lako kwa Yesu, si mbali Naye. Anaweza kushughulikia maswali yako. Alimjibu Yohana kutoka gerezani. Alimtokea Thomaso. Atakutana nawe katika kutokuwa na uhakika kwako.",
      "prayer": "Bwana, nina shaka. Ninaogopa kusema hivyo, lakini ninaamini tayari unajua. Ninakuletea — si mbali Nawe. Kutana nami katika kutokuwa na uhakika kwangu kama ulivyokutana na Thomaso. Ninaamini; nisaidie kutoamini kwangu. Amina."
    },
    "114": {
      "hook": "Vita si hasa vya nje. Vinapiganwa kati ya masikio yako.",
      "body": "2 Wakorintho 10:4-5: \"Maana silaha za vita vyetu si za mwilini, bali zina uwezo katika Mungu hata kuangusha ngome; tukiangusha mawazo na kila kitu kilichoinuka, kijiinuacho juu ya elimu ya Mungu, na kuteka nyara kila fikira ipate kumtii Kristo.\" Ngome. Mawazo. Vitu vilivyoinuka. Kila fikira. Vita vya kiroho ni vita vya mawazo, hadithi, na simulizi unazojiambia.\n\nNgome katika akili ni mfumo wa mawazo uliojikita sana hata unahisi kama ukweli. \"Mungu hanipendi.\" \"Sitabadilika kamwe.\" \"Hivi ndivyo nilivyo tu.\" \"Hakuna kinachofanikiwa kwangu.\" Haya si maoni — ni ngome. Na kuna nguvu ya kimungu inayopatikana dhidi yao.\n\nWarumi 12:2: \"Wala msiifuatishe namna ya dunia hii; bali mgeuzwe kwa kufanywa upya nia zenu.\" Mabadiliko yanaanza akilini. Kufanywa upya si zoezi la fikra chanya — ni ubadilishaji wa kimfumo wa hadithi za uongo na ukweli wa Neno la Mungu. Kila fikira inayopingana na kile Mungu anachosema kukuhusu — fikira hiyo inatekwa nyara.",
      "repentance": "Tambua ngome — mifumo ya mawazo iliyokuwa ikiendesha maisha yako. Iteke nyara. Iweke dhidi ya ukweli wa Neno la Mungu. Anza kufanywa upya kwa akili yako leo.",
      "prayer": "Bwana, ninatambua ngome katika akili yangu leo. Ninaziteka nyara kwa jina la Yesu. Ninazibadilisha na kile unachosema. Ninaanza kufanywa upya kwa akili yangu — si kwa fikra chanya, bali kwa ukweli wa Neno Lako. Nibadilishe. Amina."
    },
    "115": {
      "hook": "Eliya alimwomba Mungu amalize maisha yake. Mungu alituma malaika kumlisha badala yake.",
      "body": "1 Wafalme 19 ni simulizi la uaminifu zaidi la sonona ya kiroho katika Maandiko. Eliya alikuwa ameita moto kutoka mbinguni juu ya Mlima Karmeli. Alikuwa amesimama dhidi ya manabii mia nne na hamsini. Kisha: \"Akaenda mwenyewe jangwani mwendo wa siku moja, akaenda akaketi chini ya mti mmoja wa mretemu, akajiombea kufa, akisema, Yatosha; sasa, Ee Bwana, uutwae uhai wangu\" (1 Wafalme 19:4). Kutoka kilele kikubwa cha kiroho hadi vilindi vya kukata tamaa kwa muda wa siku chache.\n\nJibu la Mungu kwa sonona ya Eliya ni la ajabu katika uwezekano wake: \"Malaika akamgusa, akamwambia, Ondoka ule chakula.\" Chakula na mapumziko — kabla ya mazungumzo ya kitheolojia. Kisha chakula na mapumziko tena. Kisha \"safari ni ndefu mno kwako.\" Mungu alishughulikia hali halisi ya kimwili kabla ya ile ya kiroho. Hakumkemea Eliya kwa kukata tamaa kwake. Alimlisha.\n\nKisha sauti ndogo, ya utulivu — pangoni huko Horebu (1 Wafalme 19:12). Si tetemeko la ardhi, si moto, si mchezo wa kuigiza. Sauti tulivu ya Mungu ikizungumza na nabii aliyechoka. Mungu alikutana na Eliya pale alipokuwa — si pale ambapo angepaswa kuwa — na akamrudisha.",
      "repentance": "Kama uko mahali alipokuwa Eliya, Mungu hayuko mbali nawe. Hawakemei waliochoka. Anawalisha. Njoo Kwake katika uchovu wako na upokee huduma Yake.",
      "prayer": "Bwana, yatosha. Niko kama Eliya chini ya mti. Sifanyi maonyesho ya nguvu nisiyokuwa nayo. Ninakuja Kwako katika uchovu. Nilishe. Niache nipumzike. Na nitakapokuwa tayari — sema katika sauti ndogo, tulivu. Nitasikiliza. Amina."
    }
  },
  "ar": {
    "111": {
      "hook": "التجربة تبدو فريدة بالنسبة لك. المخرج موعود للجميع.",
      "body": "١ كورنثوس ١٠: ١٣: «لم تصبكم تجربة إلا بشرية. ولكن الله أمين، الذي لا يدعكم تُجربون فوق ما تستطيعون، بل سيجعل مع التجربة أيضًا المنفذ لتستطيعوا أن تحتملوا.» ثلاثة ضمانات: التجربة ليست فريدة، وليست فوق طاقتك، وهناك دائمًا مخرج.\n\nالضمان الأول يعالج العزلة التي تنتجها التجربة. تشعر وكأن لا أحد آخر يعاني من هذا. هذا غير صحيح. «لم تصبكم تجربة إلا بشرية.» صراعك إنساني، ليس وحشيًا. آخرون واجهوه. آخرون تغلبوا عليه.\n\nالضمان الثالث ربما يكون الأكثر عملية: عندما تُجرَّب، يوفر الله مخرجًا. دائمًا. ليس أحيانًا — دائمًا. المخرج قد يتطلب حركة — ابتعادًا جسديًا عن الموقف، محادثة تحتاج إجراءها. لكنه موجود دائمًا. السؤال ليس ما إذا كان المخرج موجودًا. السؤال هو هل ستأخذه.",
      "repentance": "ابحث عن المخرج الذي وفره الله في تجربتك الحالية. إنه موجود. قد يتطلب شجاعة أكبر لأخذه من الاستسلام — لكنه موجود.",
      "prayer": "يا رب، أثق بوعدك أن هناك دائمًا مخرجًا. أتوقف عن النظر إلى التجربة وأبدأ بالبحث عن المخرج الذي وفرته. امنحني الشجاعة لأخذه. أختار المخرج بدلاً من السقوط. آمين."
    },
    "112": {
      "hook": "حاولت التوقف. هو لا يطلب منك أن تتوقف وحدك.",
      "body": "الشخص في رومية ٧ — «لست أفعل ما أريده بل أفعل ما أبغضه» (رومية ٧: ١٥) — هو الوصف الأكثر صدقًا للإدمان في العالم القديم. عاقل، مدرك، يريد التغيير، غير قادر على تحقيقه. ليس شخصًا لا يهتم. شخص الاهتمام وحده لا يكفيه.\n\nإجابة بولس في رومية ٨: «إذًا لا شيء من الدينونة الآن على الذين هم في المسيح يسوع... لأن ناموس روح الحياة في المسيح يسوع قد أعتقني من ناموس الخطية والموت» (رومية ٨: ١-٢). ليست نسخة أفضل من إرادتك. ناموس مختلف تمامًا — القوة الخارقة للروح القدس — أقوى من الناموس الذي يجذبك نحو الدمار.\n\nغلاطية ٥: ١: «للحرية أعتقنا المسيح، فاثبتوا إذًا ولا ترتبكوا أيضًا بنير عبودية.» الحرية موجودة. اشتُريت على الصليب. الروح متاح لإنتاجها. عمل الحرية لا يتم بالتمسك أكثر — بل بالاستسلام الأكمل لمن هو بالفعل أقوى مما يمسك بك.",
      "repentance": "أحضر الإدمان بصدق إلى الله. ليس النسخة المنمقة — بل الحقيقية. تقبل المساعدة التي يقدمها — ليس كمكمل لجهدك، بل كقوة تتجاوز جهدك تمامًا.",
      "prayer": "أيها الرب يسوع، أحضر إليك هذا الإدمان — كله، دون تقليل. حاولت التوقف ولا أستطيع بمفردي. أتقبل ما تقدمه — ليس إرادة أفضل، بل الروح الذي يهب الحياة. حرّرني. أستسلم لك أكثر مما استسلمت لما كان يمسك بي. آمين."
    },
    "113": {
      "hook": "الشك الصادق المُقدَّم ليسوع سيجد إجابة صادقة.",
      "body": "يوحنا المعمدان — الرجل الذي دعاه يسوع «أعظم مواليد النساء» (متى ١١: ١١) — أرسل رسالة من السجن: «أأنت هو الآتي أم ننتظر آخر؟» (لوقا ٧: ١٩). النبي الذي عمّد يسوع، والذي رأى الروح ينزل كحمامة — كان يسأل عما إذا كان يسوع حقًا المسيح. في ظلام زنزانة السجن، جاء الشك لأعظم الأنبياء.\n\nلم يُدِن يسوع شك يوحنا. بل أجاب عليه. أرسل دليلًا — العُمي يبصرون، العُرج يمشون، الصُم يسمعون، الموتى يقومون — ولم يطلب من يوحنا أن يكون لديه يقين قبل طرح السؤال. قوبل السؤال بالدليل، لا بالرفض.\n\nشك توما في القيامة حتى لمس الجروح (يوحنا ٢٠: ٢٧-٢٨). ظهر يسوع لتوما تحديدًا وأعطاه بالضبط ما احتاجه. لم يستبعد توما من التلاميذ بسبب الشك. ظهر للشاك. الله لا يخاف من الشك الصادق. إنه يواجهه.",
      "repentance": "أحضر شكك إلى يسوع، لا تبتعد عنه. يستطيع التعامل مع أسئلتك. أجاب يوحنا من السجن. ظهر لتوما. سيقابلك في عدم يقينك.",
      "prayer": "يا رب، لدي شكوك. أخشى أن أقول ذلك، لكنني أؤمن أنك تعرف بالفعل. أحضرها إليك — لا أبتعد عنك. قابلني في عدم يقيني كما قابلت توما. أنا أؤمن، فأعِن عدم إيماني. آمين."
    },
    "114": {
      "hook": "الحرب ليست خارجية بالدرجة الأولى. إنها تُخاض بين أذنيك.",
      "body": "٢ كورنثوس ١٠: ٤-٥: «إذ أسلحة محاربتنا ليست جسدية بل قادرة بالله على هدم حصون. هادمين ظنونًا وكل علو يرتفع ضد معرفة الله، وأسرين كل فكر إلى طاعة المسيح.» حصون. ظنون. علو. كل فكر. المعركة الروحية هي معركة أفكار وسرديات والقصص التي تحدث بها نفسك.\n\nالحصن في العقل هو نمط تفكير أصبح راسخًا لدرجة أنه يبدو حقيقيًا. «الله لا يحبني.» «لن أتغير أبدًا.» «هكذا أنا فقط.» «لا شيء ينجح لي أبدًا.» هذه ليست ملاحظات — إنها حصون. وهناك قوة إلهية متاحة ضدها.\n\nرومية ١٢: ٢: «لا تشاكلوا هذا الدهر، بل تغيّروا عن شكلكم بتجديد ذهنكم.» التحول يبدأ في العقل. التجديد ليس تمرينًا في التفكير الإيجابي — إنه الاستبدال المنهجي للسرديات الكاذبة بحقيقة كلمة الله. كل فكر يناقض ما يقوله الله عنك — يُؤسر ذلك الفكر.",
      "repentance": "حدد الحصون — أنماط التفكير التي كانت تدير حياتك. أسرها. ضعها أمام حقيقة كلمة الله. ابدأ تجديد ذهنك اليوم.",
      "prayer": "يا رب، أحدد الحصون في ذهني اليوم. أسرها باسم يسوع. أستبدلها بما تقوله أنت. أبدأ تجديد ذهني — ليس بالتفكير الإيجابي، بل بحقيقة كلمتك. حوّلني. آمين."
    },
    "115": {
      "hook": "طلب إيليا من الله أن ينهي حياته. أرسل الله ملاكًا ليطعمه بدلاً من ذلك.",
      "body": "١ ملوك ١٩ هو الرواية الأكثر صدقًا للاكتئاب الروحي في الكتاب المقدس. كان إيليا قد استدعى للتو نارًا من السماء على جبل الكرمل. وقف ضد أربعمائة وخمسين نبيًا. ثم: «مضى في البرية مسيرة يوم، وأتى وجلس تحت شجرة رتم وطلب لنفسه أن يموت وقال: كفى الآن يا رب. خذ نفسي» (١ ملوك ١٩: ٤). من أعظم قمة روحية إلى أعماق اليأس الانتحاري في غضون أيام.\n\nاستجابة الله لاكتئاب إيليا استثنائية في عمليتها: «لمسه ملاك وقال له: قم كل.» طعام وراحة — قبل الحوار اللاهوتي. ثم طعام وراحة مرة أخرى. ثم «الطريق أكثر مما تستطيع.» تعامل الله مع الواقع الجسدي قبل الروحي. لم يوبخ إيليا على يأسه. أطعمه.\n\nثم الصوت الخفيف الهادئ — في الكهف عند حوريب (١ ملوك ١٩: ١٢). ليس الزلزال، ولا النار، ولا الدراما. صوت الله اللطيف يتحدث إلى نبي منهك. قابل الله إيليا حيث كان — لا حيث كان يجب أن يكون — وأعاده.",
      "repentance": "إذا كنت في المكان الذي كان فيه إيليا، فالله ليس بعيدًا عنك. لا يوبخ المنهكين. بل يطعمهم. تعال إليه في تعبك وتقبل رعايته.",
      "prayer": "يا رب، كفاني. أنا مثل إيليا تحت الشجرة. لا أتظاهر بقوة لا أملكها. أتيت إليك في الإرهاق. أطعمني. دعني أرتاح. وعندما أكون مستعدًا — تحدث بالصوت الخفيف الهادئ. سأستمع. آمين."
    }
  },
  "yo": {
    "111": {
      "hook": "Ìdẹwò náà dà bí ẹni pé ìtọ̀wọ́ rẹ nìkan ni. Ọ̀nà àbájáde ni a ṣèlérí fún gbogbo ènìyàn.",
      "body": "1 Kọ́ríntì 10:13: \"Kò sí ìdẹwò tí ó ti bá yín, bí kò ṣe ti ẹ̀dá ènìyàn: ṣùgbọ́n Ọlọ́run ṣeni ìgbẹ́kẹ̀lé, ẹni tí kì yóò jẹ́ kí a dẹ ẹ yín wò ju bí ẹ ti lè fara dà á lọ, ṣùgbọ́n pẹ̀lú ìdẹwò náà, yóò tún ṣe ọ̀nà àbájáde, kí ẹ̀yin lè fara dà á.\" Ìdánilójú mẹ́ta: ìdẹwò náà kì í ṣe ti ẹnì kan nìkan, kì í ṣe ju agbára rẹ lọ, àti pé ọ̀nà àbájáde ń bẹ nígbà gbogbo.\n\nÌdánilójú kìíní yanjú ìdáwà tí ìdẹwò máa ń mú wá. O rí i bí ẹni pé kò sí ẹlòmíràn tí ó ń bá èyí jà. Kì í ṣe òtítọ́. \"Kò sí ìdẹwò tí ó ti bá yín, bí kò ṣe ti ẹ̀dá ènìyàn.\" Ìjàkadì rẹ jẹ́ ti ẹ̀dá ènìyàn, kì í ṣe ti ẹranko burúkú. Àwọn mìíràn ti dojú kọ ọ́. Àwọn mìíràn ti ṣẹ́gun rẹ̀.\n\nÌdánilójú kẹta bóyá ni ó wúlò jùlọ: nígbà tí a bá dẹ ọ́ wò, Ọlọ́run yóò pèsè ọ̀nà àbájáde. Nígbà gbogbo. Kì í ṣe nígbà mìíràn — nígbà gbogbo. Ọ̀nà àbájáde náà lè béèrè ìṣíwájú — yíyọ ara ẹni kúrò ní ipò náà, ìjíròrò tí o nílò láti ní. Ṣùgbọ́n ó wà nígbà gbogbo. Ìbéèrè náà kì í ṣe bóyá ọ̀nà àbájáde náà wà. Ó jẹ́ bóyá o máa mú un.",
      "repentance": "Wá ọ̀nà àbájáde tí Ọlọ́run ti pèsè nínú ìdẹwò rẹ lọ́wọ́lọ́wọ́. Ó wà. Ó lè béèrè ìgboyà púpọ̀ láti mú un ju láti fi ara sílẹ̀ lọ — ṣùgbọ́n ó wà.",
      "prayer": "Olúwa, mo gbẹ́kẹ̀lé ìlérí Rẹ pé ọ̀nà àbájáde ń bẹ nígbà gbogbo. Mo dáwọ́ wíwo ìdẹwò náà dúró mo sì bẹ̀rẹ̀ wíwá ọ̀nà àbájáde tí O ti pèsè. Fún mi ní ìgboyà láti mú un. Mo yan ọ̀nà àbájáde dípò ọ̀nà ìṣubú. Àmín."
    },
    "112": {
      "hook": "O ti gbìyànjú láti dáwọ́ dúró. Kò ní ọ láti dáwọ́ dúró nìkan.",
      "body": "Ẹni tí ó wà nínú Romu 7 — \"Èmi kì í ṣe ohun tí mo fẹ́ ṣe, bí kò ṣe ohun tí mo kórìíra\" (Romu 7:15) — ni àpèjúwe olóòótọ́ jùlọ ti ìfẹ́kúfẹ̀ẹ́ ní ayé àtijọ́. Onípé-ìmọ̀, olùmọ̀, olùfẹ́ ìyípadà, aláìlágbára láti mú un jáde. Kì í ṣe ẹni tí kò ṣàníyàn. Ẹni tí ìṣàníyàn kò tó fún.\n\nÌdáhùn Pọ́ọ̀lù wà nínú Romu 8: \"Nítorí náà, kò sí ìdálẹ́bi fún àwọn tí ó wà nínú Kristi Jésù mọ́... nítorí òfin Ẹ̀mí ìyè nínú Kristi Jésù ti dá mi sílẹ̀ lọ́wọ́ òfin ẹ̀ṣẹ̀ àti ikú\" (Romu 8:1-2). Kì í ṣe ẹ̀dà tí ó dára ju ti agbára ìfẹ́ rẹ lọ. Òfin tí ó yàtọ̀ pátápátá — agbára Ẹ̀mí Mímọ́ tí ó ju àdánidá lọ — tí ó lágbára ju òfin tí ó ń fà ọ́ sí ìparun lọ.\n\nGalátíà 5:1: \"Nítorí òmìnira ni Kristi ti dá wa sílẹ̀; ẹ dúró ṣinṣin nínú rẹ̀ nítorí náà, kí ẹ má sì fi ara yín sí abẹ́ àjàgà ìsìnrú mọ́.\" Òmìnira wà. A ra á padà ní àgbélébùú. Ẹ̀mí wà láti mú un jáde. Iṣẹ́ òmìnira kì í ṣe nípa dídìmú mọ́ra sí i — ó jẹ́ nípa fífi ara ẹni fún Ẹni tí ó ti lágbára ju ohun tí ó ń dì ọ́ mú lọ pátápátá.",
      "repentance": "Mú ìfẹ́kúfẹ̀ẹ́ rẹ wá sọ́dọ̀ Ọlọ́run ní òtítọ́. Kì í ṣe ẹ̀dà tí a ti mú kúrò lára èérí — ti òtítọ́ ni. Gba ìrànlọ́wọ́ tí ó ń fúnni — kì í ṣe gẹ́gẹ́ bí àfikún sí ìsapá rẹ, bí kò ṣe gẹ́gẹ́ bí agbára tí ó ré kọjá ìsapá rẹ pátápátá.",
      "prayer": "Olúwa Jésù, mo mú ìfẹ́kúfẹ̀ẹ́ yìí wá sọ́dọ̀ Rẹ — gbogbo rẹ̀, láìdín kù. Mo ti gbìyànjú láti dáwọ́ dúró, èmi kò sì lè ṣe é nìkan. Mo gba ohun tí O ń fúnni — kì í ṣe agbára ìfẹ́ tí ó dára ju, bí kò ṣe Ẹ̀mí tí ó fún ni ní ìyè. Dá mi sílẹ̀. Mo fi ara mi fún Ọ pátápátá ju bí mo ti fi fún ohun tí ó ti ń dì mí mú lọ. Àmín."
    },
    "113": {
      "hook": "Iyèméjì olóòótọ́ tí a mú wá sọ́dọ̀ Jésù yóò rí ìdáhùn olóòótọ́.",
      "body": "Jòhánù Onítẹ̀bọmi — ọkùnrin tí Jésù pè ní \"ẹni tí ó tóbi jùlọ nínú àwọn tí a bí nípa obìnrin\" (Mátíù 11:11) — fi ìránṣẹ́ ránṣẹ́ láti inú túbú: \"Ìwọ ha ni ẹni tí ń bọ̀ wá, tàbí kí a máa retí ẹlòmíràn?\" (Lúùkù 7:19). Wòlíì tí ó bamitisi Jésù, tí ó rí bí Ẹ̀mí ṣe sọ̀kalẹ̀ bí àdàbà — ń bi bóyá Jésù ni Mèsáyà lóòótọ́. Nínú òkùnkùn yàrá túbú, iyèméjì dé bá wòlíì tí ó tóbi jùlọ.\n\nJésù kò dá ẹ̀bi fún iyèméjì Jòhánù. Ó dá a lóhùn. Ó rán ẹ̀rí padà — afọ́jú ríran, arọ rìn, adití gbọ́, òkú jíǹde — kò sì béèrè kí Jòhánù ní ìdánilójú kó tó béèrè ìbéèrè náà. A pàdé ìbéèrè náà pẹ̀lú ẹ̀rí, kì í ṣe kíkọ̀.\n\nThómásì ṣiyèméjì àjíǹde náà títí ó fi fi ọwọ́ kan àwọn ọgbẹ́ (Jòhánù 20:27-28). Jésù farahàn Thómásì ní pàtàkì ó sì fún un ní ohun tí ó nílò gan-an. Kò yọ Thómásì kúrò nínú àwọn ọmọ ẹ̀yìn nítorí iyèméjì. Ó farahàn olùyèméjì náà. Ọlọ́run kò bẹ̀rù iyèméjì olóòótọ́. Ó ń pàdé rẹ̀.",
      "repentance": "Mú iyèméjì rẹ wá sọ́dọ̀ Jésù, má ṣe sá kúrò lọ́dọ̀ Rẹ̀. Ó lè bójú tó àwọn ìbéèrè rẹ. Ó dá Jòhánù lóhùn láti inú túbú. Ó farahàn Thómásì. Yóò pàdé ọ nínú àìdánilójú rẹ.",
      "prayer": "Olúwa, mo ní iyèméjì. Mo bẹ̀rù láti sọ bẹ́ẹ̀, ṣùgbọ́n mo gbàgbọ́ pé O ti mọ̀ ọ́n tẹ́lẹ̀. Mo mú wọn wá sọ́dọ̀ Rẹ — kì í ṣe kúrò lọ́dọ̀ Rẹ. Pàdé mi nínú àìdánilójú mi bí O ṣe pàdé Thómásì. Mo gbàgbọ́; ràn àìgbàgbọ́ mi lọ́wọ́. Àmín."
    },
    "114": {
      "hook": "Ogun náà kì í ṣe ti ìta ní àkọ́kọ́. A ń jà á láàrin etí rẹ méjèèjì.",
      "body": "2 Kọ́ríntì 10:4-5: \"Nítorí ohun ìjà ogun wa kì í ṣe ti ara, bí kò ṣe alágbára ní ọwọ́ Ọlọ́run láti wó àwọn odi olódi lulẹ̀; a ń wó àwọn àríyànjiyàn lulẹ̀, àti gbogbo ìṣesí gíga tí ó gbé ara rẹ̀ ga sí ìmọ̀ Ọlọ́run, a sì mú gbogbo èrò inú ní ìgbèkùn sí ìgbọ́ràn sí Kristi.\" Odi olódi. Àríyànjiyàn. Ìṣesí gíga. Gbogbo èrò inú. Ogun tẹ̀mí jẹ́ ogun ti èrò, ìtàn, àti àwọn ìtàn tí o ń sọ fún ara rẹ.\n\nOdi olódi nínú ọpọlọ jẹ́ ìrísí èrò tí ó ti fìdí múlẹ̀ tó bẹ́ẹ̀ tí ó fi dà bí òtítọ́. \"Ọlọ́run kò nífẹ̀ẹ́ mi.\" \"Èmi kò ní yí padà láéláé.\" \"Bẹ́ẹ̀ ni mo rí nìyẹn.\" \"Kò sí ohun tí ó ń ṣiṣẹ́ dáradára fún mi rí.\" Àwọn wọ̀nyí kì í ṣe àkíyèsí — wọ́n jẹ́ odi olódi. Àti pé agbára àtọ̀runwá wà tí a lè fi lòdì sí wọn.\n\nRomu 12:2: \"Ẹ má ṣe bá ayé yìí mu, ṣùgbọ́n kí a yí yín padà nípa ìsọdọ̀tun èrò inú yín.\" Ìyípadà bẹ̀rẹ̀ nínú ọpọlọ. Ìsọdọ̀tun kì í ṣe eré ìmọ̀ ọ̀pọ̀lọpọ̀ rere — ó jẹ́ ìyípadà ìtòlẹ́sẹẹsẹ ti àwọn ìtàn èké pẹ̀lú òtítọ́ Ọ̀rọ̀ Ọlọ́run. Gbogbo èrò tí ó tako ohun tí Ọlọ́run sọ nípa rẹ — a mú èrò náà ní ìgbèkùn.",
      "repentance": "Dá àwọn odi olódi mọ̀ — àwọn ìrísí èrò tí ó ti ń darí ìgbésí ayé rẹ. Mú wọn ní ìgbèkùn. Fi wọ́n wéra pẹ̀lú òtítọ́ Ọ̀rọ̀ Ọlọ́run. Bẹ̀rẹ̀ ìsọdọ̀tun ọpọlọ rẹ lónìí.",
      "prayer": "Olúwa, mo dá àwọn odi olódi mọ̀ nínú ọpọlọ mi lónìí. Mo mú wọn ní ìgbèkùn ní orúkọ Jésù. Mo fi ohun tí O sọ rọ́pò wọn. Mo bẹ̀rẹ̀ ìsọdọ̀tun ọpọlọ mi — kì í ṣe pẹ̀lú ìmọ̀ ọ̀pọ̀lọpọ̀ rere, bí kò ṣe pẹ̀lú òtítọ́ Ọ̀rọ̀ Rẹ. Yí mi padà. Àmín."
    },
    "115": {
      "hook": "Èlíjà béèrè lọ́wọ́ Ọlọ́run láti fòpin sí ìyè rẹ̀. Ọlọ́run rán áńjẹ́lì kan láti bọ́ ọn dípò bẹ́ẹ̀.",
      "body": "1 Àwọn Ọba 19 ni àkọsílẹ̀ olóòótọ́ jùlọ ti ìsoríkọ́ tẹ̀mí nínú Ìwé Mímọ́. Èlíjà ti ké iná lát'ọ̀run síl'orí Òkè Kámẹ́lì. Ó ti dúró tako ọ̀ọ́dúrún àti àádọ́ta wòlíì. Lẹ́yìn náà: \"Ó lọ sí aginjù ìrìn ọjọ́ kan, ó lọ sì jókòó sábẹ́ igi kan, ó sì ń fẹ́ ikú fún ara rẹ̀, ó ń wí pé, Ó tó; ǹjẹ́, Olúwa, gba ẹ̀mí mi\" (1 Àwọn Ọba 19:4). Láti orí òkè tẹ̀mí tí ó ga jùlọ dé ọ̀gbun ìrètí ìpara-ẹni láàrin ọjọ́ mélòó kan.\n\nÌdáhùn Ọlọ́run sí ìsoríkọ́ Èlíjà yanilẹ́nu nínú bí ó ṣe wúlò tó: \"Áńjẹ́lì kan fọwọ́ kàn án, ó sì wí fún un pé, Dìde jẹun.\" Oúnjẹ àti ìsinmi — kó tó bọ́ sínú ìjíròrò ẹ̀kọ́ ìsìn. Lẹ́yìn náà oúnjẹ àti ìsinmi lẹ́ẹ̀kan sí i. Lẹ́yìn náà \"ìrìn àjò náà pọ̀ jù fún ọ.\" Ọlọ́run dojú kọ ipò ti ara kó tó dojú kọ ti tẹ̀mí. Kò bá Èlíjà wí nítorí ìrètí àìní rẹ̀. Ó bọ́ ọn.\n\nLẹ́yìn náà ohùn dídákẹ́ jẹ́ẹ́ tí ó rọ̀rùn — ní ihò àpáta ní Hórébù (1 Àwọn Ọba 19:12). Kì í ṣe ìmìtìtì ilẹ̀, kì í ṣe iná, kì í ṣe eré ìdárayá. Ohùn Ọlọ́run tí ó rọ̀rùn ń bá wòlíì tí ó ti rẹ̀ sọ̀rọ̀. Ọlọ́run bá Èlíjà pàdé níbi tí ó wà — kì í ṣe níbi tí ó yẹ kí ó wà — ó sì mú un padà.",
      "repentance": "Bí o bá wà níbi tí Èlíjà wà, Ọlọ́run kò jìnnà sí ọ. Kò bá àwọn tí ó rẹ̀ wí. Ó ń bọ́ wọn. Wá sọ́dọ̀ Rẹ̀ nínú àárẹ̀ rẹ kí o sì gba ìtọ́jú Rẹ̀.",
      "prayer": "Olúwa, ó tó fún mi. Mo dà bí Èlíjà lábẹ́ igi. Èmi kì í ṣe àṣehàn agbára tí èmi kò ní. Mo wá sọ́dọ̀ Rẹ nínú àárẹ̀. Bọ́ mi. Jẹ́ kí n sinmi. Nígbà tí mo bá ti ṣetán — sọ̀rọ̀ nínú ohùn dídákẹ́ jẹ́ẹ́ tí ó rọ̀rùn. Èmi yóò tẹ́tí sí i. Àmín."
    }
  },
  "ig": {
    "111": {
      "hook": "Ọnwụnwa ahụ dị ka nke naanị gị. A kwere onye ọ bụla nkwa ụzọ mgbapụ.",
      "body": "1 Ndị Kọrint 10:13: \"Ọ dịghị ọnwụnwa dakwasịrị unu, ma ọ bụghị nke bụ ihe unyi mmadụ nile na-adịkarị. Ma Chineke bụ onye kwesịrị ntụkwasị obi, onye na-agaghị ekwe ka a nwaa unu ihe karịrị ike unu, kama ya na ọnwụnwa ahụ ọ ga-emekwa ka ọ dịrị ụzọ mgbapụ, ka unu wee nwee ike ịnagide ya.\" Nkwa atọ: ọnwụnwa ahụ abụghị nke naanị gị, ọ karịghị ike gị, ọ dịkwa ụzọ mgbapụ mgbe niile.\n\nNkwa mbụ na-edozi mwepụ nke ọnwụnwa na-emepụta. Ị na-eche na ọ dịghị onye ọzọ na-alụ ọgụ a. Ọ bụghị eziokwu. \"Ọ dịghị ọnwụnwa dakwasịrị unu, ma ọ bụghị nke bụ ihe unyi mmadụ nile na-adịkarị.\" Ọgụ gị bụ nke mmadụ, ọ bụghị nke anụ ọhịa. Ndị ọzọ ezuola ya. Ndị ọzọ emeriela ya.\n\nNkwa nke atọ, ma eleghị anya, bụ nke bara uru karịa: mgbe a na-anwa gị ọnwụnwa, Chineke na-enye ụzọ mgbapụ. Mgbe niile. Ọ bụghị mgbe ụfọdụ — mgbe niile. Ụzọ mgbapụ ahụ nwere ike ịchọ mmegharị — iwepụ onwe gị n'ahụ́ site n'ọnọdụ ahụ, mkparịta ụka ị chọrọ inwe. Ma ọ na-adị mgbe niile. Ajụjụ ahụ abụghị ma ọpụpụ ahụ dị. Ọ bụ ma ị ga-anara ya.",
      "repentance": "Chọọ ụzọ mgbapụ Chineke wepụtaworo n'ọnwụnwa gị nke ugbu a. Ọ dị. O nwere ike ịchọ obi ike karịa ka ị nara ya karịa ka ị kwe — ma ọ dị.",
      "prayer": "Onyenwe anyị, m tụkwasịrị obi n'ime nkwa Gị na ụzọ mgbapụ na-adịkarị mgbe niile. M na-akwụsị ile ọnwụnwa ahụ anya ma malite ịchọ ọpụpụ ahụ I wepụtara. Nye m obi ike ịnara ya. Ana m ahọrọ ụzọ mgbapụ kama ụzọ ịdaba. Amen."
    },
    "112": {
      "hook": "Ị gbaliela ịkwụsị. Ọ dịghị achọ ka ị kwụsị naanị gị.",
      "body": "Onye ahụ dị na Ndị Rom 7 — \"Adịghị m eme ihe m chọrọ ime, kama ihe m kpọrọ asị ka m na-eme\" (Ndị Rom 7:15) — bụ nkọwa kachasị eziokwu banyere ịda mmanya na ụwa oge ochie. Onye nwere uche, onye maara ihe, onye chọrọ mgbanwe, onye na-enweghị ike ime ya. Ọ bụghị onye na-adịghị eche banyere ya. Onye na-eche banyere ya ezughị.\n\nAzịza Pọl dị na Ndị Rom 8: \"Ya mere, ọ dịghịkwa mkpe ọ bụla ọzọ nye ndị nọ n'ime Kraịst Jizọs... n'ihi na iwu nke Mmụọ nke ndụ n'ime Kraịst Jizọs emeworo m onye nnwere onwe pụọ n'iwu nke mmehie na ọnwụ\" (Ndị Rom 8:1-2). Ọ bụghị ụdị ọma karịa nke ike mmụọ gị. Iwu dị iche kpamkpam — ike ebube nke Mmụọ Nsọ — nke sikwuru ike karịa iwu na-adọkpụrụ gị gaa n'ịla n'iyi.\n\nNdị Galeshia 5:1: \"N'ihi nnwere onwe ka Kraịst mere ka anyị nwere onwe anyi; ya mere, guzosienụ ike, unu ekwekwala ka a tinyeghachi unu n'okiri ohu.\" Nnwere onwe dị. E jiri ya zụta ya na obe. Mmụọ Nsọ dịla iji mepụta ya. Ọrụ nnwere onwe adịghị eme site n'ijide ike karịa — ọ na-eme site n'inyefe onwe gị n'aka nke bụburu ihe siri ike karịa ihe na-ejide gị.",
      "repentance": "Wetara Chineke ịda mmanya gị n'eziokwu. Ọ bụghị ụdị a hichapụrụ — nke ezi n'ezi. Nabata enyemaka ọ na-enye — ọ bụghị dịka mgbakwunye na mgbalị gị, kama dịka ike gafere mgbalị gị kpamkpam.",
      "prayer": "Onyenwe m Jizọs, ana m eweta ịda mmanya a n'ihu Gị — ya niile, na-enweghị ibelata ya. Agbaliala m ịkwụsị ma enweghị m ike ime ya naanị m. Ana m anabata ihe Ị na-enye — ọ bụghị ike mmụọ ka mma, kama Mmụọ nke na-enye ndụ. Meere m onye nnwere onwe. Ana m enyefe onwe m nye Gị karịa ka m si enyefe onwe m nye ihe jidere m. Amen."
    },
    "113": {
      "hook": "Obi abụọ eziokwu wetaara Jizọs ga-achọta azịza eziokwu.",
      "body": "Jọn Onye Baptaịzị — nwoke Jizọs kpọrọ \"onye kachasị ukwuu n'ime ndị nwanyị mụrụ\" (Matiu 11:11) — zipụrụ ozi si n'ụlọ mkpọrọ: \"Ọ bụ gị bụ onye ahụ na-abịa, ka anyị ga-achọ ọzọ?\" (Luk 7:19). Onye amụma ahụ mere Jizọs baptism, onye hụrụ ka Mmụọ Nsọ si n'eluigwe rịdata dịka nduru — na-ajụ ma Jizọs ọ̀ bụ ezie Mezaya. N'ọchịchịrị nke ime ụlọ mkpọrọ, obi abụọ bịakwutere onye amụma kachasị ukwuu.\n\nJizọs amaghị Jọn ikpe maka obi abụọ ya. Ọ zara ya. O ziputara ihe akaebe — ndị kpuru ìsì na-ahụ ụzọ, ndị ngwụrọ na-eje ije, ndị ntị chiri na-anụ ihe, ndị nwụrụ anwụ na-ebilikwa — ọ chọghịkwa ka Jọn nwee obi mkpebi tupu ọ jụọ ajụjụ ahụ. Ejiri ihe akaebe zaghachi ajụjụ ahụ, ọ bụghị ajụ ya.\n\nTọmọs nwere obi abụọ banyere mbilite n'ọnwụ ahụ ruo mgbe o metụrị ọnya ndị ahụ aka (Jọn 20:27-28). Jizọs pụtara ìhè nye Tọmọs kpọmkwem ma nye ya kpọmkwem ihe ọ chọrọ. Ọ kpochapụghị Tọmọs n'etiti ndị na-eso ụzọ ya n'ihi obi abụọ ya. Ọ pụtara ìhè nye onye nwere obi abụọ. Chineke anaghị atụ egwu obi abụọ eziokwu. Ọ na-ezute ya.",
      "repentance": "Wetara Jizọs obi abụọ gị, ewezuga ya n'ebe ọ nọ. Ọ nwere ike ijikwa ajụjụ gị. Ọ zara Jọn si n'ụlọ mkpọrọ. Ọ pụtara ìhè nye Tọmọs. Ọ ga-ezute gị n'enweghị mkpebi gị.",
      "prayer": "Onyenwe anyị, enwere m obi abụọ. Atụrụ m egwu ikwu nke ahụ, ma ekwenyere m na Ị maralarị. Ana m eweta ha n'ihu Gị — ewezugaghị ha n'ebe Ị nọ. Zute m n'enweghị mkpebi m dịka i si zute Tọmọs. Ekwenyere m; nyere ekweghị ekwe m aka. Amen."
    },
    "114": {
      "hook": "Agha ahụ abụghị nke mbụ nke mpụga. A na-alụ ya n'etiti ntị gị abụọ.",
      "body": "2 Ndị Kọrint 10:4-5: \"N'ihi na ngwa agha nke ọgụ anyị abụghị nke anụ ahụ, kama ha dị ike n'ihu Chineke ịkwada ebe niile e wusiri ike; anyị na-akwada arụmụka niile na ihe niile na-ebuli onwe ha elu megide ihe ọmụma nke Chineke, na-adọtakwa echiche ọ bụla dịka onye a dọtara n'agha ka o rube isi na Kraịst.\" Ebe e wusiri ike. Arụmụka. Ihe na-ebuli onwe ha elu. Echiche ọ bụla. Agha ime mmụọ bụ agha nke echiche, akụkọ, na akụkọ ndị ị na-agwa onwe gị.\n\nEbe e wusiri ike n'echiche bụ ụkpụrụ iche echiche nke aghọworo ihe siri ike nke ọ na-adị ka eziokwu. \"Chineke ahụghị m n'anya.\" \"Agaghị m agbanwe ma ọlị.\" \"Otu a ka m dị.\" \"Ọ dịghị ihe na-agara m nke ọma.\" Ndị a abụghị nlele — ha bụ ebe e wusiri ike. Enwekwara ike ebube dị iji megide ha.\n\nNdị Rom 12:2: \"Unu adaghị eyi ka ụwa nke a; kama ka a gbanwee unu site n'imegharị echiche unu ọhụrụ.\" Mgbanwe ahụ na-amalite n'echiche. Imegharị ọhụrụ abụghị mmega ahụ echiche mma — ọ bụ mgbanwe usoro nke akụkọ ụgha ka eji eziokwu Okwu Chineke dochie ya. Echiche ọ bụla na-emegide ihe Chineke kwuru banyere gị — a na-adọta echiche ahụ n'agha.",
      "repentance": "Chọpụta ebe e wusiri ike — ụkpụrụ iche echiche na-achị ndụ gị. Dọta ha n'agha. Tinye ha megide eziokwu Okwu Chineke. Malite imegharị echiche gị ọhụrụ taa.",
      "prayer": "Onyenwe anyị, achọpụtala m ebe e wusiri ike n'echiche m taa. Ana m adọta ha n'agha n'aha Jizọs. Ana m eji ihe Ị na-ekwu dochie ha. Ana m amalite imegharị echiche m ọhụrụ — ọ bụghị site n'echiche mma, kama site n'eziokwu Okwu Gị. Gbanwee m. Amen."
    },
    "115": {
      "hook": "Ịlaịja gwara Chineke ka ọ kwụsị ndụ ya. Chineke zitere mmụọ ozi ka o nye ya nri kama.",
      "body": "1 Ndị Eze 19 bụ akụkọ kachasị eziokwu banyere mwute ime mmụọ n'Akwụkwọ Nsọ. Ịlaịja akpọtụrụla ọkụ si n'eluigwe n'elu Ugwu Kamel. O guzoworola imegide ndị amụma dị narị anọ na iri ise. Mgbe ahụ: \"O jere ihe dị ka ije otu ụbọchị n'ọzara ma bịa nọdụ ala n'okpuru osisi rọọm, rịọ ka ọ nwụọ, sị, Ọ ezuola; ugbu a, Onyenwe anyị, kpọrọ ndụ m\" (1 Ndị Eze 19:4). Site n'elu kachasị ukwuu nke mmụọ ruo n'ime ala nke nchekasị obi ọnwụ n'ime ụbọchị ole na ole.\n\nAzịza Chineke nyere maka mwute Ịlaịja dị ịtụnanya n'usoro ya: \"Mmụọ ozi metụrụ ya aka, sị ya, Bilie rie nri.\" Nri na izu ike — tupu mkparịta ụka nkà mmụta okpukpe. Mgbe ahụ nri na izu ike ọzọ. Mgbe ahụ \"ije ahụ dị elu karịrị gị.\" Chineke lekwasịrị eziokwu nke anụ ahụ anya tupu nke mmụọ. Ọ baghị Ịlaịja mba maka nchekasị obi ya. O nyere ya nri.\n\nMgbe ahụ olu dị nro dị jụụ — n'ime ọgba ahụ dị na Horeb (1 Ndị Eze 19:12). Ọ bụghị ala ọma jijiji, ọ bụghị ọkụ, ọ bụghị egwuregwu. Olu dị nro nke Chineke na-agwa onye amụma ike gwụrụ okwu. Chineke zutere Ịlaịja ebe ọ nọ — ọ bụghị ebe o kwesịrị ịnọ — ma mee ka ọ laghachi azụ.",
      "repentance": "Ọ bụrụ na ị nọ n'ebe Ịlaịja nọ, Chineke anọghị anya gị. Ọ dịghị aba ndị ike gwụrụ mba. Ọ na-enye ha nri. Bịa n'ihu ya n'ike gwụrụ gị ma nabata nlekọta ya.",
      "prayer": "Onyenwe anyị, ọ ezuola. Adị m ka Ịlaịja n'okpuru osisi. Anaghị m eme ka a mara ike m na-enweghị. Ana m abịa n'ihu Gị n'ike ọgwụgwụ. Nye m nri. Kwe ka m zuru ike. Mgbe m dị njikere — kwuo n'olu dị nro dị jụụ. Aga m ege ntị. Amen."
    }
  },
  "ha": {
    "111": {
      "hook": "Jarabar tana ji kamar ta musamman gareka. An yi alkawarin hanyar fita ga kowa.",
      "body": "1 Korintiyawa 10:13: \"Wata jarabawa ba ta same ku ba face irin ta ɗan adam. Amma Allah amintacce ne, wanda ba zai yarda a jarabce ku fiye da ƙarfinku ba, amma tare da jarabawar kuma zai yi hanyar fita, don ku iya jurewa.\" Tabbaci uku: jarabar ba ta musamman ba ce, ba ta wuce ƙarfinka ba, kuma akwai hanyar fita koyaushe.\n\nTabbaci na farko yana magance keɓewar da jaraba ke haifarwa. Kana jin kamar babu wani mai fama da wannan. Ba gaskiya ba ne. \"Wata jarabawa ba ta same ku ba face irin ta ɗan adam.\" Gwagwarmayarka na ɗan adam ne, ba na dabba ba. Wasu sun fuskance ta. Wasu sun sha nasara akanta.\n\nTabbaci na uku wataƙila shi ne mafi amfani: idan aka jarabce ka, Allah yana ba da hanyar fita. Koyaushe. Ba wani lokaci ba — koyaushe. Hanyar fita na iya buƙatar motsi — kawar da kai ta jiki daga halin, magana da kake buƙatar yi. Amma tana wanzuwa koyaushe. Tambayar ba ita ce ko hanyar fita take wanzuwa ba. Ita ce ko za ka ɗauke ta.",
      "repentance": "Nemi hanyar fita da Allah ya tanadar a cikin jarabar da kake ciki yanzu. Tana wanzuwa. Tana iya buƙatar ƙarfin hali fiye da ba da kai — amma tana wanzuwa.",
      "prayer": "Ubangiji, na dogara ga alkawarinka na cewa akwai hanyar fita koyaushe. Na daina kallon jarabar ina fara neman hanyar fita da ka tanadar. Ka ba ni ƙarfin hali in ɗauke ta. Na zaɓi hanyar fita maimakon hanyar faɗuwa. Amin."
    },
    "112": {
      "hook": "Ka riga ka yi ƙoƙarin daina. Ba ya neman ka daina kai kaɗai.",
      "body": "Mutumin da ke cikin Romawa 7 — \"Ba na yin abin da nake so, sai dai abin da nake ƙi\" (Romawa 7:15) — shi ne bayanin da ya fi gaskiya na shaye-shaye a duniyar dā. Mai hankali, mai sani, mai son canji, wanda ba shi da ikon aiwatar da shi. Ba mutum wanda bai damu ba. Mutum wanda kulawa kaɗai bai isa ba.\n\nAmsar Bulus tana cikin Romawa 8: \"Saboda haka, yanzu babu hukunci ga waɗanda suke cikin Kristi Yesu... domin dokar Ruhu na rai a cikin Kristi Yesu ta 'yantar da ni daga dokar zunubi da mutuwa\" (Romawa 8:1-2). Ba wani sigar da ya fi na ƙarfin zuciyarka ba. Doka dabam dabam gaba ɗaya — ikon allahntaka na Ruhu Mai Tsarki — wanda ya fi ƙarfi da dokar da take janyo ka zuwa ga hallaka.\n\nGalatiyawa 5:1: \"Domin 'yanci ne Kristi ya 'yantar da mu; saboda haka ku tsaya daram, kada ku sāke shiga cikin ƙunci na bauta.\" 'Yanci yana wanzuwa. An saye shi a kan gicciye. Ruhu yana nan don samar da shi. Aikin 'yanci ba a yin sa ta ƙara riƙewa da ƙarfi — ana yin sa ta ƙara mika kai ga Wanda ya riga ya fi ƙarfi da abin da yake riƙe ka.",
      "repentance": "Kawo shaye-shayenka da gaskiya ga Allah. Ba tsaftataccen sigar ba — na gaskiya. Karɓi taimakon da yake bayarwa — ba a matsayin ƙari ga ƙoƙarinka ba, sai dai a matsayin iko wanda ya wuce ƙoƙarinka gaba ɗaya.",
      "prayer": "Ubangiji Yesu, na kawo maka wannan shaye-shaye — dukkansa, ba tare da rage shi ba. Na yi ƙoƙarin dainawa amma ba zan iya kaina ba. Na karɓi abin da kake bayarwa — ba ƙarfin zuciya mafi kyau ba, sai dai Ruhu wanda ke bayar da rai. Ka 'yantar da ni. Na mika kai gareka gaba ɗaya fiye da ga abin da yake riƙe ni. Amin."
    },
    "113": {
      "hook": "Shakku na gaskiya da aka kawo wa Yesu zai sami amsa ta gaskiya.",
      "body": "Yohanna Mai Baftisma — mutumin da Yesu ya kira \"mafi girma cikin waɗanda mata suka haifa\" (Matiyu 11:11) — ya aika saƙo daga kurkuku: \"Kai ne wanda zai zo, ko mu jira wani?\" (Luka 7:19). Annabin da ya yi wa Yesu baftisma, wanda ya ga Ruhu ya sauko kamar kurciya — yana tambaya ko Yesu shi ne hakika Almasihu. A duhun kurkuku, shakku ya zo wa annabi mafi girma.\n\nYesu bai la'anci shakkun Yohanna ba. Ya amsa masa. Ya aika shaida — makafi suna gani, guragu suna tafiya, kurame suna ji, matattu suna tashi — bai kuma buƙaci Yohanna ya sami tabbaci kafin ya yi tambayar ba. An sadu da tambayar da shaida, ba ƙi ba.\n\nToma ya yi shakkun tashin matattu har sai da ya taɓa raunuka (Yohanna 20:27-28). Yesu ya bayyana wa Toma musamman kuma ya ba shi ainihin abin da yake buƙata. Bai fitar da Toma daga cikin almajiran ba saboda shakku. Ya bayyana wa mai shakkun. Allah ba ya tsoron shakku na gaskiya. Yana sadu da shi.",
      "repentance": "Kawo shakkunka ga Yesu, ba nesa da shi ba. Zai iya jimre tambayoyinka. Ya amsa wa Yohanna daga kurkuku. Ya bayyana wa Toma. Zai sadu da kai a rashin tabbacinka.",
      "prayer": "Ubangiji, ina da shakku. Ina jin tsoron faɗin haka, amma na yi imani ka riga ka sani. Ina kawo su gareka — ba nesa da kai ba. Ka sadu da ni a rashin tabbaci na yadda ka sadu da Toma. Na yi imani; ka taimaki rashin imani na. Amin."
    },
    "114": {
      "hook": "Yaƙin ba na waje ba ne da farko. Ana yin sa ne tsakanin kunnuwanka.",
      "body": "2 Korintiyawa 10:4-5: \"Domin makaman yaƙinmu ba na jiki ba ne, amma suna da iko daga Allah don rushe kagaru; muna rushe fadace-fadace da kowace babbar magana da take tayar da kanta a kan sanin Allah, muna kuma kama kowace tunani mai ban zunubi don ta yi biyayya ga Kristi.\" Kagaru. Fadace-fadace. Babbar magana. Kowace tunani. Yaƙin ruhaniya yaƙi ne na dabaru, labarai, da tatsuniyoyin da kake gaya wa kanka.\n\nKagara a cikin hankali dabara ce ta tunani da ta yi tushe har ta zama kamar gaskiya. \"Allah ba ya ƙaunata.\" \"Ba zan taɓa canjawa ba.\" \"Haka nake kawai.\" \"Babu abin da yake yi mini aiki.\" Waɗannan ba lura ba ne — kagaru ne. Kuma akwai ikon allahntaka da za a yi amfani da shi a kansu.\n\nRomawa 12:2: \"Kada ku bi salon wannan zamani, sai dai a canja ku ta wurin sabunta hankalinku.\" Canjin yana farawa a cikin hankali. Sabuntawar ba dabara ce ta tunani mai kyau ba — ita ce maye gurbin tsari na tatsuniyoyin ƙarya da gaskiyar Maganar Allah. Kowace tunani da take saɓawa da abin da Allah yake faɗi game da kai — ana kama wannan tunanin.",
      "repentance": "Gano kagaru — dabarun tunani da suka riga suke tafiyar da rayuwarka. Ka kama su. Ka sanya su a kan gaskiyar Maganar Allah. Ka fara sabunta hankalinka yau.",
      "prayer": "Ubangiji, na gano kagaru a cikin hankalina yau. Na kama su a cikin sunan Yesu. Na maye gurbinsu da abin da kake faɗi. Na fara sabunta hankalina — ba da tunani mai kyau ba, sai da gaskiyar Maganarka. Ka canja ni. Amin."
    },
    "115": {
      "hook": "Iliya ya roƙi Allah ya ƙare ransa. Allah ya aiko mala'ika ya ciyar da shi maimakon.",
      "body": "1 Sarakuna 19 shi ne labari mafi gaskiya na baƙin ciki na ruhaniya cikin Nassi. Iliya ya kira wuta daga sama a kan Dutsen Karmel. Ya tsaya kan annabawa ɗari huɗu da hamsin. Sannan: \"Ya tafi cikin jeji tafiyar rana ɗaya, ya zauna a ƙarƙashin itacen rotem, ya roƙi mutuwa a kansa, yana cewa, Ya isa; yanzu, ya Ubangiji, ka ɗauki raina\" (1 Sarakuna 19:4). Daga mafi girman kolin ruhaniya zuwa zurfin fatan mutuwa cikin 'yan kwanaki.\n\nAmsar Allah ga baƙin cikin Iliya ban mamaki ce a hanyar amfaninta: \"Mala'ika ya taɓa shi ya ce masa, Tashi ka ci abinci.\" Abinci da hutawa — kafin tattaunawa ta tauhidi. Sannan abinci da hutawa kuma. Sannan \"tafiyar ta yi wa yawa gareka.\" Allah ya magance gaskiyar jiki kafin ta ruhaniya. Bai zargi Iliya saboda fatan mutuwarsa ba. Ya ciyar da shi.\n\nSannan muryar shiru mai laushi — a cikin kogo a Horeb (1 Sarakuna 19:12). Ba girgizar ƙasa ba, ba wuta ba, ba wasa ba. Muryar Allah mai laushi tana yin magana da annabi wanda ya gaji. Allah ya sadu da Iliya inda yake — ba inda ya kamata ya kasance ba — kuma ya dawo da shi.",
      "repentance": "Idan kana wurin da Iliya yake, Allah ba ya nesa da kai. Ba ya zargin gajiyayyu. Yana ciyar da su. Zo gareshi cikin gajiyarka ka karɓi kulawarsa.",
      "prayer": "Ubangiji, ya isa. Ina kama da Iliya ƙarƙashin itace. Ba na yin wasan ƙarfi wanda ba ni da shi. Ina zuwa gareka cikin gajiya. Ka ciyar da ni. Ka bar ni in huta. Kuma idan na shirya — ka yi magana cikin muryar shiru mai laushi. Zan saurara. Amin."
    }
  },
  "pcm": {
    "111": {
      "hook": "Di temptation feel like say na only you e dey happen to. God don promise say way out dey for everybody.",
      "body": "1 Corinthians 10:13: \"No temptation don catch you wey no be common to man. God dey faithful; E no go allow make dem tempt you pass wetin you fit carry, but as e dey tempt you, E go also provide way out, make you fit endure am.\" Three promises: di temptation no be only for you, e no pass wetin you fit carry, and way out dey always.\n\nDi first promise dey address di isolation wey temptation dey bring. You dey feel like say no other person dey struggle with dis one. E no be true. \"No temptation don catch you wey no be common to man.\" Your struggle na human one, e no be monster one. Oda people don face am. Oda people don overcome am.\n\nDi third promise fit be di one wey get more sense pass: when dem tempt you, God go provide way out. Always. E no be sometimes — na always. Di way out fit need movement — to comot your body from di situation, one conversation wey you need to have. But e dey there always. Di question no be whether di exit dey. Na whether you go take am.",
      "repentance": "Find di way out wey God don provide for your current temptation. E dey there. E fit need more courage to take am pass to give in — but e dey there.",
      "prayer": "Lord, I trust Your promise say way out dey always. I don stop to dey look di temptation and I don start to dey look for di exit wey You provide. Give me di courage to take am. I choose di way out over di way down. Amen."
    },
    "112": {
      "hook": "You don try to stop. E no ask you make you stop alone.",
      "body": "Di person for Romans 7 — \"I no dey do wetin I want to do, but di very thing wey I hate na im I dey do\" (Romans 7:15) — na di most honest description of addiction for ancient world. E get sense, e sabi, e wan change, but e no fit produce di change. E no be person wey no care. Na person wey to care no reach.\n\nPaul answer dey for Romans 8: \"So now, no condemnation remain for those wey dey inside Christ Jesus... because through Christ Jesus di law of Spirit wey dey give life don set you free from di law of sin and death\" (Romans 8:1-2). E no be better version of your willpower. Na completely different law — di supernatural power of Holy Spirit — wey strong pass di law wey dey pull you go destruction.\n\nGalatians 5:1: \"Na for freedom Christ don make us free. So stand firm, no let anybody put unu again under yoke of slavery.\" Freedom dey. Dem buy am for cross. Spirit dey available to produce am. Di work of freedom no be to hold tight — na to surrender well well to di One wey don already strong pass wetin dey hold you.",
      "repentance": "Bring di addiction come to God with honesty. No bring di clean version — bring di real one. Receive di help wey E dey offer — no be as extra for your effort, but as power wey pass your effort completely.",
      "prayer": "Lord Jesus, I dey bring dis addiction come to You — everything, I no go minimize am. I don try to stop and I no fit do am alone. I receive wetin You dey offer — no be better willpower, but di Spirit wey dey give life. Set me free. I dey surrender well well to You pass to wetin don dey hold me. Amen."
    },
    "113": {
      "hook": "Honest doubt wey person bring come to Jesus go find honest answer.",
      "body": "John di Baptist — di man wey Jesus call \"di greatest wey woman born\" (Matthew 11:11) — send message from prison: \"You be di one wey go come, or make we expect another person?\" (Luke 7:19). Di prophet wey baptize Jesus, wey see as Spirit come down like dove — dey ask whether Jesus be di real Messiah. Inside di darkness of prison cell, doubt come meet di greatest prophet.\n\nJesus no condemn John doubt. E answer am. E send back evidence — blind people dey see, lame people dey waka, deaf people dey hear, dead people dey rise — E no even ask John to get certainty before E answer di question. Di question meet evidence, e no meet rejection.\n\nThomas doubt di resurrection until e touch di wounds (John 20:27-28). Jesus appear to Thomas specifically and give am exactly wetin e need. E no comot Thomas from di disciples because of di doubt. E appear to di doubter. God no dey fear honest doubt. E dey meet am.",
      "repentance": "Bring your doubt come to Jesus, no run comot from Am. E fit handle your questions. E answer John from prison. E appear to Thomas. E go meet you for your uncertainty.",
      "prayer": "Lord, I get doubts. I dey fear to talk am, but I believe say You don already know. I dey bring dem come to You — I no dey run comot from You. Meet me for my uncertainty di way You meet Thomas. I believe; help my unbelief. Amen."
    },
    "114": {
      "hook": "Di war no be outside thing first. Na for between your two ears dem dey fight am.",
      "body": "2 Corinthians 10:4-5: \"Di weapons wey we dey use fight no be weapons of di world. Instead, dem get power from God to break down strongholds. We dey break down arguments and every proud thing wey dey rise up against di knowledge of God, we dey take captive every thought make e obey Christ.\" Strongholds. Arguments. Proud things. Every thought. Di spiritual battle na battle of ideas, stories, and di things wey you dey tell yourself.\n\nA stronghold for mind na pattern of thinking wey don enter deep well well until e feel like truth. \"God no love me.\" \"I go never change.\" \"Na so I just be.\" \"Nothing ever dey work for me.\" Dis ones no be observation — na strongholds. And power from God dey available against dem.\n\nRomans 12:2: \"No conform to di pattern of dis world, but make dem transform you through di renewing of your mind.\" Di transformation dey start for di mind. Di renewing no be positive thinking exercise — na di systematic way of replacing false stories with di truth of God Word. Every thought wey dey contradict wetin God talk about you — dem go take dat thought captive.",
      "repentance": "Identify di strongholds — di patterns of thinking wey don dey run your life. Take dem captive. Put dem against di truth of God Word. Start di renewing of your mind today.",
      "prayer": "Lord, I dey identify di strongholds for my mind today. I dey take dem captive for di name of Jesus. I dey replace dem with wetin You talk. I dey start di renewing of my mind — no be with positive thinking, but with di truth of Your Word. Transform me. Amen."
    },
    "115": {
      "hook": "Elijah beg God make E end im life. God send angel come feed am instead.",
      "body": "1 Kings 19 na di most honest account of spiritual depression for Scripture. Elijah just call fire from heaven come Mount Carmel. E don stand against four hundred and fifty prophets. Then: \"E waka enter wilderness, one day journey, e come sidon under one broom tree, e pray say make e die, e talk say, 'E don do; now, LORD, take my life'\" (1 Kings 19:4). From di highest spiritual level go di deepest suicidal despair within few days.\n\nGod response to Elijah depression get plenty sense for how e practical: \"Angel touch am, e tell am, 'Wake up, chop.'\" Food and rest — before di theological conversation. Then food and rest again. Then \"di journey plenty too much for you.\" God address di physical reality before di spiritual one. E no rebuke Elijah for im despair. E feed am.\n\nThen di still small voice — di gentle, quiet word — for di cave for Horeb (1 Kings 19:12). E no be di earthquake, e no be di fire, e no be di drama. Di gentle voice of God dey talk to prophet wey tire finish. God meet Elijah where e dey — no be where e suppose dey — and bring am back.",
      "repentance": "If you dey di place wey Elijah dey, God no far from you. E no dey rebuke people wey tire. E dey feed dem. Come to Am for your tiredness receive im care.",
      "prayer": "Lord, e don do. I be like Elijah under di tree. I no dey perform strength wey I no get. I dey come to You for dis tiredness. Feed me. Make I rest. And when I ready — talk for di still small voice. I go listen. Amen."
    }
  }
};

if (typeof mergeTractsI18n === 'function') mergeTractsI18n(TRACTS_I18N_STRUGGLE_P1);