// ==========================================================
// GOSPEL TRACTS i18n — STRUGGLE category, Part 3 of 3 (tracts 137,152,163,176,188)
// Translated into all 8 languages. Merge with base GOSPEL_TRACTS data
// (id, category, color, title, verses stay the same across languages —
// only hook/body/repentance/prayer prose changes per language).
// ==========================================================
const TRACTS_I18N_STRUGGLE_P3 = {
  "en": {
    "137": {
      "hook": "A mustard seed does not apologise for not being an oak tree yet.",
      "body": "Matthew 17:20: \"Truly I tell you, if you have faith as small as a mustard seed, you can say to this mountain, 'Move from here to there,' and it will move. Nothing will be impossible for you.\" The mustard seed is the smallest of seeds. Jesus chose it deliberately. He was not setting a high bar. He was setting the lowest possible bar — and saying that is enough.\n\nThe disciples had just failed to cast out a demon and asked why. The answer was not \"you needed more power\" or \"you needed more gifts.\" It was faith the size of a mustard seed. Small faith in the right direction, directed at the right Person, is infinitely more powerful than large confidence in the wrong thing.\n\nThe father of the demon-possessed boy brought both the need and the honest confession in the same prayer: \"I do believe; help me overcome my unbelief!\" (Mark 9:24). Jesus healed the boy. The prayer was accepted. The small, honest, mixed faith was sufficient. Your faith does not have to be mountain-sized to move mountains. It has to be directed at the One who moves them.",
      "repentance": "Stop waiting until your faith feels large enough. Bring the small faith you have. Direct it at the right Person. It is enough.",
      "prayer": "Lord, I bring the faith I have — small as a mustard seed, mixed with doubt. I direct it at You. Not at my own confidence, not at my feeling of spiritual strength — at You. Move what needs to be moved. My faith is small. You are not. Amen."
    },
    "152": {
      "hook": "The same mercy that covered the first failure covers the hundredth.",
      "body": "Proverbs 24:16: \"For though the righteous fall seven times, they rise again, but the wicked stumble when calamity strikes.\" Seven times. The righteous — not the sinless, but those who have been made righteous in Christ — fall seven times. And rise seven times. The defining characteristic is not the falling. It is the rising. The righteous are defined by what they do after the fall.\n\nMicah 7:8: \"Do not gloat over me, my enemy! Though I have fallen, I will rise. Though I sit in darkness, the LORD will be my light.\" The enemy's primary weapon against repeated failure is the whisper: you will never change, God has given up on you, this is just who you are. This is a lie specifically designed to prevent the rising.\n\nLamentations 3:22-23: \"Because of the LORD's great love we are not consumed, for his compassions never fail. They are new every morning.\" New every morning. The mercy available today is not diminished by how much was needed yesterday. The supply is not depleted by demand. It is renewed. The same mercy available at the first failure is available after the hundredth. Get up.",
      "repentance": "You have failed again. That is not the end of the sentence. Get up. Receive the mercy that is new this morning. Confess specifically. Receive completely. Rise again.",
      "prayer": "Lord, I have failed again. I confess specifically what I did. I receive the mercy that is new this morning. I am righteous in Christ — so I rise. I get up again. Thank You for mercy that does not run out. Amen."
    },
    "163": {
      "hook": "Jesus dealt with shame at the cross. It has no legal claim on you.",
      "body": "Hebrews 12:2: Jesus endured the cross \"scorning its shame.\" Scorning — despising, treating with contempt, refusing to be affected by. The cross was designed to produce maximum shame — public exposure, criminal association, humiliation. Jesus scorned it. He did not merely endure the shame. He refused to be defined by it.\n\nIsaiah 53:4-5: \"Surely he took up our pain and bore our suffering...he was pierced for our transgressions...by his wounds we are healed.\" He bore our shame — the exposure, the guilt, the sense of permanent unworthiness. He took it into Himself so that it would have no further claim on those who belong to Him.\n\nRomans 10:11: \"Anyone who believes in him will never be put to shame.\" Never. Not \"will experience less shame.\" Will never be put to shame. The verdict of the cross is that shame has no authority over those who are in Christ. Not because the wrong things were not done. Because the One who bore them has declared them done.",
      "repentance": "Shame that has been covering you has no legal authority over you in Christ. Bring it to the cross today and let it be absorbed by the One who scorned shame on your behalf.",
      "prayer": "Lord Jesus, I bring my shame to the cross today — the things I have done, the things done to me. You scorned shame. You bore mine. I receive Your declaration: I will never be put to shame. I am covered. I am free. I walk out from under the shame today. Amen."
    },
    "176": {
      "hook": "God does not wait until you are fixed to use you. He uses the breaking.",
      "body": "2 Corinthians 4:7-10: \"But we have this treasure in jars of clay to show that this all-surpassing power is from God and not from us. We are hard pressed on every side, but not crushed; perplexed, but not in despair; persecuted, but not abandoned; struck down, but not destroyed.\" Jars of clay. Common, breakable, ordinary. And containing the treasure of the gospel. The container's fragility is not accidental. It is intentional — it makes the power inside undeniable.\n\nGideon was hiding in a wine press when the angel called him \"mighty warrior\" (Judges 6:11-12). He was not yet mighty. He was afraid. The name was prophetic, not descriptive. God called what was not as though it were — and then made it so. God's calling precedes God's equipping. The person He calls is not the finished product. They are the raw material.\n\nThe cracks in the jar of clay are not evidence that God made a mistake. They are the spaces through which His light gets out. Your brokenness is not a barrier to your usefulness. In the hands of the God who specialises in using the broken, it is the very thing that makes you most useful.",
      "repentance": "Stop waiting until you are whole to offer yourself to God. Come broken. The treasure can only be seen through the cracks. What feels like your greatest limitation may be God's greatest point of access.",
      "prayer": "Lord, I come broken. I stop pretending I am whole enough to be useful. I offer You the jar of clay — cracked, ordinary, fragile. Let Your treasure shine through the cracks. Use what is broken. Use what others dismissed. The power will be obviously Yours. Amen."
    },
    "188": {
      "hook": "There are battles that require the body of Christ. You cannot win them solo.",
      "body": "Exodus 17:11-12: \"As long as Moses held up his hands, the Israelites were winning, but whenever he lowered his hands, the Amalekites were winning. When Moses' hands grew tired, they took a stone and put it under him and he sat on it. Aaron and Hur held his hands up — one on one side, one on the other — so that his hands remained steady till sunset.\" Moses could not hold his hands up alone. He needed Aaron and Hur. The victory required the body acting together.\n\nEcclesiastes 4:9-10: \"Two are better than one, because they have a good return for their labour: If either of them falls down, one can help the other up. But pity anyone who falls and has no one to help them up!\" God designed human beings for community. The battle that you are losing alone is often the battle that the body of Christ is equipped to help you win.\n\nGalatians 6:2: \"Carry each other's burdens, and in this way you will fulfil the law of Christ.\" The burden you have been carrying alone is not meant to be carried alone. The law of Christ is mutual burden-bearing — the community holding up the arms of the one who is faltering.",
      "repentance": "Who can hold up your arms in the battle you are losing alone? Reach out to the Aaron and Hur God has placed in your life. The pride that keeps you isolated is costing you victories that community would win.",
      "prayer": "Lord, I acknowledge that I have been fighting alone what I was not meant to fight alone. Give me the humility to reach out. Help me find the Aaron and Hur You have placed in my life. Let me receive the help that makes the victory possible. Amen."
    }
  },
  "fr": {
    "137": {
      "hook": "Une graine de moutarde ne s'excuse pas de ne pas encore être un chêne.",
      "body": "Matthieu 17.20 : « Je vous le dis en vérité, si vous aviez de la foi comme un grain de sénevé, vous diriez à cette montagne : Transporte-toi d'ici là, et elle se transporterait ; rien ne vous serait impossible. » Le grain de sénevé est la plus petite des semences. Jésus l'a choisi délibérément. Il ne fixait pas une barre haute. Il fixait la barre la plus basse possible — et disait que cela suffit.\n\nLes disciples venaient d'échouer à chasser un démon et demandèrent pourquoi. La réponse ne fut pas « vous aviez besoin de plus de puissance » ni « vous aviez besoin de plus de dons ». C'était une foi de la taille d'un grain de sénevé. Une petite foi dans la bonne direction, dirigée vers la bonne Personne, est infiniment plus puissante qu'une grande confiance placée dans la mauvaise chose.\n\nLe père de l'enfant possédé par un démon apporta à la fois le besoin et la confession honnête dans la même prière : « Je crois ! viens au secours de mon incrédulité ! » (Marc 9.24). Jésus guérit l'enfant. La prière fut acceptée. La foi petite, honnête et mêlée de doute fut suffisante. Ta foi n'a pas besoin d'être de la taille d'une montagne pour déplacer des montagnes. Elle doit être dirigée vers Celui qui les déplace.",
      "repentance": "Arrête d'attendre que ta foi te semble assez grande. Apporte la petite foi que tu as. Dirige-la vers la bonne Personne. Cela suffit.",
      "prayer": "Seigneur, j'apporte la foi que j'ai — petite comme un grain de sénevé, mêlée de doute. Je la dirige vers Toi. Pas vers ma propre confiance, pas vers mon sentiment de force spirituelle — vers Toi. Déplace ce qui doit être déplacé. Ma foi est petite. Toi, Tu ne l'es pas. Amen."
    },
    "152": {
      "hook": "La même miséricorde qui a couvert le premier échec couvre le centième.",
      "body": "Proverbes 24.16 : « Car sept fois le juste tombe, et il se relève, mais les méchants sont précipités dans le malheur. » Sept fois. Le juste — non pas le sans-péché, mais celui qui a été rendu juste en Christ — tombe sept fois. Et se relève sept fois. Ce qui le caractérise n'est pas la chute. C'est le relèvement. Le juste est défini par ce qu'il fait après la chute.\n\nMichée 7.8 : « Ne te réjouis pas à mon sujet, mon ennemie ! Si je suis tombée, je me relèverai ; si je suis assise dans les ténèbres, l'Éternel sera ma lumière. » L'arme principale de l'ennemi contre l'échec répété est le murmure : tu ne changeras jamais, Dieu a abandonné sur toi, c'est simplement qui tu es. C'est un mensonge conçu spécifiquement pour empêcher le relèvement.\n\nLamentations 3.22-23 : « Les bontés de l'Éternel ne sont pas épuisées, ses compassions ne sont pas à leur terme ; elles se renouvellent chaque matin. » Nouvelles chaque matin. La miséricorde disponible aujourd'hui n'est pas diminuée par ce qui a été nécessaire hier. La réserve n'est pas épuisée par la demande. Elle est renouvelée. La même miséricorde disponible au premier échec est disponible après le centième. Relève-toi.",
      "repentance": "Tu as encore échoué. Ce n'est pas la fin de la phrase. Relève-toi. Reçois la miséricorde qui est nouvelle ce matin. Confesse spécifiquement. Reçois complètement. Relève-toi à nouveau.",
      "prayer": "Seigneur, j'ai encore échoué. Je confesse spécifiquement ce que j'ai fait. Je reçois la miséricorde qui est nouvelle ce matin. Je suis juste en Christ — donc je me relève. Je me relève encore. Merci pour une miséricorde qui ne s'épuise jamais. Amen."
    },
    "163": {
      "hook": "Jésus a réglé la question de la honte à la croix. Elle n'a aucune revendication légale sur toi.",
      "body": "Hébreux 12.2 : Jésus a enduré la croix « en méprisant la honte ». Mépriser — dédaigner, traiter avec mépris, refuser d'en être affecté. La croix était conçue pour produire une honte maximale — exposition publique, association criminelle, humiliation. Jésus l'a méprisée. Il n'a pas simplement enduré la honte. Il a refusé d'en être défini.\n\nÉsaïe 53.4-5 : « Certainement, ce sont nos souffrances qu'il a portées, c'est de nos douleurs qu'il s'est chargé... il était transpercé à cause de nos péchés... c'est par ses meurtrissures que nous sommes guéris. » Il a porté notre honte — l'exposition, la culpabilité, le sentiment d'indignité permanente. Il l'a prise en Lui-même afin qu'elle n'ait plus aucune emprise sur ceux qui Lui appartiennent.\n\nRomains 10.11 : « Quiconque croit en lui ne sera point confus. » Jamais. Pas « éprouvera moins de honte ». Ne sera jamais confus. Le verdict de la croix est que la honte n'a aucune autorité sur ceux qui sont en Christ. Non pas parce que les mauvaises choses n'ont pas été faites. Parce que Celui qui les a portées les a déclarées faites.",
      "repentance": "La honte qui te couvrait n'a aucune autorité légale sur toi en Christ. Apporte-la à la croix aujourd'hui et laisse-la être absorbée par Celui qui a méprisé la honte à ta place.",
      "prayer": "Seigneur Jésus, j'apporte ma honte à la croix aujourd'hui — les choses que j'ai faites, les choses qu'on m'a faites. Tu as méprisé la honte. Tu as porté la mienne. Je reçois Ta déclaration : je ne serai jamais confus. Je suis couvert. Je suis libre. Je sors de dessous la honte aujourd'hui. Amen."
    },
    "176": {
      "hook": "Dieu n'attend pas que tu sois réparé pour t'utiliser. Il utilise la brisure.",
      "body": "2 Corinthiens 4.7-10 : « Nous portons ce trésor dans des vases de terre, afin que cette grande puissance soit attribuée à Dieu, et non pas à nous. Nous sommes pressés de toute manière, mais non réduits à l'extrémité; dans la détresse, mais non dans le désespoir; persécutés, mais non abandonnés; abattus, mais non perdus. » Des vases de terre. Communs, cassables, ordinaires. Et contenant le trésor de l'évangile. La fragilité du contenant n'est pas accidentelle. Elle est intentionnelle — elle rend la puissance intérieure indéniable.\n\nGédéon se cachait dans un pressoir lorsque l'ange l'appela « vaillant héros » (Juges 6.11-12). Il n'était pas encore vaillant. Il avait peur. Le nom était prophétique, non descriptif. Dieu a appelé ce qui n'était pas comme si c'était — et l'a ensuite rendu tel. L'appel de Dieu précède l'équipement de Dieu. La personne qu'Il appelle n'est pas le produit fini. C'est la matière première.\n\nLes fissures dans le vase de terre ne sont pas la preuve que Dieu a fait une erreur. Ce sont les espaces par lesquels Sa lumière sort. Ta brisure n'est pas un obstacle à ton utilité. Entre les mains du Dieu qui se spécialise dans l'utilisation de ce qui est brisé, c'est précisément ce qui te rend le plus utile.",
      "repentance": "Arrête d'attendre d'être entier pour t'offrir à Dieu. Viens brisé. Le trésor ne peut être vu qu'à travers les fissures. Ce qui te semble être ta plus grande limitation pourrait être le plus grand point d'accès de Dieu.",
      "prayer": "Seigneur, je viens brisé. J'arrête de prétendre être assez entier pour être utile. Je T'offre le vase de terre — fissuré, ordinaire, fragile. Que Ton trésor brille à travers les fissures. Utilise ce qui est brisé. Utilise ce que d'autres ont rejeté. La puissance sera manifestement Tienne. Amen."
    },
    "188": {
      "hook": "Il y a des batailles qui nécessitent le corps de Christ. Tu ne peux pas les gagner seul.",
      "body": "Exode 17.11-12 : « Lorsque Moïse élevait sa main, Israël était le plus fort; et lorsqu'il baissait sa main, Amalek était le plus fort. Les mains de Moïse étant fatiguées, ils prirent une pierre qu'ils placèrent sous lui, et il s'assit dessus; Aaron et Hur soutenaient ses mains, l'un d'un côté, l'autre de l'autre; et ses mains restèrent fermes jusqu'au coucher du soleil. » Moïse ne pouvait pas tenir ses mains levées seul. Il avait besoin d'Aaron et de Hur. La victoire exigeait que le corps agisse ensemble.\n\nEcclésiaste 4.9-10 : « Deux valent mieux qu'un, parce qu'ils retirent un bon salaire de leur travail. Car, s'ils tombent, l'un relève son compagnon; mais malheur à celui qui est seul et qui tombe, sans avoir un second pour le relever! » Dieu a conçu les êtres humains pour la communauté. La bataille que tu perds seul est souvent la bataille que le corps de Christ est équipé pour t'aider à gagner.\n\nGalates 6.2 : « Portez les fardeaux les uns des autres, et vous accomplirez ainsi la loi de Christ. » Le fardeau que tu portes seul n'est pas destiné à être porté seul. La loi de Christ est le port mutuel des fardeaux — la communauté soutenant les bras de celui qui faiblit.",
      "repentance": "Qui peut soutenir tes bras dans la bataille que tu perds seul ? Tends la main vers l'Aaron et le Hur que Dieu a placés dans ta vie. L'orgueil qui te maintient isolé te coûte des victoires que la communauté remporterait.",
      "prayer": "Seigneur, je reconnais que j'ai combattu seul ce qui n'était pas destiné à être combattu seul. Donne-moi l'humilité de tendre la main. Aide-moi à trouver l'Aaron et le Hur que Tu as placés dans ma vie. Que je reçoive l'aide qui rend la victoire possible. Amen."
    }
  },
  "sw": {
    "137": {
      "hook": "Punje ya haradali haiombi radhi kwa kutokuwa mti wa mwaloni bado.",
      "body": "Mathayo 17:20: \"Amin, nawaambia, mkiwa na imani kiasi cha chembe ya haradali, mtauambia mlima huu, Ondoka hapa uende kule, nao utaondoka; wala halitakuwako neno lisilowezekana kwenu.\" Chembe ya haradali ni ndogo kuliko mbegu zote. Yesu aliichagua kwa makusudi. Hakuweka kiwango cha juu. Aliweka kiwango cha chini kabisa kinachowezekana — na kusema hicho kinatosha.\n\nWanafunzi walikuwa wamekwisha shindwa kutoa pepo na waliuliza sababu. Jibu halikuwa \"mlihitaji nguvu zaidi\" au \"mlihitaji vipawa zaidi.\" Ilikuwa imani ya ukubwa wa chembe ya haradali. Imani ndogo katika mwelekeo sahihi, ikielekezwa kwa Mtu sahihi, ina nguvu zaidi isiyo na kikomo kuliko imani kubwa iliyowekwa kwenye kitu kibaya.\n\nBaba wa mtoto aliyepagawa na pepo aliileta hitaji na ungamo la uaminifu katika ombi lile lile: \"Naamini; unisaidie kutokuamini kwangu!\" (Marko 9:24). Yesu alimponya mtoto. Ombi lilikubaliwa. Imani ndogo, ya uaminifu, iliyochanganyika na shaka ilitosha. Imani yako haihitaji kuwa kubwa kama mlima ili kuhamisha milima. Inahitaji kuelekezwa kwa Yule anayeihamisha.",
      "repentance": "Acha kusubiri mpaka imani yako ihisi kuwa kubwa vya kutosha. Leta imani ndogo uliyo nayo. Ielekeze kwa Mtu sahihi. Inatosha.",
      "prayer": "Bwana, ninaleta imani niliyo nayo — ndogo kama chembe ya haradali, iliyochanganyika na shaka. Ninaielekeza Kwako. Si kwa imani yangu mwenyewe, si kwa hisia zangu za nguvu za kiroho — Kwako. Hamisha kile kinachohitaji kuhamishwa. Imani yangu ni ndogo. Wewe sivyo. Amina."
    },
    "152": {
      "hook": "Rehema ile ile iliyofunika kushindwa kwa mara ya kwanza inafunika ya mia.",
      "body": "Mithali 24:16: \"Kwa maana mwenye haki huanguka mara saba, akaondoka tena; bali wabaya hujikwaa katika msiba.\" Mara saba. Mwenye haki — si asiye na dhambi, bali yule aliyefanywa mwenye haki ndani ya Kristo — huanguka mara saba. Na kuinuka mara saba. Sifa ya kutambulisha si kuanguka. Ni kuinuka. Wenye haki wanatambulishwa na wanachofanya baada ya kuanguka.\n\nMika 7:8: \"Usinifurahie, ewe adui yangu; nijapoanguka, nitainuka; nijapoketi gizani, Bwana atakuwa nuru yangu.\" Silaha kuu ya adui dhidi ya kushindwa mara kwa mara ni kunong'ona: hutabadilika kamwe, Mungu amekukatisha tamaa, huyu ndiye wewe. Hii ni uongo uliobuniwa mahususi kuzuia kuinuka.\n\nMaombolezo 3:22-23: \"Kwa sababu ya fadhili za Bwana hatuangamii, kwa kuwa huruma zake hazikomi. Ni mpya kila asubuhi.\" Mpya kila asubuhi. Rehema inayopatikana leo haipunguzwi na kiasi kilichohitajika jana. Ugavi hauishi kwa mahitaji. Unafanywa upya. Rehema ile ile iliyopatikana kushindwa kwa mara ya kwanza inapatikana baada ya mia. Inuka.",
      "repentance": "Umeshindwa tena. Hiyo si mwisho wa sentensi. Inuka. Pokea rehema iliyo mpya asubuhi hii. Ungama mahususi. Pokea kikamilifu. Inuka tena.",
      "prayer": "Bwana, nimeshindwa tena. Ninaungama mahususi nilichofanya. Ninapokea rehema iliyo mpya asubuhi hii. Mimi ni mwenye haki katika Kristo — hivyo ninainuka. Ninainuka tena. Asante kwa rehema isiyoisha. Amina."
    },
    "163": {
      "hook": "Yesu alishughulikia aibu msalabani. Haina haki ya kisheria juu yako.",
      "body": "Waebrania 12:2: Yesu alivumilia msalaba \"akidharau aibu yake.\" Kudharau — kuchukia, kutendea kwa dharau, kukataa kuathiriwa nayo. Msalaba ulibuniwa kuzalisha aibu ya juu zaidi — kuonyeshwa hadharani, kuhusishwa na uhalifu, kudhalilishwa. Yesu aliidharau. Hakuvumilia tu aibu. Alikataa kutambulishwa nayo.\n\nIsaya 53:4-5: \"Hakika ameyachukua masikitiko yetu, amejitwika huzuni zetu...alijeruhiwa kwa makosa yetu...na kwa mapigo yake sisi tumepona.\" Alibeba aibu yetu — kufichuliwa, hatia, hisia ya kutostahili kudumu. Aliichukua ndani Yake ili isiwe na haki tena juu ya wale walio Wake.\n\nWarumi 10:11: \"Kila amwaminiye hatatahayarika kamwe.\" Kamwe. Si \"atapata aibu kidogo.\" Hatatahayarika kamwe. Uamuzi wa msalabani ni kwamba aibu haina mamlaka juu ya wale walio ndani ya Kristo. Si kwa sababu mambo mabaya hayakufanywa. Kwa sababu Yule aliyeyabeba ametangaza yamekwisha.",
      "repentance": "Aibu iliyokuwa ikikufunika haina mamlaka ya kisheria juu yako ndani ya Kristo. Ilete msalabani leo iachwe ifyonzwe na Yule aliyedharau aibu kwa niaba yako.",
      "prayer": "Bwana Yesu, ninaleta aibu yangu msalabani leo — mambo niliyofanya, mambo yaliyofanywa kwangu. Ulidharau aibu. Ulibeba yangu. Ninapokea tangazo Lako: sitatahayarika kamwe. Nimefunikwa. Niko huru. Ninatoka chini ya aibu leo. Amina."
    },
    "176": {
      "hook": "Mungu hasubiri mpaka umerekebishwa ndipo akutumie. Anatumia uvunjifu.",
      "body": "2 Wakorintho 4:7-10: \"Lakini tunao hazina hii katika vyombo vya udongo, ili ubora wa uwezo huu uwe wa Mungu, wala si wetu. Twateswa kwa kila namna, lakini hatuchakaziki; twaduwazwa, lakini hatuna wasiwasi; twaudhiwa, lakini hatuachwi; twaangushwa chini, lakini hatuangamizwi.\" Vyombo vya udongo. Vya kawaida, vinavyoweza kuvunjika, vya kawaida. Na vinavyobeba hazina ya injili. Udhaifu wa chombo si bahati mbaya. Ni wa makusudi — unafanya nguvu ya ndani isikanushike.\n\nGideoni alikuwa akijificha kwenye shinikizo la divai wakati malaika alipomwita \"shujaa hodari\" (Waamuzi 6:11-12). Hakuwa bado shujaa. Aliogopa. Jina hilo lilikuwa la kinabii, si la maelezo. Mungu aliita kile ambacho hakikuwa kama kwamba kilikuwa — kisha akakifanya kiwe hivyo. Wito wa Mungu unatangulia utoshelezaji wa Mungu. Mtu anayemwita si bidhaa iliyokamilika. Ni malighafi.\n\nNyufa katika chombo cha udongo si ushahidi kwamba Mungu alifanya kosa. Ni nafasi ambazo nuru Yake hupitia. Uvunjifu wako si kizuizi cha manufaa yako. Mikononi mwa Mungu anayebobea katika kutumia vilivyovunjika, ndicho kinachokufanya uwe na manufaa zaidi.",
      "repentance": "Acha kusubiri mpaka uwe mzima ili ujitoe kwa Mungu. Njoo ukiwa umevunjika. Hazina inaweza kuonekana tu kupitia nyufa. Kile kinachohisi kama kikwazo chako kikubwa kinaweza kuwa mlango mkubwa wa Mungu.",
      "prayer": "Bwana, ninakuja nikiwa nimevunjika. Ninaacha kujifanya nimekamilika vya kutosha kuwa na manufaa. Ninakutolea chombo cha udongo — kilichopasuka, cha kawaida, dhaifu. Acha hazina Yako iangaze kupitia nyufa. Tumia kilichovunjika. Tumia kile wengine walichokataa. Nguvu itaonekana ni Yako wazi. Amina."
    },
    "188": {
      "hook": "Kuna vita vinavyohitaji mwili wa Kristo. Huwezi kuvishinda peke yako.",
      "body": "Kutoka 17:11-12: \"Ikawa, alipoinua Musa mkono wake, Israeli walikuwa na nguvu, na alipoushusha mkono wake, Amaleki walikuwa na nguvu. Lakini mikono ya Musa ilikuwa mizito; wakatwaa jiwe, wakaliweka chini yake, akaketi juu yake; na Haruni na Huri walikuwa wakiitegemeza mikono yake, mmoja upande huu, na mwingine upande huu; hivyo mikono yake ikawa imara hata jua lilipokuchwa.\" Musa hakuweza kuinua mikono yake peke yake. Alihitaji Haruni na Huri. Ushindi ulihitaji mwili kutenda pamoja.\n\nMhubiri 4:9-10: \"Wawili ni afadhali kuliko mmoja, kwa maana wana thawabu njema kwa kazi yao. Kwa maana wakianguka, mmoja atamwinua mwenzake; lakini ole wake aangukaye, naye hana wa pili wa kumwinua!\" Mungu aliwaumba wanadamu kwa ajili ya jamii. Vita unavyoshindwa peke yako mara nyingi ni vita ambavyo mwili wa Kristo umeandaliwa kukusaidia kuvishinda.\n\nWagalatia 6:2: \"Bebeni mizigo ya mfano huu wa mnyororo, na hivyo mtaitimiza sheria ya Kristo.\" Mzigo uliokuwa ukibeba peke yako hukusudiwa kubebwa peke yako. Sheria ya Kristo ni kubebeana mizigo pamoja — jamii ikitegemeza mikono ya yule anayeyumba.",
      "repentance": "Ni nani anayeweza kutegemeza mikono yako katika vita unavyoshindwa peke yako? Wafikie Haruni na Huri ambao Mungu amewaweka katika maisha yako. Kiburi kinachokufanya ubaki peke yako kinakugharimu ushindi ambao jamii ingeushinda.",
      "prayer": "Bwana, ninakiri kwamba nimekuwa nikipigana peke yangu kile ambacho hakikukusudiwa kupiganwa peke yangu. Nipe unyenyekevu wa kufikia wengine. Nisaidie kupata Haruni na Huri uliowaweka katika maisha yangu. Niruhusu nipokee msaada unaofanya ushindi uwezekane. Amina."
    }
  },
  "ar": {
    "137": {
      "hook": "حبة الخردل لا تعتذر عن كونها ليست شجرة بلوط بعد.",
      "body": "متى ١٧: ٢٠: «الحق أقول لكم: لو كان لكم إيمان مثل حبة خردل لكنتم تقولون لهذا الجبل: انتقل من هنا إلى هناك فينتقل، ولا يكون شيء عاجزًا لديكم.» حبة الخردل هي أصغر البذور. اختارها يسوع عن قصد. لم يكن يضع سقفًا عاليًا. كان يضع أدنى سقف ممكن — وقال إن هذا يكفي.\n\nكان التلاميذ قد فشلوا للتو في إخراج شيطان وسألوا عن السبب. لم تكن الإجابة «كنتم بحاجة إلى قوة أكبر» أو «كنتم بحاجة إلى مواهب أكثر». كان إيمانًا بحجم حبة الخردل. إيمان صغير في الاتجاه الصحيح، موجّه نحو الشخص الصحيح، أقوى بلا نهاية من ثقة كبيرة موضوعة في الشيء الخاطئ.\n\nأحضر أبو الصبي الذي كان به شيطان الحاجة والاعتراف الصادق في الصلاة نفسها: «أنا أؤمن، فأعِن عدم إيماني!» (مرقس ٩: ٢٤). شفى يسوع الصبي. قُبلت الصلاة. كان الإيمان الصغير الصادق الممزوج بالشك كافيًا. لا يجب أن يكون إيمانك بحجم جبل لتحريك الجبال. يجب أن يكون موجّهًا نحو الذي يحركها.",
      "repentance": "توقف عن الانتظار حتى يبدو إيمانك كبيرًا بما فيه الكفاية. أحضر الإيمان الصغير الذي لديك. وجّهه نحو الشخص الصحيح. إنه يكفي.",
      "prayer": "يا رب، أحضر الإيمان الذي لدي — صغير كحبة خردل، ممزوج بالشك. أوجّهه نحوك. ليس نحو ثقتي الخاصة، ليس نحو شعوري بالقوة الروحية — بل نحوك. حرّك ما يحتاج إلى أن يُحرَّك. إيماني صغير. أنت لست كذلك. آمين."
    },
    "152": {
      "hook": "الرحمة ذاتها التي غطت الفشل الأول تغطي المئة.",
      "body": "أمثال ٢٤: ١٦: «لأن الصدّيق يسقط سبع مرات ويقوم، أما الأشرار فيعثرون في الشر.» سبع مرات. الصدّيق — ليس الذي بلا خطيئة، بل من صار بارًا في المسيح — يسقط سبع مرات. ويقوم سبع مرات. الصفة المميزة ليست السقوط. إنها القيام. يُعرَف الأبرار بما يفعلونه بعد السقوط.\n\nميخا ٧: ٨: «لا تشمتي بي يا عدوتي. إني سقطت، أقوم. إني جلست في الظلام، الرب نور لي.» السلاح الأساسي للعدو ضد الفشل المتكرر هو الهمس: لن تتغير أبدًا، الله تخلى عنك، هذا هو أنت فحسب. هذه كذبة مصممة خصيصًا لمنع القيام.\n\nمراثي ٣: ٢٢-٢٣: «من إحسانات الرب أننا لم نفنَ، لأن مراحمه لا تزول. هي جديدة كل صباح.» جديدة كل صباح. الرحمة المتاحة اليوم لا تنقص بمقدار ما احتيج إليه بالأمس. الإمداد لا ينضب بالطلب. إنه يتجدد. الرحمة ذاتها المتاحة عند الفشل الأول متاحة بعد المئة. قم.",
      "repentance": "لقد فشلت مرة أخرى. هذه ليست نهاية الجملة. قم. اقبل الرحمة الجديدة هذا الصباح. اعترف تحديدًا. اقبل تمامًا. قم مرة أخرى.",
      "prayer": "يا رب، لقد فشلت مرة أخرى. أعترف تحديدًا بما فعلت. أقبل الرحمة الجديدة هذا الصباح. أنا بار في المسيح — لذلك أقوم. أقوم مرة أخرى. أشكرك على رحمة لا تنضب. آمين."
    },
    "163": {
      "hook": "تعامل يسوع مع العار على الصليب. ليس له أي مطالبة قانونية عليك.",
      "body": "عبرانيين ١٢: ٢: احتمل يسوع الصليب «مستهينًا بالخزي». الاستهانة — الازدراء، المعاملة بازدراء، رفض التأثر. صُمم الصليب لإنتاج أقصى قدر من العار — التعرية العلنية، الارتباط بالجريمة، الإذلال. استهان به يسوع. لم يكتفِ باحتمال العار. رفض أن يُعرَّف به.\n\nإشعياء ٥٣: ٤-٥: «لكن أحزاننا حملها وأوجاعنا تحمّلها... وهو مجروح لأجل معاصينا... وبحبره شُفينا.» حمل عارنا — التعرية، الشعور بالذنب، الشعور الدائم بعدم الاستحقاق. أخذه في نفسه حتى لا يكون له مطالبة إضافية على أولئك الذين ينتمون إليه.\n\nرومية ١٠: ١١: «كل من يؤمن به لا يخزى.» أبدًا. ليس «سيختبر خزيًا أقل». لن يُخزى أبدًا. حكم الصليب هو أن العار ليس له سلطة على أولئك الذين هم في المسيح. ليس لأن الأشياء الخاطئة لم تُفعل. لأن الذي حملها أعلن أنها انتهت.",
      "repentance": "العار الذي كان يغطيك ليس له سلطة قانونية عليك في المسيح. أحضره إلى الصليب اليوم ودعه يُمتص من قبل الذي استهان بالعار نيابة عنك.",
      "prayer": "أيها الرب يسوع، أحضر عاري إلى الصليب اليوم — الأشياء التي فعلتها، الأشياء التي فُعلت بي. أنت استهنت بالعار. حملت عاري. أقبل إعلانك: لن أُخزى أبدًا. أنا مغطى. أنا حر. أخرج من تحت العار اليوم. آمين."
    },
    "176": {
      "hook": "الله لا ينتظر حتى تُصلَح ليستخدمك. إنه يستخدم الانكسار.",
      "body": "٢ كورنثوس ٤: ٧-١٠: «ولكن لنا هذا الكنز في أوانٍ خزفية ليكون فضل القوة للّه لا منا. مكتئبين في كل شيء ولكن غير متضايقين، متحيّرين ولكن غير يائسين، مضطهدين ولكن غير متروكين، مطروحين ولكن غير هالكين.» أوانٍ خزفية. عادية، قابلة للكسر، بسيطة. وتحتوي على كنز الإنجيل. هشاشة الوعاء ليست عرضية. إنها مقصودة — تجعل القوة الداخلية لا يمكن إنكارها.\n\nكان جدعون مختبئًا في معصرة الخمر عندما دعاه الملاك «جبار البأس» (قضاة ٦: ١١-١٢). لم يكن بعد جبارًا. كان خائفًا. كان الاسم نبويًا، لا وصفيًا. دعا الله ما لم يكن كأنه كائن — ثم جعله كذلك. دعوة الله تسبق تجهيز الله. الشخص الذي يدعوه ليس المنتج النهائي. إنه المادة الخام.\n\nالشقوق في الوعاء الخزفي ليست دليلاً على أن الله ارتكب خطأً. إنها المساحات التي يخرج منها نوره. كسرك ليس عائقًا أمام فائدتك. في يدي الإله المتخصص في استخدام المنكسرين، إنه بالضبط ما يجعلك الأكثر فائدة.",
      "repentance": "توقف عن الانتظار حتى تصبح كاملاً لتقدم نفسك لله. تعال منكسرًا. لا يمكن رؤية الكنز إلا من خلال الشقوق. ما يبدو أنه أكبر قيودك قد يكون أعظم نقطة وصول لله.",
      "prayer": "يا رب، آتي منكسرًا. أتوقف عن التظاهر بأنني كامل بما فيه الكفاية لأكون مفيدًا. أقدم لك الوعاء الخزفي — المشقق، العادي، الهش. دع كنزك يلمع عبر الشقوق. استخدم ما هو مكسور. استخدم ما رفضه الآخرون. ستكون القوة واضحة أنها لك. آمين."
    },
    "188": {
      "hook": "هناك معارك تتطلب جسد المسيح. لا يمكنك الفوز بها منفردًا.",
      "body": "خروج ١٧: ١١-١٢: «وكان اذا رفع موسى يده ان اسرائيل يغلب، واذا خفض يده ان عماليق يغلب. فاستثقلت يدا موسى فأخذا حجرا ووضعاه تحته فجلس عليه، ودعم هرون وحور يديه واحد من هنا وواحد من هناك، فكانت يداه ثابتتين الى غروب الشمس.» لم يستطع موسى أن يرفع يديه وحده. احتاج إلى هارون وحور. تطلب النصر أن يعمل الجسد معًا.\n\nالجامعة ٤: ٩-١٠: «الاثنان خير من الواحد لأن لهما أجرة صالحة عن تعبهما. لأنهما إن سقطا يقيم أحدهما رفيقه، ولكن ويل للواحد إذا سقط وليس ثانٍ يقيمه!» صمم الله البشر من أجل المجتمع. المعركة التي تخسرها وحدك غالبًا ما تكون المعركة التي جهّز جسد المسيح لمساعدتك على الفوز بها.\n\nغلاطية ٦: ٢: «احملوا بعضكم أثقال بعض، وهكذا تمّموا ناموس المسيح.» العبء الذي كنت تحمله وحدك لم يُقصد أن يُحمَل وحده. ناموس المسيح هو حمل الأثقال المتبادل — المجتمع يسند ذراعي من يترنح.",
      "repentance": "من يمكنه أن يسند ذراعيك في المعركة التي تخسرها وحدك؟ تواصل مع هارون وحور الذين وضعهما الله في حياتك. الكبرياء الذي يبقيك معزولاً يكلفك انتصارات كان المجتمع سيحققها.",
      "prayer": "يا رب، أعترف أنني كنت أحارب وحدي ما لم يُقصد أن أحاربه وحدي. أعطني التواضع للتواصل مع الآخرين. ساعدني في إيجاد هارون وحور الذين وضعتهما في حياتي. دعني أتلقى المساعدة التي تجعل النصر ممكنًا. آمين."
    }
  },
  "yo": {
    "137": {
      "hook": "Hóró músítádì kì í tọrọ àforíjì fún àìtí di igi óòkì.",
      "body": "Mátíù 17:20: \"Lóòótọ́ ni mo wí fún yín, bí ẹ̀yin bá ní ìgbàgbọ́ bí hóró músítádì, ẹ̀yin yóò wí fún òkè ńlá yìí pé, Ṣí kúrò níhìn-ín lọ sí ọ̀hún; yóò sì ṣí lọ; kò sì sí ohun tí kì yóò ṣeéṣe fún yín.\" Hóró músítádì ni hóró tó kéré jùlọ nínú àwọn hóró. Jésù yàn án mọ̀ọ́mọ̀. Kì í ṣe ìdíwọ̀n gíga ni Ó gbé kalẹ̀. Ìdíwọ̀n tó kéré jùlọ tí ó ṣeéṣe ni Ó gbé kalẹ̀ — Ó sì sọ pé ìyẹn tó.\n\nÀwọn ọmọ ẹ̀yìn ti kùnà láti lé ẹ̀mí èṣù jáde, wọ́n sì béèrè ìdí. Ìdáhùn náà kì í ṣe \"ẹ nílò agbára púpọ̀ sí i\" tàbí \"ẹ nílò ẹ̀bùn púpọ̀ sí i\". Ìgbàgbọ́ tí ó dà bí hóró músítádì ni. Ìgbàgbọ́ kékeré ní ọ̀nà tí ó tọ́, tí a dojú kọ Ẹni tí ó tọ́, lágbára ju ìgbẹ́kẹ̀lé ńlá tí a fi sí ohun tí kò tọ́ lọ.\n\nBàbá ọmọ tí ẹ̀mí èṣù ń dá lóró mú àìní àti ìjẹ́wọ́ olóòótọ́ wá sínú àdúrà kan náà: \"Mo gbàgbọ́; ràn mí lọ́wọ́ nínú àìgbàgbọ́ mi!\" (Máàkù 9:24). Jésù wo ọmọ náà sàn. A gba àdúrà náà. Ìgbàgbọ́ kékeré, olóòótọ́, tí ó dàpọ̀ mọ́ ìṣiyèméjì tó. Ìgbàgbọ́ rẹ kò ní láti dà bí òkè ńlá kí ó tó lè ṣí àwọn òkè ńlá. Ó ní láti dojú kọ Ẹni tí ń ṣí wọn.",
      "repentance": "Dáwọ́ dídúró dúró títí tí ìgbàgbọ́ rẹ yóò fi dà bí ẹni pé ó tóbi tó. Mú ìgbàgbọ́ kékeré tí o ní wá. Darí i sí Ẹni tí ó tọ́. Ó tó.",
      "prayer": "Olúwa, mo mú ìgbàgbọ́ tí mo ní wá — kékeré bí hóró músítádì, tí ó dàpọ̀ mọ́ ìṣiyèméjì. Mo darí i sí Ọ̀dọ̀ Rẹ. Kì í ṣe sí ìgbẹ́kẹ̀lé ara mi, kì í ṣe sí bí mo ṣe nímọ̀lára agbára tẹ̀mí — sí Ọ̀dọ̀ Rẹ ni. Ṣí ohun tí ó yẹ kí a ṣí. Ìgbàgbọ́ mi kéré. Ìwọ kò kéré. Àmín."
    },
    "152": {
      "hook": "Àánú kan náà tí ó bo ìkùnà kìíní ni ó bo ìkẹtàlélọ́gọ́rùn-ún.",
      "body": "Òwe 24:16: \"Nítorí olódodo ń ṣubú ní ìgbà méje, ó sì ń dìde padà; ṣùgbọ́n àwọn ẹni búburú ni a ó gbé rì nínú ibi.\" Ìgbà méje. Olódodo — kì í ṣe ẹni tí kò ní ẹ̀ṣẹ̀, ṣùgbọ́n ẹni tí a ti ṣe olódodo nínú Kristi — ń ṣubú ní ìgbà méje. Ó sì ń dìde ní ìgbà méje. Ìwà tí ó ṣe àpèjúwe rẹ̀ kì í ṣe ìṣubú. Ó jẹ́ ìdìde. Àwọn olódodo ni a ṣe àpèjúwe wọn nípa ohun tí wọ́n ń ṣe lẹ́yìn ìṣubú.\n\nMíkà 7:8: \"Má ṣe yọ̀ mí, ìwọ ọ̀tá mi; nígbà tí mo bá ṣubú, èmi yóò dìde; nígbà tí mo bá jókòó nínú òkùnkùn, OLÚWA yóò jẹ́ ìmọ́lẹ̀ mi.\" Ohun ìjà pàtàkì ọ̀tá lòdì sí ìkùnà tí ó ń ṣẹlẹ̀ léraléra ni ìsọ̀rọ̀ kẹ̀lẹ̀kẹ̀lẹ̀: o kì yóò yí padà láéláé, Ọlọ́run ti fi ọ́ sílẹ̀, èyí ni ẹni tí ìwọ jẹ́ gan-an. Èyí jẹ́ irọ́ tí a ṣe ní pàtàkì láti dí ìdìde náà lọ́wọ́.\n\nÌdárò 3:22-23: \"Nítorí àánú OLÚWA ni àwa kò fi ṣègbé, nítorí ìkẹ́ rẹ̀ kì í kùnà. Ó jẹ́ tuntun ní òwúrọ̀ kọ̀ọ̀kan.\" Tuntun ní òwúrọ̀ kọ̀ọ̀kan. Àánú tí ó wà lónìí kò dínkù nítorí iye tí a nílò lánàá. Ìpèsè náà kò tán nítorí ìbéèrè. A tún un ṣe. Àánú kan náà tí ó wà nígbà ìkùnà kìíní wà lẹ́yìn ìkẹtàlélọ́gọ́rùn-ún. Dìde.",
      "repentance": "O ti kùnà lẹ́ẹ̀kan sí i. Kì í ṣe òpin gbolóhùn náà. Dìde. Gba àánú tí ó jẹ́ tuntun ní òwúrọ̀ yìí. Jẹ́wọ́ ní pàtó. Gbà á ní kíkún. Dìde padà.",
      "prayer": "Olúwa, mo tún kùnà. Mo jẹ́wọ́ ní pàtó ohun tí mo ṣe. Mo gba àánú tí ó jẹ́ tuntun ní òwúrọ̀ yìí. Mo jẹ́ olódodo nínú Kristi — nítorí náà mo dìde. Mo tún dìde. Mo dúpẹ́ fún àánú tí kì í tán. Àmín."
    },
    "163": {
      "hook": "Jésù kojú ìtìjú ní àgbélébùú. Kò ní ẹ̀tọ́ òfin lórí rẹ.",
      "body": "Hébérù 12:2: Jésù farada àgbélébùú \"ó fojú kéré ìtìjú rẹ̀.\" Fífojúkéré — ìkọ̀sí, títọ́jú pẹ̀lú ẹ̀gàn, kíkọ̀ láti jẹ́ kí ó nípa lórí ẹni. A ṣe àgbélébùú láti mú ìtìjú tí ó pọ̀ jùlọ jáde — ìfarahàn ní gbangba, ìsopọ̀ pẹ̀lú ọ̀daràn, ìtìjú. Jésù fojú kéré e. Kì í ṣe pé ó farada ìtìjú náà lásán. Ó kọ̀ láti jẹ́ kí a fi ìtìjú náà ṣe àpèjúwe òun.\n\nÌsaáyà 53:4-5: \"Nítòótọ́ àìsàn wa ni ó ru, ìbànújẹ́ wa ni ó gbé...a gún un fún ìrékọjá wa...pẹ̀lú ọgbẹ́ rẹ̀ ni a mú wa láradá.\" Ó ru ìtìjú wa — ìfarahàn, ẹ̀bi, ìmọ̀lára àìyẹ tí ó wà títí láé. Ó mú u wọ inú ara Rẹ̀ kí ó má bàa ní ẹ̀tọ́ mọ́ lórí àwọn tí ó jẹ́ ti Rẹ̀.\n\nRómù 10:11: \"Ẹnikẹ́ni tí ó bá gbàgbọ́ nínú Rẹ̀ ni a kì yóò dójútì láéláé.\" Láéláé. Kì í ṣe \"yóò ní ìrírí ìtìjú kékeré.\" A kì yóò dójú tì í láéláé. Ìdájọ́ àgbélébùú ni pé ìtìjú kò ní ọlá àṣẹ lórí àwọn tí ó wà nínú Kristi. Kì í ṣe nítorí pé a kò ṣe àwọn ohun tí kò tọ́. Nítorí pé Ẹni tí ó ru wọn ti kéde pé wọ́n ti parí.",
      "repentance": "Ìtìjú tí ó ti ń bò ọ́ mọ́lẹ̀ kò ní ọlá àṣẹ òfin lórí rẹ nínú Kristi. Mú un wá sí àgbélébùú lónìí kí ó sì jẹ́ kí Ẹni tí ó fojú kéré ìtìjú fún ọ mu gbogbo rẹ̀.",
      "prayer": "Olúwa Jésù, mo mú ìtìjú mi wá sí àgbélébùú lónìí — àwọn ohun tí mo ti ṣe, àwọn ohun tí a ti ṣe sí mi. O fojú kéré ìtìjú. O ru tèmi. Mo gba ìkéde Rẹ: A kì yóò dójú tì mí láéláé. A ti bò mí mọ́lẹ̀. Òmìnira ni mí. Mo rìn jáde kúrò lábẹ́ ìtìjú lónìí. Àmín."
    },
    "176": {
      "hook": "Ọlọ́run kì í dúró títí tí a fi tún ọ ṣe kí ó tó lo ọ. Ó ń lo fífọ́.",
      "body": "2 Kọ́ríntì 4:7-10: \"Ṣùgbọ́n àwa ní ìṣúra yìí nínú àwo amọ̀, kí ìpọ̀jù agbára náà lè jẹ́ ti Ọlọ́run, kì í ṣe tiwa. A pọ́n wa lójú ní ọ̀nà gbogbo, ṣùgbọ́n a kò há wa mọ́; a dààmú wa, ṣùgbọ́n a kò sọ̀rètí nù; a ṣe inúnibíni sí wa, ṣùgbọ́n a kò kọ̀ wá sílẹ̀; a bì wá ṣubú, ṣùgbọ́n a kò pa wá run.\" Àwo amọ̀. Ojoojúmọ́, tí ń fọ́, lásán. Tí ó sì ní ìṣúra ìhìnrere nínú. Àìlera àwo náà kì í ṣe àìròtẹ́lẹ̀. Ó jẹ́ mọ̀ọ́mọ̀ — ó mú kí agbára inú rẹ̀ má lè ṣàì gbà á gbọ́.\n\nGídíónì ń fi ara pamọ́ sínú ìfúntí wáìnì nígbà tí áńgẹ́lì pè é ní \"akíkanjú jagunjagun\" (Àwọn Onídàájọ́ 6:11-12). Kò tíì jẹ́ akíkanjú. Ó ń bẹ̀rù. Orúkọ náà jẹ́ àsọtẹ́lẹ̀, kì í ṣe àpèjúwe. Ọlọ́run pe ohun tí kò sí bí ẹni pé ó wà — ó sì mú kí ó rí bẹ́ẹ̀. Ìpè Ọlọ́run ṣíwájú ìmúrasílẹ̀ Ọlọ́run. Ẹni tí Ó pè kì í ṣe ọjà tí ó parí. Wọ́n jẹ́ àwọn ohun èlò àkọ́kọ́.\n\nÀwọn ojú tí ó là nínú àwo amọ̀ kì í ṣe ẹ̀rí pé Ọlọ́run ṣe àṣìṣe. Wọ́n jẹ́ àyè tí ìmọ́lẹ̀ Rẹ̀ ń jáde gbà. Ìfọ́ rẹ kì í ṣe ìdíwọ́ fún ìwúlò rẹ. Ní ọwọ́ Ọlọ́run tí ó mọ̀ láti lo àwọn tí ó fọ́, ó jẹ́ ohun gan-an tí ó mú ọ wúlò jùlọ.",
      "repentance": "Dáwọ́ dídúró dúró títí tí ìwọ yóò fi pé kí o tó fi ara rẹ fún Ọlọ́run. Wá bí ẹni tí ó fọ́. Ìṣúra náà lè hàn nìkan nípasẹ̀ àwọn ojú tí ó là. Ohun tí ó dà bí ìdíwọ́ rẹ ńlá jùlọ lè jẹ́ ẹnu ọ̀nà ìwọlé Ọlọ́run tí ó tóbi jùlọ.",
      "prayer": "Olúwa, mo wá ní ẹni tí ó fọ́. Mo dáwọ́ dídibọ̀n pé mo pé tó láti wúlò dúró. Mo fi àwo amọ̀ fún Ọ — tí ó là, tí ó jẹ́ lásán, tí ó lẹ́rùn. Jẹ́ kí ìṣúra Rẹ tàn nípasẹ̀ àwọn ojú tí ó là. Lo ohun tí ó fọ́. Lo ohun tí àwọn ẹlòmíràn kọ̀. Agbára náà yóò hàn ní gbangba pé ti Rẹ ni. Àmín."
    },
    "188": {
      "hook": "Àwọn ogun kan wà tí wọ́n nílò ara Kristi. O kò lè ṣẹ́gun wọn ní ìkanwáà.",
      "body": "Ẹ́kísódù 17:11-12: \"Ó sì ṣe, nígbà tí Mósè bá gbé ọwọ́ rẹ̀ sókè, Ísírẹ́lì ṣẹ́gun; nígbà tí ó bá sì rẹ ọwọ́ rẹ̀ sílẹ̀, Ámálékì ṣẹ́gun. Ṣùgbọ́n ọwọ́ Mósè rẹ̀, wọ́n sì mú òkúta kan wá, wọ́n sì gbé e sí abẹ́ rẹ̀, ó sì jókòó lé e lórí; Áárónì àti Húrì sì fi ọwọ́ wọn tì í lẹ́yìn, ọ̀kan ní ìhà kan, ọ̀kan sì ní ìhà kejì; bẹ́ẹ̀ ni ọwọ́ rẹ̀ dúró ṣinṣin títí oòrùn fi wọ̀.\" Mósè kò lè gbé ọwọ́ rẹ̀ sókè fúnra rẹ̀. Ó nílò Áárónì àti Húrì. Ìṣẹ́gun náà nílò kí ara ṣe pọ̀.\n\nOníwàásù 4:9-10: \"Ẹnì méjì sàn ju ẹnìkan lọ; nítorí wọ́n ní èrè rere fún làálàá wọn. Nítorí bí wọ́n bá ṣubú, ẹnì kan yóò gbé ẹnì kejì dìde: ṣùgbọ́n ègbé ni fún ẹni tí ó dá dá bí ó bá ṣubú; nítorí kò ní ẹnì kejì láti gbé e dìde!\" Ọlọ́run ṣe ẹ̀dá ènìyàn fún àwùjọ. Ogun tí o ń pàdánù nínú fúnra rẹ ni ogun tí ara Kristi ti mú ìmúrasílẹ̀ láti ràn ọ́ lọ́wọ́ láti ṣẹ́gun.\n\nGálátíà 6:2: \"Ẹ máa ru ẹrù ara yín, bẹ́ẹ̀ ni kí ẹ̀yin lè mú òfin Kristi ṣẹ.\" Ẹrù tí o ti ń rù fúnra rẹ kò ní ète láti rù ní ìkanwáà. Òfin Kristi ni fífi ara ẹni ru ẹrù ara ẹnìkejì — àwùjọ ń tì apá ẹni tí ó ń dojú kọ ìṣubú lẹ́yìn.",
      "repentance": "Ta ni ó lè tì apá rẹ nínú ogun tí o ń pàdánù nínú fúnra rẹ? Kàn sí Áárónì àti Húrì tí Ọlọ́run ti fi sí ìgbésí ayé rẹ. Ìgbéraga tí ó jẹ́ kí o dá wà ń ná ọ ní ìṣẹ́gun tí àwùjọ ìbá ti ṣẹ́gun.",
      "prayer": "Olúwa, mo jẹ́wọ́ pé mo ti ń jà fúnra mi ohun tí kò ní ète láti jà ní ìkanwáà. Fún mi ní ìrẹ̀lẹ̀ láti kàn sí àwọn ẹlòmíràn. Ràn mí lọ́wọ́ láti rí Áárónì àti Húrì tí O ti fi sí ìgbésí ayé mi. Jẹ́ kí n gba ìrànlọ́wọ́ tí ó mú kí ìṣẹ́gun ṣeéṣe. Àmín."
    }
  },
  "ig": {
    "137": {
      "hook": "Mkpụrụ mustad anaghị arịọ mgbaghara maka na ọ bụghị osisi oak ka.",
      "body": "Matiu 17:20: \"N'ezie asị m unu, ọ bụrụ na unu nwere okwukwe dị ka mkpụrụ mustad, unu ga-asị ugwu a, Site ebe a gaa n'ebe ahụ; ọ ga-agakwa; ọ dịghịkwa ihe ga-esi ike n'aka unu.\" Mkpụrụ mustad bụ mkpụrụ kacha nta n'ime mkpụrụ niile. Jizọs họọrọ ya kpọmkwem. Ọ bụghị ọkwa dị elu ka O tọrọ ntọala. Ọ tọrọ ntọala kacha ala nwere ike ịdị — ma kwuo na nke ahụ ezuola.\n\nNdị na-eso ụzọ ya ka kariri ịchụpụ mmụọ ọjọọ ma jụọ ihe kpatara ya. Azịza ahụ abụghị \"unu chọrọ ike karịa\" ma ọ bụ \"unu chọrọ onyinye karịa.\" Ọ bụ okwukwe dị ka mkpụrụ mustad n'obosara ya. Okwukwe pere mpe n'ụzọ ziri ezi, chere ihu Onye ziri ezi, dị ike karịa ntụkwasị obi buru ibu e tinyere n'ihe na-ezighị ezi.\n\nNna nwata mmụọ ọjọọ na-esogbu wetara ma mkpa na nkwupụta n'ezi obi n'otu ekpere: \"Ekwenyere m; nyere m aka n'enweghị ekwenye m!\" (Mak 9:24). Jizọs gwọrọ nwata ahụ. A nabatara ekpere ahụ. Okwukwe dị nta, nke ezi obi, gwakọtara na obi abụọ ezuola. Okwukwe gị ekwesịghị ịdị ka ugwu iji kwagharịa ugwu nile. Ọ ga-echere ihu Onye na-akwagharị ha.",
      "repentance": "Kwụsị ichere ka okwukwe gị dị ukwuu zuru oke. Wetara okwukwe nta i nwere. Chee ya ihu Onye ziri ezi. Ọ ezuola.",
      "prayer": "Onyenwe anyị, ana m eweta okwukwe m nwere — nke dị nta dị ka mkpụrụ mustad, gwakọtara na obi abụọ. Ana m eche ya ihu Gị. Ọ bụghị n'ike aka m, ọ bụghị na mmetụta m nke ike ime mmụọ — Gị. Kwagharịa ihe kwesịrị ịkwagharị. Okwukwe m dị nta. Gị adịghị. Amen."
    },
    "152": {
      "hook": "Otu ebere ahụ kpuchiri ọdịda mbụ na-ekpuchi nke narị.",
      "body": "Ilu 24:16: \"N'ihi na onye ezi omume na-ada ugboro asaa, ọ na-ebiliteghachikwa; ma ndị ajọ omume na-asụ ngọngọ n'ime ọdachi.\" Ugboro asaa. Onye ezi omume — ọ bụghị onye na-emeghị mmehie, kama onye e mere ka ọ bụrụ ezi omume na Kraịst — na-ada ugboro asaa. Ma na-ebilite ugboro asaa. Àgwà na-akọwa ya abụghị ọdịda. Ọ bụ mbilite. A na-akọwa ndị ezi omume site n'ihe ha na-eme mgbe ha dara.\n\nMaịka 7:8: \"Aṅụrịla ọṅụ n'ihi m, gị onye iro m; ọ bụ ezie na m dara, m ga-ebili; ọ bụ ezie na m nọ n'ọchịchịrị, Onyenwe anyị ga-abụ ìhè m.\" Ngwa agha kachasị onye iro na-eji emegide ọdịda ugboro ugboro bụ ịsụ ntamu: ị gaghị agbanwe ma ọlị, Chineke ahapụla gị, nke a bụ naanị onye ị bụ. Nke a bụ okwu ụgha e chepụtara kpọmkwem ka o gbochie mbilite ahụ.\n\nAkwa Ozu 3:22-23: \"N'ihi ịhụnanya dị ukwuu nke Onyenwe anyị, anyị eribeghị; n'ihi na ọmiko ya adịghị agwụ. Ha bụ ọhụrụ n'ụtụtụ ọ bụla.\" Ọhụrụ n'ụtụtụ ọ bụla. Ebere dị taa adịghị ebelata site na ole ka a chọrọ ụnyaahụ. Ihe enyere adịghị agwụ agwụ site na ihe a chọrọ. A na-eme ka ọ bụrụ ọhụrụ. Otu ebere ahụ dị mgbe ọdịda mbụ dịkwa mgbe ọdịda narị. Bilie.",
      "repentance": "Ị dawo ọzọ. Nke ahụ abụghị njedebe nke ahịrịokwu ahụ. Bilie. Nabata ebere dị ọhụrụ ụtụtụ a. Kwupụta kpọmkwem. Nabata kpamkpam. Bilie ọzọ.",
      "prayer": "Onyenwe anyị, adawo m ọzọ. Ana m ekwupụta kpọmkwem ihe m mere. Ana m anabata ebere dị ọhụrụ ụtụtụ a. Abụ m onye ezi omume na Kraịst — ya mere ana m ebili. Ana m ebili ọzọ. Daalụ maka ebere na-adịghị agwụ agwụ. Amen."
    },
    "163": {
      "hook": "Jizọs kwụsịrị ihere na obe. Ihere enweghị ikike iwu n'ahụ gị.",
      "body": "Ndị Hibru 12:2: Jizọs nagidere obe \"leda ihere ya anya.\" Ledaanya — kpọasị, mesoo ya mkparị, jụ ka o mee ihe. E chepụtara obe iji mepụta oke ihere — igosipụta n'ihu ọha, njikọ na omume mpụ, imecha ihu. Jizọs ledara ya anya. Ọ bụghị nnọọ na o nagidere ihere ahụ. Ọ jụrụ ka a kọwaa ya site na ya.\n\nAịzaya 53:4-5: \"N'ezie, ọ bụ mgbu anyị ka O buuru, ọ bụkwa iru ụjụ anyị ka O buuru... e mapuru ya maka njehie anyị... site n'ọnya ya ka e ji gwọọ anyị.\" O buuru ihere anyị — igosipụta ihu ọha, ikpe ọmụma, mmetụta enweghị isi na-adịgide adịgide. O were ya baa n'ime onwe ya ka ọ ghara ịnwe ikike ọzọ n'ahụ ndị bụ nke ya.\n\nNdị Rom 10:11: \"Onye ọ bụla nke kwere na ya agaghị enwe ihere ọ bụla.\" Ọ dịghị mgbe. Ọ bụghị \"ga-enwe obere ihere.\" Agaghị enwe ihere ọ bụla mgbe ọ bụla. Ikpe nke obe bụ na ihere enweghị ikike n'ahụ ndị nọ na Kraịst. Ọ bụghị n'ihi na e meghị ihe ọjọọ. N'ihi na Onye buuru ha ekwuola na ha agwụla.",
      "repentance": "Ihere nke na-ekpuchi gị enweghị ikike iwu n'ahụ gị na Kraịst. Wetara ya n'obe taa ka Onye ledara ihere anya nʼihi gị rikọta ya.",
      "prayer": "Onyenwe m Jizọs, ana m eweta ihere m n'obe taa — ihe m mere, ihe e mere m. I ledara ihere anya. I buuru nke m. Ana m anabata nkwupụta Gị: agaghị m enwe ihere ọ bụla mgbe ọ bụla. E kpuchiri m. Enwere m onwe m. Ana m apụ n'okpuru ihere taa. Amen."
    },
    "176": {
      "hook": "Chineke anaghị eche ka e mezie gị tupu O jiri gị. O ji nkụjọ na-arụ ọrụ.",
      "body": "2 Ndị Kọrint 4:7-10: \"Ma anyị nwere akụ a n'ime ite ụrọ, ka ịdị ukwuu nke ike a si na Chineke bụrụghị nke anyị. A na-akpagbu anyị n'akụkụ ọ bụla, ma ọ dịghị amịpụta anyị; anyị nọ na mgbagwoju anya, ma anyị adịghị enweghị olileanya; a na-akpagbu anyị, ma a naghị ahapụ anyị; a na-akwada anyị, ma a naghị ala anyị n'iyi.\" Ite ụrọ. Nke a na-ahụkarị, nke nwere ike ịgbaji, nke nkịtị. Ma jide akụ nke ozi ọma. Adịghị ike nke ihe eji ejide ihe abụghị ihe na-emeghị onwe ya. Ọ bụ ihe e mere kpọmkwem — ọ na-eme ka ike dị n'ime ya ghara ịgbaghara.\n\nGidiọn nọ na-ezo onwe ya na ihe ịpịakọta mmanya mgbe mmụọ ozi kpọrọ ya \"dike agha\" (Ndị Ikpe 6:11-12). Ọ bụghị dike agha ka ọ dị. Ọ na-atụ ụjọ. Aha ahụ bụ amụma, ọ bụghị nkọwa. Chineke kpọrọ ihe na-adịghị ka ọ bụ ihe dị — mgbe ahụ mee ka ọ dịrị otu ahụ. Ọkpụkpọ Chineke na-ebute ihe ndozi Chineke. Onye ọ kpọrọ abụghị ngwaahịa e mechara. Ha bụ akụrụngwa ndị a na-ahazibeghị.\n\nỌwara dị n'ime ite ụrọ abụghị ihe akaebe na Chineke mere mmejọ. Ha bụ oghere ìhè ya na-esi na ha na-apụta. Nkụjọ gị abụghị ihe mgbochi nye baara gị uru. N'aka Chineke onye kachasị mara ime ka ihe gbajiri agbaji baa uru, ọ bụ okwu kpọmkwem nke na-eme ka ị baa uru karịa.",
      "repentance": "Kwụsị ichere ka i zuo oke tupu i nyefee onwe gị Chineke. Bịa n'ọnọdụ nkụjọ. Naanị site n'ọwara ka a pụrụ ịhụ akụ ahụ. Ihe dị ka oke mgbochi gị nwere ike ịbụ ebe ịba baa nke Chineke kachasị ukwuu.",
      "prayer": "Onyenwe anyị, ana m abịa n'ọnọdụ nkụjọ. Ana m akwụsị ime ka a ghara ịma na m zuru oke iji baa uru. Ana m enye Gị ite ụrọ — nke gbawara agbawa, nke nkịtị, nke na-adịghị ike. Kwe ka akụ Gị na-enwu site n'ọwara ndị ahụ. Jiri ihe gbajiri agbaji. Jiri ihe ndị ọzọ jụrụ. Ike ahụ ga-apụta ìhè na ọ bụ nke Gị. Amen."
    },
    "188": {
      "hook": "Ọ dị agha na-achọ ahụ Kraịst. Ị pụghị imeri ha naanị gị.",
      "body": "Ọpụpụ 17:11-12: \"O wee ruo, mgbe Mozis welitere aka ya elu, na Izrel na-emeri; ma mgbe o wedatara aka ya, na ndị Amalek na-emeri. Ma aka Mozis dara ike; ha wee were nkume tinye ya n'okpuru ya, ọ nọdụ ala na ya; Erọn na Hoa jidere aka ya elu, otu n'akụkụ nke a, nke ọzọ n'akụkụ nke ọzọ; aka ya wee guzosie ike ruo mgbe anyanwụ dara.\" Mozis apụghị iwelite aka ya elu naanị ya. Ọ chọrọ Erọn na Hoa. Mmeri ahụ chọrọ ka ahụ ahụ rụkọọ ọrụ ọnụ.\n\nEklisiastis 4:9-10: \"Mmadụ abụọ ka mma karịa otu; n'ihi na ha nwere ụgwọ ọrụ ọma nʼihi ọrụ ike ha: n'ihi na ọ bụrụ na ha adaa, otu onye ga-eweli ibe ya elu: ma ahụhụ dịrị onye ọ bụ nke naanị ya mgbe ọ daa; n'ihi na ọ dịghị onye ọzọ iweli ya elu!\" Chineke kere mmadụ maka obodo. Agha ị na-emeri naanị gị bụkarị agha nke ahụ Kraịst kwadebere inyere gị aka imeri.\n\nNdị Galeshia 6:2: \"Bulụrụnụ ibe unu ibu arọ unu, otu a kwa ka unu ga-eji mezuo iwu Kraịst.\" Ibu ị na-ebu naanị gị adịghị ka a bu ya naanị gị. Iwu Kraịst bụ ibu ibu ọnụ — obodo na-akwagide ogwe aka onye na-ada mba.",
      "repentance": "Onye pụrụ ikwagide ogwe aka gị n'agha ị na-emeri naanị gị? Kpọtụrụ Erọn na Hoa Chineke tinyere na ndụ gị. Nganga nke na-eme ka ị nọrọ naanị gị na-efunahụ gị mmeri obodo ga-emeri.",
      "prayer": "Onyenwe anyị, ana m ekwupụta na anọwo m na-alụ naanị m agha nke ekwesighị ka a lụọ naanị onye. Nye m ịdị umeala n'obi ịkpọtụrụ ndị ọzọ. Nyere m aka ịchọta Erọn na Hoa i tinyere na ndụ m. Kwe ka m nata enyemaka nke na-eme ka mmeri ahụ ga-ekwe omume. Amen."
    }
  },
  "ha": {
    "137": {
      "hook": "Ƙwayar mustad ba ta neman gafara don ba ta zama itacen oak ba tukuna.",
      "body": "Matiyu 17:20: \"Hakika ina gaya muku, in kuna da bangaskiya kamar ƙwayar mustad, za ku ce wa dutsen nan, Ka tashi daga nan zuwa can; zai kuwa tashi; kuma babu abin da zai gagara gare ku.\" Ƙwayar mustad ita ce mafi ƙanƙanta cikin dukkan iri. Yesu ya zaɓe ta da gangan. Bai kafa mizani mai tsayi ba. Ya kafa mafi ƙasƙancin mizani da ake iyawa — kuma ya ce hakan ya isa.\n\nAlmajiran sun kasa fitar da aljani suka kuma tambaya me ya sa. Amsar ba \"kuna buƙatar ƙarin iko ba\" ko \"kuna buƙatar ƙarin baiwa\". Bangaskiya ce mai girman ƙwayar mustad. Ƙaramar bangaskiya a shugabanci daidai, wadda aka nufa ga Mutumin da ya dace, ta fi ƙarfi mara iyaka fiye da babban tabbaci da aka sanya a kan kuskuren abu.\n\nUban yaron da aljani ya kama ya kawo bukatarsa da furuci na gaskiya cikin addu'a guda: \"Na gaskata; ka taimake ni cikin rashin gaskatawata!\" (Markus 9:24). Yesu ya warkar da yaron. An karɓi addu'ar. Ƙarama, gaskiya, bangaskiya mai cakuɗe da shakka ta isa. Bangaskiyarka ba dole ta zama girman dutse ba don ta motsa duwatsu. Dole a nufe ta ga wanda yake motsa su.",
      "repentance": "Ka daina jira har bangaskiyarka ta ji kamar isasshiya. Ka kawo ƙaramar bangaskiya da kake da ita. Ka nufe ta ga Mutumin da ya dace. Ta isa.",
      "prayer": "Ubangiji, na kawo bangaskiyar da nake da ita — ƙarama kamar ƙwayar mustad, cakuɗe da shakka. Ina nufe ta gareka. Ba ga amincewa ta kaina ba, ba ga jin ƙarfina na ruhaniya ba — gareka. Ka motsa abin da ya kamata a motsa. Bangaskiyata ƙarama ce. Kai ba haka ba. Amin."
    },
    "152": {
      "hook": "Jinƙai wanda ya rufe kasawa ta farko shi ne ya rufe ta ɗari.",
      "body": "Karin Magana 24:16: \"Gama mai adalci yakan fāɗi sau bakwai, ya sāke tashi; amma miyagu su kan yi tuntuɓe cikin masifa.\" Sau bakwai. Mai adalci — ba wanda ba shi da zunubi ba, sai dai wanda aka mai da shi mai adalci a cikin Kristi — yana fāɗuwa sau bakwai. Yana kuma tashi sau bakwai. Halayen da suke bayyana shi ba fāɗuwa ba ce. Tashi ne. Ana bayyana masu adalci ta abin da suke yi bayan fāɗuwa.\n\nMikahu 7:8: \"Kada ki yi murna a kaina, ya kishiyata. Ko na fāɗi, zan tashi; ko na zauna cikin duhu, Ubangiji zai zama haskena.\" Babbar makamin abokin gāba akan gazawa maimaitawa shine raɗa: ba za ka taɓa canjawa ba, Allah ya daina bincikanka, wannan shine ainihin kai. Wannan ƙarya ce da aka tsara musamman don hana tashin.\n\nMaraice 3:22-23: \"Domin jinƙan Ubangiji ba ya ƙarewa, tausayinsa ba ya gushewa. Sabo ne kowace safiya.\" Sabo kowace safiya. Jinƙan da ake da shi yau ba a rage shi ta yawan buƙatar da aka yi jiya ba. Tanadin ba ya ƙarewa ta buƙata. Ana sabunta shi. Jinƙai iri ɗaya da aka samu a gazawar farko yana nan bayan ɗari. Ka tashi.",
      "repentance": "Ka sake gazawa. Wannan ba ƙarshen jumlar ba ne. Ka tashi. Ka karɓi jinƙan da yake sabo wannan safiya. Ka furta takamaimai. Ka karɓi cikakke. Ka sake tashi.",
      "prayer": "Ubangiji, na sake gazawa. Na furta takamaimai abin da na yi. Na karɓi jinƙan da yake sabo wannan safiya. Ni mai adalci ne a cikin Kristi — saboda haka na tashi. Na sake tashi. Na gode don jinƙai wanda ba ya ƙarewa. Amin."
    },
    "163": {
      "hook": "Yesu ya magance kunya a kan gicciye. Ba shi da wani da'awar shari'a a kanka.",
      "body": "Ibraniyawa 12:2: Yesu ya jimre gicciye \"yana raina kunyarsa.\" Rainawa — ƙyama, kula da rashin daraja, ƙin a rinjaye shi. An tsara gicciye don samar da mafi girman kunya — bayyanawa a gaban jama'a, alaƙa da laifi, kunya. Yesu ya raine ta. Bai kawai jimre da kunyar ba. Ya ƙi a bayyana shi da ita.\n\nIsha'ya 53:4-5: \"Hakika ya ɗauki ciwonmu, ya kuma ɗauki baƙin cikinmu... an huda shi saboda laifofinmu... ta wurin raunukansa aka warkar da mu.\" Ya ɗauki kunyarmu — bayyanawa, laifi, jin rashin cancanta na dindindin. Ya ɗauke ta cikin kansa domin kada ta ƙara samun da'awa a kan waɗanda suke nasa.\n\nRomawa 10:11: \"Duk mai gaskata da shi ba za a kunyata shi ba.\" Kullum. Ba \"za a ɗan rage kunya ba.\" Ba za a taɓa kunyata shi ba. Hukuncin gicciye shine cewa kunya ba ta da iko a kan waɗanda suke cikin Kristi. Ba don ba a yi laifukan ba. Domin wanda ya ɗauke su ya sanar da cewa an gama da su.",
      "repentance": "Kunyar da take rufe ka ba ta da iko na shari'a a kanka a cikin Kristi. Ka kawo ta wurin gicciye yau ka bar ta a sha ta wurin wanda ya raina kunya saboda kai.",
      "prayer": "Ubangiji Yesu, na kawo kunyata wurin gicciye yau — abubuwan da na yi, abubuwan da aka yi mini. Ka raina kunya. Ka ɗauki tawa. Na karɓi sanarwarka: ba za a taɓa kunyata ni ba. An rufe ni. Ni ɗan'ci ne. Na fita daga ƙarƙashin kunya yau. Amin."
    },
    "176": {
      "hook": "Allah baya jira sai an gyara ka kafin ya yi amfani da kai. Yana amfani da karyewa.",
      "body": "2 Korintiyawa 4:7-10: \"Amma muna da wannan taska a cikin kwanunan yumɓu, don a bayyana wannan iko mai girma ya fito daga Allah ba daga gare mu ba. Ana matsalar mu ta kowace hanya, amma ba a shanya mu ba; ana rikita mu, amma ba mu yanke ƙauna ba; ana tsananta mana, amma ba a yashe mu ba; ana buge mu ƙasa, amma ba a hallaka mu ba.\" Kwanunan yumɓu. Na kowa, masu iya karyewa, na yau da kullum. Suna riƙe da taskar bishara. Rashin ƙarfin kwanon ba bazata ba ne. An tsara shi da gangan — yana sa ikon da yake ciki ba za a musanta ba.\n\nGidiyona yana ɓoye a matsin inabi lokacin da mala'ika ya kira shi \"jarumin yaƙi\" (Alƙalawa 6:11-12). Bai zama jarumi tukuna ba. Yana tsoro. Sunan annabci ne, ba bayanin gaskiya ba. Allah ya kira abin da bai kasance ba kamar dai yana nan — sannan ya mai da shi haka. Kiran Allah ya gabaci shirin Allah. Mutumin da Ya kira ba shine kayan da aka kammala ba. Su ne albarkatun ƙasa.\n\nTsagewar da take a kwanon yumɓu ba shaida ba ce cewa Allah ya yi kuskure. Su ne wuraren da haskensa yake fita. Karyewarka ba shamaki ba ne ga amfaninka. A hannun Allah wanda ya kware wajen amfani da wanda ya karye, shi ne ainihin abin da yake sa ka zama mai amfani sosai.",
      "repentance": "Ka daina jira har sai ka cika don ka miƙa kanka ga Allah. Zo cikin karyewa. Ana iya ganin taskar kawai ta cikin tsageru. Abin da yake ji kamar mafi girman ƙuntatawarka na iya zama mafi girman hanyar Allah ta shiga.",
      "prayer": "Ubangiji, na zo cikin karyewa. Na daina yin kamar na cika sosai don in yi amfani. Na miƙa maka kwanon yumɓu — mai tsageru, na kowa, mai rauni. Bari taskarka ta haskaka ta cikin tsageru. Ka yi amfani da abin da ya karye. Ka yi amfani da abin da wasu suka ƙi. Ikon zai bayyana a fili nasu ka. Amin."
    },
    "188": {
      "hook": "Akwai yaƙe-yaƙe da suke buƙatar jikin Kristi. Ba za ka iya cin nasara su kaɗai ba.",
      "body": "Fitowa 17:11-12: \"Kuma in dai Musa yana rike da hannuwansa sama, Isra'ilawa suna cin nasara, amma in ya sauke hannuwansa, Amalekawa su ka cin nasara. Amma hannuwan Musa suka gaji; sai suka ɗauko dutse suka sa masa, ya zauna a kai; Haruna da Hur suka riƙe hannuwansa, ɗaya a gefe ɗaya, ɗaya kuma a gefe kuma; ta haka hannuwansa suka tsaya daram har fadowar rana.\" Musa ba zai iya riƙe hannuwansa sama shi kaɗai ba. Ya buƙaci Haruna da Hur. Nasarar ta buƙaci jiki ya yi aiki tare.\n\nMai-Wa'azi 4:9-10: \"Biyu sun fi ɗaya, gama suna da lada mai kyau saboda aikinsu. Gama in sun faɗi, ɗaya zai ta da abokinsa: amma kaiton wanda ya kaɗai idan ya faɗi; gama ba shi da wani da zai ta da shi!\" Allah ya tsara mutane don al'umma. Yaƙin da kake rasa shi kaɗai galibi shine yaƙin da jikin Kristi ya shirya taimaka maka ka ci nasara.\n\nGalatiyawa 6:2: \"Ku ɗaukar wa juna nauyi, ta haka za ku cika dokar Kristi.\" Nauyin da kake ɗauka kai kaɗai ba a nufi ka ɗauke shi kai kaɗai ba. Dokar Kristi ita ce ɗaukar nauyi na juna — al'umma tana riƙe da hannun wanda yake gab da fāɗuwa.",
      "repentance": "Wanene zai iya riƙe hannunka a yaƙin da kake rasa shi kaɗai? Ka kai hannu ga Haruna da Hur da Allah ya sanya a rayuwarka. Girman kai wanda yake sa ka kaɗaita yana sa ka rasa nasarorin da al'umma za ta ci.",
      "prayer": "Ubangiji, na yarda cewa ina yaƙi shi kaɗai abin da ba a nufa in yi shi kaɗai ba. Ba ni tawali'u don in kai hannu. Ka taimake ni in sami Haruna da Hur da Ka sanya a rayuwata. Bari in karɓi taimakon da yake sa nasara ta yiwu. Amin."
    }
  },
  "pcm": {
    "137": {
      "hook": "Mustard seed no dey beg pardon say e never turn oak tree yet.",
      "body": "Matthew 17:20: \"Truly I dey tell una, if una get faith wey small reach mustard seed, una fit tell dis mountain, 'Move from here go there,' e go move. Nothing go impossible for una.\" Mustard seed na di smallest of all seeds. Jesus choose am on purpose. E no dey set high bar. E dey set di lowest bar wey fit dey — e talk say dat one dey enough.\n\nDi disciples don just fail to cast out demon and dem ask why. Di answer no be \"una need more power\" or \"una need more gift.\" Na faith wey be like mustard seed size. Small faith wey dey correct direction, wey dey point to di correct Person, get power well well pass big confidence wey dem put for wrong thing.\n\nDi father of di boy wey demon possess bring both di need and honest confession for di same prayer: \"I believe; help my unbelief!\" (Mark 9:24). Jesus heal di boy. Di prayer dem accept am. Di small, honest, mixed faith enough. Your faith no need to big reach mountain before e go fit move mountain. E need to point to di One wey dey move dem.",
      "repentance": "Stop to dey wait until your faith feel like say e big reach. Bring di small faith wey you get. Point am to di correct Person. E dey enough.",
      "prayer": "Lord, I dey bring di faith wey I get — small like mustard seed, mixed with doubt. I dey point am to You. No be to my own confidence, no be to how I dey feel my spiritual strength — na to You. Move wetin need to move. My faith small. You no be so. Amen."
    },
    "152": {
      "hook": "Di same mercy wey cover di first failure na im dey cover di hundredth one.",
      "body": "Proverbs 24:16: \"Because righteous man dey fall seven times, e go rise again, but wicked people dey stumble when trouble strike.\" Seven times. Di righteous — no be person wey no get sin, but those wey God don make righteous inside Christ — dey fall seven times. And dey rise seven times. Di thing wey define am no be di falling. Na di rising. Dem dey define righteous people by wetin dem dey do afta dem fall.\n\nMicah 7:8: \"No gloat over me, my enemy! Even as I fall, I go rise. Even as I dey sit for darkness, di LORD go be my light.\" Di main weapon of enemy against repeated failure na di whisper: you no go ever change, God don give up on you, na so you be. Dis one na lie wey dem design specifically to stop di rising.\n\nLamentations 3:22-23: \"Because of di LORD great love we no dey consumed, because im compassion no dey fail. Dem dey new every morning.\" New every morning. Di mercy wey dey available today no dey reduce because of how much wey needed yesterday. Di supply no dey finish by demand. Dem dey renew am. Di same mercy wey dey available for di first failure dey available afta di hundredth. Get up.",
      "repentance": "You don fail again. Dat one no be di end of di sentence. Get up. Receive di mercy wey new dis morning. Confess am specifically. Receive am completely. Rise again.",
      "prayer": "Lord, I don fail again. I dey confess specifically wetin I do. I dey receive di mercy wey new dis morning. I righteous inside Christ — so I dey rise. I dey get up again. Thank You for mercy wey no dey finish. Amen."
    },
    "163": {
      "hook": "Jesus don already handle shame for cross. E no get any legal claim for your body.",
      "body": "Hebrews 12:2: Jesus endure di cross \"e no gree let shame carry Am.\" To no gree — to despise am, treat am with disgrace, refuse make e affect you. Dem design di cross to bring maximum shame — public exposure, criminal association, humiliation. Jesus no gree for am. E no just endure di shame. E refuse make dem define Am with am.\n\nIsaiah 53:4-5: \"For real, E carry our pain, E bear our suffering...dem pierce Am for our sin...na by Im wounds we don heal.\" E carry our shame — di exposure, di guilt, di feeling of permanent unworthiness. E carry am enter Imself so dat e no go get more claim for those wey belong to Am.\n\nRomans 10:11: \"Anybody wey believe for Am no go ever shame.\" Never. E no be \"go get small shame.\" No go ever shame. Di verdict of di cross be say shame no get authority for those wey dey inside Christ. No be because di wrong things no happen. Na because di One wey carry dem don talk say dem don finish.",
      "repentance": "Di shame wey don dey cover you no get legal authority for your body inside Christ. Bring am come di cross today make di One wey no gree for shame absorb am for your behalf.",
      "prayer": "Lord Jesus, I dey bring my shame come di cross today — di things wey I do, di things wey dem do to me. You no gree for shame. You carry mine. I dey receive Your declaration: I no go ever shame. Dem don cover me. I free. I dey waka comot from under shame today. Amen."
    },
    "176": {
      "hook": "God no dey wait until dem fix you before E go use you. E dey use di breaking.",
      "body": "2 Corinthians 4:7-10: \"But we get dis treasure inside clay pot, so dat di power wey too much go show say na from God, no be from us. Dem dey press us for every side, but dem no fit crush us; we dey confuse, but we no dey despair; dem dey persecute us, but dem no abandon us; dem strike us down, but dem no destroy us.\" Clay pot. Common, e fit break, ordinary. And e dey carry di treasure of di gospel. How di container weak no be by mistake. Na on purpose — e dey make di power wey dey inside no fit deny.\n\nGideon dey hide for wine press when angel call am \"mighty warrior\" (Judges 6:11-12). E never mighty yet. E fear catch am. Di name na prophecy, no be description. God call wetin no dey as if e dey — den make am so. God calling dey come before God equipping. Di person wey E call no be finish product. Na raw material.\n\nDi cracks for di clay pot no be evidence say God make mistake. Na di space wey Im light dey pass comot. Your breaking no be barrier to how you go useful. For hand of God wey specialize for using broken things, na di very thing wey dey make you useful pass.",
      "repentance": "Stop to dey wait until you complete before you go offer yourself to God. Come as you dey broken. Di treasure fit show only through di cracks. Wetin dey feel like your biggest limitation fit be God biggest point of access.",
      "prayer": "Lord, I dey come broken. I dey stop to pretend say I complete reach to useful. I dey offer You di clay pot — wey get crack, ordinary, weak. Make Your treasure shine through di cracks. Use wetin break. Use wetin other people reject. Di power go clearly be Yours. Amen."
    },
    "188": {
      "hook": "Some battles dey wey need di body of Christ. You no fit win dem alone.",
      "body": "Exodus 17:11-12: \"As Moses dey hold up im hand, na so Israel dey win, but anytime wey e lower im hand, na so Amalek dey win. When Moses hand come tire, dem carry stone put am under am make e sit down. Aaron and Hur hold im hand up — one for one side, di other one for di other side — so dat im hand remain steady until sun set.\" Moses no fit hold im hand up alone. E need Aaron and Hur. Di victory need di body to work together.\n\nEcclesiastes 4:9-10: \"Two better pass one, because dem get good reward for dia work: If any of dem fall down, one fit help di other one stand up. But sorry for anybody wey fall down wey no get anybody to help dem stand up!\" God design human beings for community. Di battle wey you dey lose alone na often di battle wey di body of Christ dem equip to help you win.\n\nGalatians 6:2: \"Carry each other burden, and dis way una go fulfil di law of Christ.\" Di burden wey you don dey carry alone, dem no mean make you carry am alone. Di law of Christ na to carry burden together — di community dey hold up di arms of di person wey dey falter.",
      "repentance": "Who fit hold up your arms for di battle wey you dey lose alone? Reach out to di Aaron and Hur wey God don put for your life. Di pride wey dey keep you isolated dey cost you victories wey community for don win.",
      "prayer": "Lord, I acknowledge say I don dey fight alone wetin dem no mean make I fight alone. Give me humility to reach out. Help me find di Aaron and Hur wey You don put for my life. Make I receive di help wey go make di victory possible. Amen."
    }
  }
};

if (typeof mergeTractsI18n === 'function') mergeTractsI18n(TRACTS_I18N_STRUGGLE_P3);